
var e;e||(e=typeof Module !== 'undefined' ? Module : {});e.Ia||(e.Ia=0);e.Ia++;
(function(a){function b(p,u,n){var q=new XMLHttpRequest;q.open("GET",p,!0);q.responseType="arraybuffer";q.onprogress=function(v){var g=u;v.total&&(g=v.total);if(v.loaded){q.ia?e.pa[p].loaded=v.loaded:(q.ia=!0,e.pa||(e.pa={}),e.pa[p]={loaded:v.loaded,total:g});var t=g=v=0,w;for(w in e.pa){var A=e.pa[w];v+=A.total;g+=A.loaded;t++}v=Math.ceil(v*e.Ia/t);e.setStatus&&e.setStatus("Downloading data... ("+g+"/"+v+")")}else!e.pa&&e.setStatus&&e.setStatus("Downloading data...")};q.onerror=function(){throw Error("NetworkError for: "+
p);};q.onload=function(){if(200==q.status||304==q.status||206==q.status||0==q.status&&q.response)n(q.response);else throw Error(q.statusText+" : "+q.responseURL);};q.send(null)}function c(p){console.error("package error:",p)}function d(){function p(v,g,t){this.start=v;this.Ha=g;this.audio=t}function u(v){if(!v)throw"Loading data file failed."+Error().stack;if(!(v instanceof ArrayBuffer))throw"bad input to processPackageData"+Error().stack;v=new Uint8Array(v);p.prototype.wb=v;v=a.files;for(var g=0;g<
v.length;++g)p.prototype.ia[v[g].filename].onload();e.removeRunDependency("datafile_index.data")}e.FS_createPath("/","src",!0,!0);e.FS_createPath("/src","shaders",!0,!0);p.prototype={ia:{},open:function(v,g){this.name=g;this.ia[g]=this;e.addRunDependency("fp "+this.name)},send:function(){},onload:function(){this.ub(this.wb.subarray(this.start,this.Ha))},ub:function(v){e.FS_createDataFile(this.name,null,v,!0,!0,!0);e.removeRunDependency("fp "+this.name);this.ia[this.name]=null}};for(var n=a.files,
q=0;q<n.length;++q)(new p(n[q].start,n[q].end,n[q].audio)).open("GET",n[q].filename);e.addRunDependency("datafile_index.data");e.ib||(e.ib={});e.ib["index.data"]={cc:!1};r?(u(r),r=null):k=u}if("object"===typeof window)window.encodeURIComponent(window.location.pathname.toString().substring(0,window.location.pathname.toString().lastIndexOf("/"))+"/");else if("undefined"!==typeof location)encodeURIComponent(location.pathname.toString().substring(0,location.pathname.toString().lastIndexOf("/"))+"/");
else throw"using preloaded data can only be done on a web page or in a web worker";"function"!==typeof e.locateFilePackage||e.locateFile||(e.locateFile=e.locateFilePackage,l("warning: you defined Module.locateFilePackage, that has been renamed to Module.locateFile (using your locateFilePackage for now)"));var f=e.locateFile?e.locateFile("index.data",""):"index.data",h=a.remote_package_size,k=null,r=e.getPreloadedPackage?e.getPreloadedPackage(f,h):null;r||b(f,h,function(p){k?(k(p),k=null):r=p},c);
e.calledRun?d():(e.preRun||(e.preRun=[]),e.preRun.push(d))})({files:[{filename:"/src/shaders/tri.vert",start:0,end:416,audio:0},{filename:"/src/shaders/tri.frag",start:416,end:1446,audio:0}],remote_package_size:1446,package_uuid:"d29b864f-aee3-41ed-b8e7-b6b26ae61eda"});var aa={},m;for(m in e)e.hasOwnProperty(m)&&(aa[m]=e[m]);var ba="./this.program";function ca(a,b){throw b;}var da=!1,x=!1,ea=!1,fa=!1;da="object"===typeof window;x="function"===typeof importScripts;
ea="object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node;fa=!da&&!ea&&!x;var y="",ha,ja,ka,la,ma;
if(ea)y=x?require("path").dirname(y)+"/":__dirname+"/",ha=function(a,b){la||(la=require("fs"));ma||(ma=require("path"));a=ma.normalize(a);return la.readFileSync(a,b?null:"utf8")},ka=function(a){a=ha(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a},1<process.argv.length&&(ba=process.argv[1].replace(/\\/g,"/")),process.argv.slice(2),"undefined"!==typeof module&&(module.exports=e),process.on("uncaughtException",function(a){if(!(a instanceof na))throw a;}),process.on("unhandledRejection",
z),ca=function(a){process.exit(a)},e.inspect=function(){return"[Emscripten Module object]"};else if(fa)"undefined"!=typeof read&&(ha=function(a){return read(a)}),ka=function(a){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(a));a=read(a,"binary");assert("object"===typeof a);return a},"function"===typeof quit&&(ca=function(a){quit(a)}),"undefined"!==typeof print&&("undefined"===typeof console&&(console={}),console.log=print,console.warn=console.error="undefined"!==typeof printErr?
printErr:print);else if(da||x)x?y=self.location.href:"undefined"!==typeof document&&document.currentScript&&(y=document.currentScript.src),y=0!==y.indexOf("blob:")?y.substr(0,y.lastIndexOf("/")+1):"",ha=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},x&&(ka=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),ja=function(a,b,c){var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType=
"arraybuffer";d.onload=function(){200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)};var oa=e.print||console.log.bind(console),l=e.printErr||console.warn.bind(console);for(m in aa)aa.hasOwnProperty(m)&&(e[m]=aa[m]);aa=null;e.thisProgram&&(ba=e.thisProgram);e.quit&&(ca=e.quit);function pa(a){qa||(qa={});qa[a]||(qa[a]=1,l(a))}var qa,ra;e.wasmBinary&&(ra=e.wasmBinary);var noExitRuntime=e.noExitRuntime||!0;"object"!==typeof WebAssembly&&z("no native wasm support detected");
function sa(a,b,c){c=c||"i8";"*"===c.charAt(c.length-1)&&(c="i32");switch(c){case "i1":B[a>>0]=b;break;case "i8":B[a>>0]=b;break;case "i16":ta[a>>1]=b;break;case "i32":C[a>>2]=b;break;case "i64":ua=[b>>>0,(D=b,1<=+Math.abs(D)?0<D?(Math.min(+Math.floor(D/4294967296),4294967295)|0)>>>0:~~+Math.ceil((D-+(~~D>>>0))/4294967296)>>>0:0)];C[a>>2]=ua[0];C[a+4>>2]=ua[1];break;case "float":va[a>>2]=b;break;case "double":wa[a>>3]=b;break;default:z("invalid type for setValue: "+c)}}var xa,ya=!1,za;
function assert(a,b){a||z("Assertion failed: "+b)}function Aa(a){var b=Ba(a.length);a.subarray||a.slice?F.set(a,b):F.set(new Uint8Array(a),b);return b}var Ca="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function Da(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.subarray&&Ca)return Ca.decode(a.subarray(b,c));for(d="";b<c;){var f=a[b++];if(f&128){var h=a[b++]&63;if(192==(f&224))d+=String.fromCharCode((f&31)<<6|h);else{var k=a[b++]&63;f=224==(f&240)?(f&15)<<12|h<<6|k:(f&7)<<18|h<<12|k<<6|a[b++]&63;65536>f?d+=String.fromCharCode(f):(f-=65536,d+=String.fromCharCode(55296|f>>10,56320|f&1023))}}else d+=String.fromCharCode(f)}return d}function Ea(a,b){return a?Da(F,a,b):""}
function Fa(a,b,c){var d=0;if(!(0<c))return 0;var f=d;c=d+c-1;for(var h=0;h<a.length;++h){var k=a.charCodeAt(h);if(55296<=k&&57343>=k){var r=a.charCodeAt(++h);k=65536+((k&1023)<<10)|r&1023}if(127>=k){if(d>=c)break;b[d++]=k}else{if(2047>=k){if(d+1>=c)break;b[d++]=192|k>>6}else{if(65535>=k){if(d+2>=c)break;b[d++]=224|k>>12}else{if(d+3>=c)break;b[d++]=240|k>>18;b[d++]=128|k>>12&63}b[d++]=128|k>>6&63}b[d++]=128|k&63}}b[d]=0;return d-f}
function Ga(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}return b}var Ha,B,F,ta,C,Ia,va,wa,G,Ja=[],Ka=[],La=[],Ma=[];function Na(){var a=e.preRun.shift();Ja.unshift(a)}var H=0,Oa=null,Pa=null;function Qa(){H++;e.monitorRunDependencies&&e.monitorRunDependencies(H)}
function Ra(){H--;e.monitorRunDependencies&&e.monitorRunDependencies(H);if(0==H&&(null!==Oa&&(clearInterval(Oa),Oa=null),Pa)){var a=Pa;Pa=null;a()}}e.preloadedImages={};e.preloadedAudios={};function z(a){if(e.onAbort)e.onAbort(a);l(a);ya=!0;za=1;throw new WebAssembly.RuntimeError("abort("+a+"). Build with -s ASSERTIONS=1 for more info.");}function Sa(a){var b=I;return String.prototype.startsWith?b.startsWith(a):0===b.indexOf(a)}function Ta(){return Sa("data:application/octet-stream;base64,")}
var I="index.wasm";if(!Ta()){var Ua=I;I=e.locateFile?e.locateFile(Ua,y):y+Ua}function Va(){var a=I;try{if(a==I&&ra)return new Uint8Array(ra);if(ka)return ka(a);throw"both async and sync fetching of the wasm failed";}catch(b){z(b)}}
function Wa(){if(!ra&&(da||x)){if("function"===typeof fetch&&!Sa("file://"))return fetch(I,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+I+"'";return a.arrayBuffer()}).catch(function(){return Va()});if(ja)return new Promise(function(a,b){ja(I,function(c){a(new Uint8Array(c))},b)})}return Promise.resolve().then(function(){return Va()})}
var D,ua,Xa={16018060:function(){return window.innerWidth||document.documentElement.clientWidth||document.body.clientWidth},16018178:function(){return window.innerHeight||document.documentElement.clientHeight||document.body.clientHeight}};function Ya(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(e);else{var c=b.vb;"number"===typeof c?void 0===b.xa?G.get(c)():G.get(c)(b.xa):c(void 0===b.xa?null:b.xa)}}}
function Za(a){this.sa=a-16;this.Mb=function(b){C[this.sa+8>>2]=b};this.Jb=function(b){C[this.sa+0>>2]=b};this.Kb=function(){C[this.sa+4>>2]=0};this.Ib=function(){B[this.sa+12>>0]=0};this.Lb=function(){B[this.sa+13>>0]=0};this.yb=function(b,c){this.Mb(b);this.Jb(c);this.Kb();this.Ib();this.Lb()}}var $a=0;function ab(a,b){for(var c=0,d=a.length-1;0<=d;d--){var f=a[d];"."===f?a.splice(d,1):".."===f?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a}
function J(a){var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=ab(a.split("/").filter(function(d){return!!d}),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a}function bb(a){var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b}function cb(a){if("/"===a)return"/";a=J(a);a=a.replace(/\/$/,"");var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)}
function db(){if("object"===typeof crypto&&"function"===typeof crypto.getRandomValues){var a=new Uint8Array(1);return function(){crypto.getRandomValues(a);return a[0]}}if(ea)try{var b=require("crypto");return function(){return b.randomBytes(1)[0]}}catch(c){}return function(){z("randomDevice")}}
function eb(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:"/";if("string"!==typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=ab(a.split("/").filter(function(d){return!!d}),!b).join("/");return(b?"/":"")+a||"."}var fb=[];function gb(a,b){fb[a]={input:[],output:[],ra:b};hb(a,ib)}
var ib={open:function(a){var b=fb[a.node.rdev];if(!b)throw new K(43);a.tty=b;a.seekable=!1},close:function(a){a.tty.ra.flush(a.tty)},flush:function(a){a.tty.ra.flush(a.tty)},read:function(a,b,c,d){if(!a.tty||!a.tty.ra.Ya)throw new K(60);for(var f=0,h=0;h<d;h++){try{var k=a.tty.ra.Ya(a.tty)}catch(r){throw new K(29);}if(void 0===k&&0===f)throw new K(6);if(null===k||void 0===k)break;f++;b[c+h]=k}f&&(a.node.timestamp=Date.now());return f},write:function(a,b,c,d){if(!a.tty||!a.tty.ra.Na)throw new K(60);
try{for(var f=0;f<d;f++)a.tty.ra.Na(a.tty,b[c+f])}catch(h){throw new K(29);}d&&(a.node.timestamp=Date.now());return f}},kb={Ya:function(a){if(!a.input.length){var b=null;if(ea){var c=Buffer.ia?Buffer.ia(256):new Buffer(256),d=0;try{d=la.readSync(process.stdin.fd,c,0,256,null)}catch(f){if(-1!=f.toString().indexOf("EOF"))d=0;else throw f;}0<d?b=c.slice(0,d).toString("utf-8"):b=null}else"undefined"!=typeof window&&"function"==typeof window.prompt?(b=window.prompt("Input: "),null!==b&&(b+="\n")):"function"==
typeof readline&&(b=readline(),null!==b&&(b+="\n"));if(!b)return null;a.input=jb(b,!0)}return a.input.shift()},Na:function(a,b){null===b||10===b?(oa(Da(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(oa(Da(a.output,0)),a.output=[])}},lb={Na:function(a,b){null===b||10===b?(l(Da(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(l(Da(a.output,0)),a.output=[])}},L={ka:null,ma:function(){return L.createNode(null,
"/",16895,0)},createNode:function(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new K(63);L.ka||(L.ka={dir:{node:{na:L.ea.na,ja:L.ea.ja,lookup:L.ea.lookup,za:L.ea.za,rename:L.ea.rename,unlink:L.ea.unlink,rmdir:L.ea.rmdir,readdir:L.ea.readdir,symlink:L.ea.symlink},stream:{oa:L.fa.oa}},file:{node:{na:L.ea.na,ja:L.ea.ja},stream:{oa:L.fa.oa,read:L.fa.read,write:L.fa.write,Pa:L.fa.Pa,cb:L.fa.cb,gb:L.fa.gb}},link:{node:{na:L.ea.na,ja:L.ea.ja,readlink:L.ea.readlink},stream:{}},Sa:{node:{na:L.ea.na,
ja:L.ea.ja},stream:mb}});c=nb(a,b,c,d);16384===(c.mode&61440)?(c.ea=L.ka.dir.node,c.fa=L.ka.dir.stream,c.da={}):32768===(c.mode&61440)?(c.ea=L.ka.file.node,c.fa=L.ka.file.stream,c.ga=0,c.da=null):40960===(c.mode&61440)?(c.ea=L.ka.link.node,c.fa=L.ka.link.stream):8192===(c.mode&61440)&&(c.ea=L.ka.Sa.node,c.fa=L.ka.Sa.stream);c.timestamp=Date.now();a&&(a.da[b]=c,a.timestamp=c.timestamp);return c},dc:function(a){return a.da?a.da.subarray?a.da.subarray(0,a.ga):new Uint8Array(a.da):new Uint8Array(0)},
Ua:function(a,b){var c=a.da?a.da.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)>>>0),0!=c&&(b=Math.max(b,256)),c=a.da,a.da=new Uint8Array(b),0<a.ga&&a.da.set(c.subarray(0,a.ga),0))},Gb:function(a,b){if(a.ga!=b)if(0==b)a.da=null,a.ga=0;else{var c=a.da;a.da=new Uint8Array(b);c&&a.da.set(c.subarray(0,Math.min(b,a.ga)));a.ga=b}},ea:{na:function(a){var b={};b.dev=8192===(a.mode&61440)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;16384===(a.mode&61440)?b.size=4096:32768===
(a.mode&61440)?b.size=a.ga:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.atime=new Date(a.timestamp);b.mtime=new Date(a.timestamp);b.ctime=new Date(a.timestamp);b.rb=4096;b.blocks=Math.ceil(b.size/b.rb);return b},ja:function(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);void 0!==b.size&&L.Gb(a,b.size)},lookup:function(){throw ob[44];},za:function(a,b,c,d){return L.createNode(a,b,c,d)},rename:function(a,b,c){if(16384===(a.mode&61440)){try{var d=pb(b,
c)}catch(h){}if(d)for(var f in d.da)throw new K(55);}delete a.parent.da[a.name];a.parent.timestamp=Date.now();a.name=c;b.da[c]=a;b.timestamp=a.parent.timestamp;a.parent=b},unlink:function(a,b){delete a.da[b];a.timestamp=Date.now()},rmdir:function(a,b){var c=pb(a,b),d;for(d in c.da)throw new K(55);delete a.da[b];a.timestamp=Date.now()},readdir:function(a){var b=[".",".."],c;for(c in a.da)a.da.hasOwnProperty(c)&&b.push(c);return b},symlink:function(a,b,c){a=L.createNode(a,b,41471,0);a.link=c;return a},
readlink:function(a){if(40960!==(a.mode&61440))throw new K(28);return a.link}},fa:{read:function(a,b,c,d,f){var h=a.node.da;if(f>=a.node.ga)return 0;a=Math.min(a.node.ga-f,d);if(8<a&&h.subarray)b.set(h.subarray(f,f+a),c);else for(d=0;d<a;d++)b[c+d]=h[f+d];return a},write:function(a,b,c,d,f,h){if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.da||a.da.subarray)){if(h)return a.da=b.subarray(c,c+d),a.ga=d;if(0===a.ga&&0===f)return a.da=b.slice(c,c+d),a.ga=d;if(f+d<=a.ga)return a.da.set(b.subarray(c,
c+d),f),d}L.Ua(a,f+d);if(a.da.subarray&&b.subarray)a.da.set(b.subarray(c,c+d),f);else for(h=0;h<d;h++)a.da[f+h]=b[c+h];a.ga=Math.max(a.ga,f+d);return d},oa:function(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.ga);if(0>b)throw new K(28);return b},Pa:function(a,b,c){L.Ua(a.node,b+c);a.node.ga=Math.max(a.node.ga,b+c)},cb:function(a,b,c,d,f,h){if(0!==b)throw new K(28);if(32768!==(a.node.mode&61440))throw new K(43);a=a.node.da;if(h&2||a.buffer!==Ha){if(0<d||d+c<a.length)a.subarray?
a=a.subarray(d,d+c):a=Array.prototype.slice.call(a,d,d+c);d=!0;h=16384*Math.ceil(c/16384);for(b=Ba(h);c<h;)B[b+c++]=0;c=b;if(!c)throw new K(48);B.set(a,c)}else d=!1,c=a.byteOffset;return{sa:c,Ub:d}},gb:function(a,b,c,d,f){if(32768!==(a.node.mode&61440))throw new K(43);if(f&2)return 0;L.fa.write(a,b,0,d,c,!1);return 0}}},qb=null,rb={},sb=[],tb=1,M=null,ub=!0,N={},K=null,ob={};
function O(a,b){a=eb("/",a);b=b||{};if(!a)return{path:"",node:null};var c={Va:!0,Oa:0},d;for(d in c)void 0===b[d]&&(b[d]=c[d]);if(8<b.Oa)throw new K(32);a=ab(a.split("/").filter(function(k){return!!k}),!1);var f=qb;c="/";for(d=0;d<a.length;d++){var h=d===a.length-1;if(h&&b.parent)break;f=pb(f,a[d]);c=J(c+"/"+a[d]);f.va&&(!h||h&&b.Va)&&(f=f.va.root);if(!h||b.Ja)for(h=0;40960===(f.mode&61440);)if(f=vb(c),c=eb(bb(c),f),f=O(c,{Oa:b.Oa}).node,40<h++)throw new K(32);}return{path:c,node:f}}
function wb(a){for(var b;;){if(a===a.parent)return a=a.ma.eb,b?"/"!==a[a.length-1]?a+"/"+b:a+b:a;b=b?a.name+"/"+b:a.name;a=a.parent}}function xb(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%M.length}function pb(a,b){var c;if(c=(c=yb(a,"x"))?c:a.ea.lookup?0:2)throw new K(c,a);for(c=M[xb(a.id,b)];c;c=c.qa){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.ea.lookup(a,b)}
function nb(a,b,c,d){a=new zb(a,b,c,d);b=xb(a.parent.id,a.name);a.qa=M[b];return M[b]=a}var Ab={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090};function Bb(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}function yb(a,b){if(ub)return 0;if(-1===b.indexOf("r")||a.mode&292){if(-1!==b.indexOf("w")&&!(a.mode&146)||-1!==b.indexOf("x")&&!(a.mode&73))return 2}else return 2;return 0}function Cb(a,b){try{return pb(a,b),20}catch(c){}return yb(a,"wx")}
function Db(){var a=4096;for(var b=0;b<=a;b++)if(!sb[b])return b;throw new K(33);}function Eb(a){Fb||(Fb=function(){},Fb.prototype={});var b=new Fb,c;for(c in a)b[c]=a[c];a=b;b=Db();a.fd=b;return sb[b]=a}var mb={open:function(a){a.fa=rb[a.node.rdev].fa;a.fa.open&&a.fa.open(a)},oa:function(){throw new K(70);}};function hb(a,b){rb[a]={fa:b}}
function Gb(a,b){var c="/"===b,d=!b;if(c&&qb)throw new K(10);if(!c&&!d){var f=O(b,{Va:!1});b=f.path;f=f.node;if(f.va)throw new K(10);if(16384!==(f.mode&61440))throw new K(54);}b={type:a,nc:{},eb:b,Eb:[]};a=a.ma(b);a.ma=b;b.root=a;c?qb=a:f&&(f.va=b,f.ma&&f.ma.Eb.push(b))}function Hb(a,b,c){var d=O(a,{parent:!0}).node;a=cb(a);if(!a||"."===a||".."===a)throw new K(28);var f=Cb(d,a);if(f)throw new K(f);if(!d.ea.za)throw new K(63);return d.ea.za(d,a,b,c)}function P(a){return Hb(a,16895,0)}
function Ib(a,b,c){"undefined"===typeof c&&(c=b,b=438);return Hb(a,b|8192,c)}function Jb(a,b){if(!eb(a))throw new K(44);var c=O(b,{parent:!0}).node;if(!c)throw new K(44);b=cb(b);var d=Cb(c,b);if(d)throw new K(d);if(!c.ea.symlink)throw new K(63);c.ea.symlink(c,b,a)}
function Kb(a){var b=O(a,{parent:!0}).node,c=cb(a),d=pb(b,c);a:{try{var f=pb(b,c)}catch(k){f=k.la;break a}var h=yb(b,"wx");f=h?h:16384===(f.mode&61440)?31:0}if(f)throw new K(f);if(!b.ea.unlink)throw new K(63);if(d.va)throw new K(10);try{N.willDeletePath&&N.willDeletePath(a)}catch(k){l("FS.trackingDelegate['willDeletePath']('"+a+"') threw an exception: "+k.message)}b.ea.unlink(b,c);b=xb(d.parent.id,d.name);if(M[b]===d)M[b]=d.qa;else for(b=M[b];b;){if(b.qa===d){b.qa=d.qa;break}b=b.qa}try{if(N.onDeletePath)N.onDeletePath(a)}catch(k){l("FS.trackingDelegate['onDeletePath']('"+
a+"') threw an exception: "+k.message)}}function vb(a){a=O(a).node;if(!a)throw new K(44);if(!a.ea.readlink)throw new K(28);return eb(wb(a.parent),a.ea.readlink(a))}function Lb(a,b){a="string"===typeof a?O(a,{Ja:!0}).node:a;if(!a.ea.ja)throw new K(63);a.ea.ja(a,{mode:b&4095|a.mode&-4096,timestamp:Date.now()})}
function Mb(a,b,c){if(""===a)throw new K(44);if("string"===typeof b){var d=Ab[b];if("undefined"===typeof d)throw Error("Unknown file open mode: "+b);b=d}c=b&64?("undefined"===typeof c?438:c)&4095|32768:0;if("object"===typeof a)var f=a;else{a=J(a);try{f=O(a,{Ja:!(b&131072)}).node}catch(h){}}d=!1;if(b&64)if(f){if(b&128)throw new K(20);}else f=Hb(a,c,0),d=!0;if(!f)throw new K(44);8192===(f.mode&61440)&&(b&=-513);if(b&65536&&16384!==(f.mode&61440))throw new K(54);if(!d&&(c=f?40960===(f.mode&61440)?32:
16384===(f.mode&61440)&&("r"!==Bb(b)||b&512)?31:yb(f,Bb(b)):44))throw new K(c);if(b&512){c=f;c="string"===typeof c?O(c,{Ja:!0}).node:c;if(!c.ea.ja)throw new K(63);if(16384===(c.mode&61440))throw new K(31);if(32768!==(c.mode&61440))throw new K(28);if(d=yb(c,"w"))throw new K(d);c.ea.ja(c,{size:0,timestamp:Date.now()})}b&=-131713;f=Eb({node:f,path:wb(f),flags:b,seekable:!0,position:0,fa:f.fa,Rb:[],error:!1});f.fa.open&&f.fa.open(f);!e.logReadFiles||b&1||(Nb||(Nb={}),a in Nb||(Nb[a]=1,l("FS.trackingDelegate error on read file: "+
a)));try{N.onOpenFile&&(c=0,1!==(b&2097155)&&(c|=1),0!==(b&2097155)&&(c|=2),N.onOpenFile(a,c))}catch(h){l("FS.trackingDelegate['onOpenFile']('"+a+"', flags) threw an exception: "+h.message)}return f}function Ob(a){if(null===a.fd)throw new K(8);a.La&&(a.La=null);try{a.fa.close&&a.fa.close(a)}catch(b){throw b;}finally{sb[a.fd]=null}a.fd=null}
function Pb(a,b,c){if(null===a.fd)throw new K(8);if(!a.seekable||!a.fa.oa)throw new K(70);if(0!=c&&1!=c&&2!=c)throw new K(28);a.position=a.fa.oa(a,b,c);a.Rb=[]}
function Qb(a,b,c,d,f,h){if(0>d||0>f)throw new K(28);if(null===a.fd)throw new K(8);if(0===(a.flags&2097155))throw new K(8);if(16384===(a.node.mode&61440))throw new K(31);if(!a.fa.write)throw new K(28);a.seekable&&a.flags&1024&&Pb(a,0,2);var k="undefined"!==typeof f;if(!k)f=a.position;else if(!a.seekable)throw new K(70);b=a.fa.write(a,b,c,d,f,h);k||(a.position+=b);try{if(a.path&&N.onWriteToFile)N.onWriteToFile(a.path)}catch(r){l("FS.trackingDelegate['onWriteToFile']('"+a.path+"') threw an exception: "+
r.message)}return b}function Rb(){K||(K=function(a,b){this.node=b;this.Hb=function(c){this.la=c};this.Hb(a);this.message="FS error"},K.prototype=Error(),K.prototype.constructor=K,[44].forEach(function(a){ob[a]=new K(a);ob[a].stack="<generic error, no stack>"}))}var Sb;function Tb(a,b){var c=0;a&&(c|=365);b&&(c|=146);return c}function Ub(a,b){a="string"===typeof a?a:wb(a);for(b=b.split("/").reverse();b.length;){var c=b.pop();if(c){var d=J(a+"/"+c);try{P(d)}catch(f){}a=d}}return d}
function Vb(a,b,c,d){a=J(("string"===typeof a?a:wb(a))+"/"+b);c=Tb(c,d);return Hb(a,(void 0!==c?c:438)&4095|32768,0)}function Wb(a,b,c,d,f,h){a=b?J(("string"===typeof a?a:wb(a))+"/"+b):a;d=Tb(d,f);f=Hb(a,(void 0!==d?d:438)&4095|32768,0);if(c){if("string"===typeof c){a=Array(c.length);b=0;for(var k=c.length;b<k;++b)a[b]=c.charCodeAt(b);c=a}Lb(f,d|146);a=Mb(f,577);Qb(a,c,0,c.length,0,h);Ob(a);Lb(f,d)}return f}
function Q(a,b,c,d){a=J(("string"===typeof a?a:wb(a))+"/"+b);b=Tb(!!c,!!d);Q.ab||(Q.ab=64);var f=Q.ab++<<8|0;hb(f,{open:function(h){h.seekable=!1},close:function(){d&&d.buffer&&d.buffer.length&&d(10)},read:function(h,k,r,p){for(var u=0,n=0;n<p;n++){try{var q=c()}catch(v){throw new K(29);}if(void 0===q&&0===u)throw new K(6);if(null===q||void 0===q)break;u++;k[r+n]=q}u&&(h.node.timestamp=Date.now());return u},write:function(h,k,r,p){for(var u=0;u<p;u++)try{d(k[r+u])}catch(n){throw new K(29);}p&&(h.node.timestamp=
Date.now());return u}});return Ib(a,b,f)}function Xb(a){if(!(a.Bb||a.Cb||a.link||a.da)){if("undefined"!==typeof XMLHttpRequest)throw Error("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");if(ha)try{a.da=jb(ha(a.url),!0),a.ga=a.da.length}catch(b){throw new K(29);}else throw Error("Cannot load without read() or XMLHttpRequest.");}}
function Yb(a,b,c,d,f){function h(){this.Ma=!1;this.ia=[]}h.prototype.get=function(n){if(!(n>this.length-1||0>n)){var q=n%this.chunkSize;return this.Za(n/this.chunkSize|0)[q]}};h.prototype.Ha=function(n){this.Za=n};h.prototype.Qa=function(){var n=new XMLHttpRequest;n.open("HEAD",c,!1);n.send(null);if(!(200<=n.status&&300>n.status||304===n.status))throw Error("Couldn't load "+c+". Status: "+n.status);var q=Number(n.getResponseHeader("Content-length")),v,g=(v=n.getResponseHeader("Accept-Ranges"))&&
"bytes"===v;n=(v=n.getResponseHeader("Content-Encoding"))&&"gzip"===v;var t=1048576;g||(t=q);var w=this;w.Ha(function(A){var T=A*t,ia=(A+1)*t-1;ia=Math.min(ia,q-1);if("undefined"===typeof w.ia[A]){var Id=w.ia;if(T>ia)throw Error("invalid range ("+T+", "+ia+") or no bytes requested!");if(ia>q-1)throw Error("only "+q+" bytes available! programmer error!");var E=new XMLHttpRequest;E.open("GET",c,!1);q!==t&&E.setRequestHeader("Range","bytes="+T+"-"+ia);"undefined"!=typeof Uint8Array&&(E.responseType=
"arraybuffer");E.overrideMimeType&&E.overrideMimeType("text/plain; charset=x-user-defined");E.send(null);if(!(200<=E.status&&300>E.status||304===E.status))throw Error("Couldn't load "+c+". Status: "+E.status);T=void 0!==E.response?new Uint8Array(E.response||[]):jb(E.responseText||"",!0);Id[A]=T}if("undefined"===typeof w.ia[A])throw Error("doXHR failed!");return w.ia[A]});if(n||!q)t=q=1,t=q=this.Za(0).length,oa("LazyFiles on gzip forces download of the whole file when length is accessed");this.qb=
q;this.pb=t;this.Ma=!0};if("undefined"!==typeof XMLHttpRequest){if(!x)throw"Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc";var k=new h;Object.defineProperties(k,{length:{get:function(){this.Ma||this.Qa();return this.qb}},chunkSize:{get:function(){this.Ma||this.Qa();return this.pb}}});var r=void 0}else r=c,k=void 0;var p=Vb(a,b,d,f);k?p.da=k:r&&(p.da=null,p.url=r);Object.defineProperties(p,{ga:{get:function(){return this.da.length}}});
var u={};Object.keys(p.fa).forEach(function(n){var q=p.fa[n];u[n]=function(){Xb(p);return q.apply(null,arguments)}});u.read=function(n,q,v,g,t){Xb(p);n=n.node.da;if(t>=n.length)return 0;g=Math.min(n.length-t,g);if(n.slice)for(var w=0;w<g;w++)q[v+w]=n[t+w];else for(w=0;w<g;w++)q[v+w]=n.get(t+w);return g};p.fa=u;return p}
function Zb(a,b,c,d,f,h,k,r,p,u){function n(g){function t(A){u&&u();r||Wb(a,b,A,d,f,p);h&&h();Ra(v)}var w=!1;e.preloadPlugins.forEach(function(A){!w&&A.canHandle(q)&&(A.handle(g,q,t,function(){k&&k();Ra(v)}),w=!0)});w||t(g)}$b();var q=b?eb(J(a+"/"+b)):a,v="cp "+q;Qa(v);"string"==typeof c?ac(c,function(g){n(g)},k):n(c)}var R={},Fb,Nb,bc=void 0;function cc(){bc+=4;return C[bc-4>>2]}function dc(a){a=sb[a];if(!a)throw new K(8);return a}var S;
ea?S=function(){var a=process.hrtime();return 1E3*a[0]+a[1]/1E6}:"undefined"!==typeof dateNow?S=dateNow:S=function(){return performance.now()};function ec(a){try{a()}catch(b){if(!(b instanceof na)&&"unwind"!==b)throw b&&"object"===typeof b&&b.stack&&l("exception thrown: "+[b,b.stack]),b;}}var fc=!1,U=null,hc=0,ic=null,jc=0,kc=0,lc=0,mc=0,nc=[],oc={},pc,qc,rc,sc=!1,tc=!1,uc=[];
function $b(){function a(){tc=document.pointerLockElement===e.canvas||document.mozPointerLockElement===e.canvas||document.webkitPointerLockElement===e.canvas||document.msPointerLockElement===e.canvas}e.preloadPlugins||(e.preloadPlugins=[]);if(!vc){vc=!0;try{wc=!0}catch(c){wc=!1,console.log("warning: no blob constructor, cannot create blobs with mimetypes")}xc="undefined"!=typeof MozBlobBuilder?MozBlobBuilder:"undefined"!=typeof WebKitBlobBuilder?WebKitBlobBuilder:wc?null:console.log("warning: no BlobBuilder");
yc="undefined"!=typeof window?window.URL?window.URL:window.webkitURL:void 0;e.hb||"undefined"!==typeof yc||(console.log("warning: Browser does not support creating object URLs. Built-in browser image decoding will not be available."),e.hb=!0);e.preloadPlugins.push({canHandle:function(c){return!e.hb&&/\.(jpg|jpeg|png|bmp)$/i.test(c)},handle:function(c,d,f,h){var k=null;if(wc)try{k=new Blob([c],{type:zc(d)}),k.size!==c.length&&(k=new Blob([(new Uint8Array(c)).buffer],{type:zc(d)}))}catch(u){pa("Blob constructor present but fails: "+
u+"; falling back to blob builder")}k||(k=new xc,k.append((new Uint8Array(c)).buffer),k=k.getBlob());var r=yc.createObjectURL(k),p=new Image;p.onload=function(){assert(p.complete,"Image "+d+" could not be decoded");var u=document.createElement("canvas");u.width=p.width;u.height=p.height;u.getContext("2d").drawImage(p,0,0);e.preloadedImages[d]=u;yc.revokeObjectURL(r);f&&f(c)};p.onerror=function(){console.log("Image "+r+" could not be decoded");h&&h()};p.src=r}});e.preloadPlugins.push({canHandle:function(c){return!e.mc&&
c.substr(-4)in{".ogg":1,".wav":1,".mp3":1}},handle:function(c,d,f,h){function k(q){p||(p=!0,e.preloadedAudios[d]=q,f&&f(c))}function r(){p||(p=!0,e.preloadedAudios[d]=new Audio,h&&h())}var p=!1;if(wc){try{var u=new Blob([c],{type:zc(d)})}catch(q){return r()}u=yc.createObjectURL(u);var n=new Audio;n.addEventListener("canplaythrough",function(){k(n)},!1);n.onerror=function(){if(!p){console.log("warning: browser could not fully decode audio "+d+", trying slower base64 approach");for(var q="",v=0,g=0,
t=0;t<c.length;t++)for(v=v<<8|c[t],g+=8;6<=g;){var w=v>>g-6&63;g-=6;q+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[w]}2==g?(q+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(v&3)<<4],q+="=="):4==g&&(q+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(v&15)<<2],q+="=");n.src="data:audio/x-"+d.substr(-3)+";base64,"+q;k(n)}};n.src=u;Ac(function(){k(n)})}else return r()}});var b=e.canvas;b&&(b.requestPointerLock=b.requestPointerLock||b.mozRequestPointerLock||
b.webkitRequestPointerLock||b.msRequestPointerLock||function(){},b.exitPointerLock=document.exitPointerLock||document.mozExitPointerLock||document.webkitExitPointerLock||document.msExitPointerLock||function(){},b.exitPointerLock=b.exitPointerLock.bind(document),document.addEventListener("pointerlockchange",a,!1),document.addEventListener("mozpointerlockchange",a,!1),document.addEventListener("webkitpointerlockchange",a,!1),document.addEventListener("mspointerlockchange",a,!1),e.elementPointerLock&&
b.addEventListener("click",function(c){!tc&&e.canvas.requestPointerLock&&(e.canvas.requestPointerLock(),c.preventDefault())},!1))}}
function Bc(a,b,c,d){if(b&&e.ua&&a==e.canvas)return e.ua;var f;if(b){var h={antialias:!1,alpha:!1,Db:2};if(d)for(var k in d)h[k]=d[k];if("undefined"!==typeof Cc&&(f=Dc(a,h)))var r=Ec[f].Ea}else r=a.getContext("2d");if(!r)return null;c&&(b||assert("undefined"===typeof V,"cannot set in module if GLctx is used, but we are a non-GL context that would replace it"),e.ua=r,b&&(Fc=Ec[f],e.ua=V=Fc&&Fc.Ea),e.pc=b,uc.forEach(function(p){p()}),$b());return r}var Gc=!1,Hc=void 0,Ic=void 0;
function Jc(a,b){function c(){sc=!1;var h=d.parentNode;(document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===h?(d.exitFullscreen=Kc,Hc&&d.requestPointerLock(),sc=!0,Ic?("undefined"!=typeof SDL&&(C[SDL.screen>>2]=Ia[SDL.screen>>2]|8388608),Lc(e.canvas),Mc()):Lc(d)):(h.parentNode.insertBefore(d,h),h.parentNode.removeChild(h),Ic?("undefined"!=typeof SDL&&(C[SDL.screen>>2]=Ia[SDL.screen>>2]&
-8388609),Lc(e.canvas),Mc()):Lc(d));if(e.onFullScreen)e.onFullScreen(sc);if(e.onFullscreen)e.onFullscreen(sc)}Hc=a;Ic=b;"undefined"===typeof Hc&&(Hc=!0);"undefined"===typeof Ic&&(Ic=!1);var d=e.canvas;Gc||(Gc=!0,document.addEventListener("fullscreenchange",c,!1),document.addEventListener("mozfullscreenchange",c,!1),document.addEventListener("webkitfullscreenchange",c,!1),document.addEventListener("MSFullscreenChange",c,!1));var f=document.createElement("div");d.parentNode.insertBefore(f,d);f.appendChild(d);
f.requestFullscreen=f.requestFullscreen||f.mozRequestFullScreen||f.msRequestFullscreen||(f.webkitRequestFullscreen?function(){f.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT)}:null)||(f.webkitRequestFullScreen?function(){f.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT)}:null);f.requestFullscreen()}
function Kc(){if(!sc)return!1;(document.exitFullscreen||document.cancelFullScreen||document.mozCancelFullScreen||document.msExitFullscreen||document.webkitCancelFullScreen||function(){}).apply(document,[]);return!0}var Nc=0;function Oc(a){if("function"===typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===Nc)Nc=b+1E3/60;else for(;b+2>=Nc;)Nc+=1E3/60;setTimeout(a,Math.max(Nc-b,0))}}function Ac(a){setTimeout(function(){ec(a)},1E4)}
function zc(a){return{jpg:"image/jpeg",jpeg:"image/jpeg",png:"image/png",bmp:"image/bmp",ogg:"audio/ogg",wav:"audio/wav",mp3:"audio/mpeg"}[a.substr(a.lastIndexOf(".")+1)]}var Pc=0,Qc=0,Rc=0,Sc=0;
function Tc(a){if(tc)"mousemove"!=a.type&&"mozMovementX"in a?Rc=Sc=0:(Rc=a.movementX||a.mozMovementX||a.webkitMovementX||0,Sc=a.movementY||a.mozMovementY||a.webkitMovementY||0),"undefined"!=typeof SDL?(Pc=SDL.jc+Rc,Qc=SDL.kc+Sc):(Pc+=Rc,Qc+=Sc);else{var b=e.canvas.getBoundingClientRect(),c=e.canvas.width,d=e.canvas.height,f="undefined"!==typeof window.scrollX?window.scrollX:window.pageXOffset,h="undefined"!==typeof window.scrollY?window.scrollY:window.pageYOffset;"touchstart"!==a.type&&"touchend"!==
a.type&&"touchmove"!==a.type&&(f=a.pageX-(f+b.left),a=a.pageY-(h+b.top),f*=c/b.width,a*=d/b.height,Rc=f-Pc,Sc=a-Qc,Pc=f,Qc=a)}}function ac(a,b,c){var d="al "+a;ja(a,function(f){assert(f,'Loading data file "'+a+'" failed (no arrayBuffer).');b(new Uint8Array(f));d&&Ra(d)},function(){if(c)c();else throw'Loading data file "'+a+'" failed.';});d&&Qa(d)}var Uc=[];function Mc(){var a=e.canvas;Uc.forEach(function(b){b(a.width,a.height)})}function Vc(a,b,c){Lc(e.canvas,a,b);c||Mc()}
function Lc(a,b,c){b&&c?(a.Sb=b,a.xb=c):(b=a.Sb,c=a.xb);var d=b,f=c;e.forcedAspectRatio&&0<e.forcedAspectRatio&&(d/f<e.forcedAspectRatio?d=Math.round(f*e.forcedAspectRatio):f=Math.round(d/e.forcedAspectRatio));if((document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===a.parentNode&&"undefined"!=typeof screen){var h=Math.min(screen.width/d,screen.height/f);d=Math.round(d*h);f=Math.round(f*
h)}Ic?(a.width!=d&&(a.width=d),a.height!=f&&(a.height=f),"undefined"!=typeof a.style&&(a.style.removeProperty("width"),a.style.removeProperty("height"))):(a.width!=b&&(a.width=b),a.height!=c&&(a.height=c),"undefined"!=typeof a.style&&(d!=b||f!=c?(a.style.setProperty("width",d+"px","important"),a.style.setProperty("height",f+"px","important")):(a.style.removeProperty("width"),a.style.removeProperty("height"))))}var vc,wc,xc,yc;
function Wc(a,b){kc=a;lc=b;if(ic)if(fc||(fc=!0),0==a)U=function(){var d=Math.max(0,qc+b-S())|0;setTimeout(rc,d)};else if(1==a)U=function(){Oc(rc)};else if(2==a){if("undefined"===typeof setImmediate){var c=[];addEventListener("message",function(d){if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);setImmediate=function(d){c.push(d);x?(void 0===e.setImmediates&&(e.setImmediates=[]),e.setImmediates.push(d),postMessage({target:"setimmediate"})):postMessage("setimmediate",
"*")}}U=function(){setImmediate(rc)}}}
function Xc(a,b,c,d,f){function h(){if(k<hc){if(!noExitRuntime)try{Yc(za)}catch(r){if(!(r instanceof na))throw r;}return!1}return!0}assert(!ic,"emscripten_set_main_loop: there can only be one main loop function at once: call emscripten_cancel_main_loop to cancel the previous one before setting a new one with different parameters.");ic=a;jc=d;var k=hc;fc=!1;rc=function(){if(!ya)if(0<nc.length){var r=Date.now(),p=nc.shift();p.vb(p.xa);if(pc){var u=pc,n=0==u%1?u-1:Math.floor(u);pc=p.Xb?n:(8*u+(n+.5))/
9}console.log('main loop blocker "'+p.name+'" took '+(Date.now()-r)+" ms");e.setStatus&&(r=e.statusMessage||"Please wait...",p=pc,u=oc.bc,p?p<u?e.setStatus(r+" ("+(u-p)+"/"+u+")"):e.setStatus(r):e.setStatus(""));h()&&setTimeout(rc,0)}else h()&&(mc=mc+1|0,1==kc&&1<lc&&0!=mc%lc?U():(0==kc&&(qc=S()),ya||e.preMainLoop&&!1===e.preMainLoop()||(ec(a),e.postMainLoop&&e.postMainLoop()),h()&&("object"===typeof SDL&&SDL.audio&&SDL.audio.Fb&&SDL.audio.Fb(),U())))};f||(b&&0<b?Wc(0,1E3/b):Wc(1,1),U());if(c)throw"unwind";
}var Zc={};function $c(){if(!ad){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"===typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:ba||"./this.program"},b;for(b in Zc)a[b]=Zc[b];var c=[];for(b in a)c.push(b+"="+a[b]);ad=c}return ad}var ad,bd=1,cd=[],dd=[],ed=[],fd=[],gd=[],Ec=[],hd={};function id(a){for(var b=bd++,c=a.length;c<b;c++)a[c]=null;return b}
function Dc(a,b){a.Xa||(a.Xa=a.getContext,a.getContext=function(d,f){f=a.Xa(d,f);return"webgl"==d==f instanceof WebGLRenderingContext?f:null});var c=a.getContext("webgl2",b);return c?jd(c,b):0}function jd(a,b){var c=id(Ec),d={ec:c,attributes:b,version:b.Db,Ea:a};a.canvas&&(a.canvas.Tb=d);Ec[c]=d;("undefined"===typeof b.tb||b.tb)&&kd(d);return c}
function kd(a){a||(a=Fc);if(!a.zb){a.zb=!0;var b=a.Ea;b.$b=b.getExtension("WEBGL_draw_instanced_base_vertex_base_instance");b.ic=b.getExtension("WEBGL_multi_draw_instanced_base_vertex_base_instance");b.ac=b.getExtension("EXT_disjoint_timer_query");b.lc=b.getExtension("WEBGL_multi_draw");(b.getSupportedExtensions()||[]).forEach(function(c){0>c.indexOf("lose_context")&&0>c.indexOf("debug")&&b.getExtension(c)})}}var Cc={},ld,Fc;
function md(a,b,c,d){for(var f=0;f<a;f++){var h=V[c](),k=h&&id(d);h?(h.name=k,d[k]=h):ld||(ld=1282);C[b+4*f>>2]=k}}function nd(a,b,c,d){this.id=a;this.y=this.x=0;this.Ka=!1;this.nb=this.mb=0;this.width=b;this.height=c;this.lb=b;this.kb=c;this.title=d;this.attributes=W;this.buttons=0;this.keys=[];this.Fa=[];this.Ra=this.$a=this.Ga=this.jb=this.ya=this.Ta=this.fb=this.Wa=this.Da=this.title=null}
var X=null,Y=null,W=null,od={131073:0,131074:0,131075:1,131076:1,131077:1,135169:8,135170:8,135171:8,135172:8,135173:24,135174:8,135175:0,135176:0,135177:0,135178:0,135179:0,135180:0,135181:0,135182:0,135183:0,139265:196609,139266:1,139267:0,139268:0,139269:0,139270:0,139271:0,139272:0};
function pd(a){switch(a){case 32:return 32;case 222:return 39;case 188:return 44;case 173:return 45;case 189:return 45;case 190:return 46;case 191:return 47;case 48:return 48;case 49:return 49;case 50:return 50;case 51:return 51;case 52:return 52;case 53:return 53;case 54:return 54;case 55:return 55;case 56:return 56;case 57:return 57;case 59:return 59;case 61:return 61;case 187:return 61;case 65:return 65;case 66:return 66;case 67:return 67;case 68:return 68;case 69:return 69;case 70:return 70;case 71:return 71;
case 72:return 72;case 73:return 73;case 74:return 74;case 75:return 75;case 76:return 76;case 77:return 77;case 78:return 78;case 79:return 79;case 80:return 80;case 81:return 81;case 82:return 82;case 83:return 83;case 84:return 84;case 85:return 85;case 86:return 86;case 87:return 87;case 88:return 88;case 89:return 89;case 90:return 90;case 219:return 91;case 220:return 92;case 221:return 93;case 192:return 94;case 27:return 256;case 13:return 257;case 9:return 258;case 8:return 259;case 45:return 260;
case 46:return 261;case 39:return 262;case 37:return 263;case 40:return 264;case 38:return 265;case 33:return 266;case 34:return 267;case 36:return 268;case 35:return 269;case 20:return 280;case 145:return 281;case 144:return 282;case 44:return 283;case 19:return 284;case 112:return 290;case 113:return 291;case 114:return 292;case 115:return 293;case 116:return 294;case 117:return 295;case 118:return 296;case 119:return 297;case 120:return 298;case 121:return 299;case 122:return 300;case 123:return 301;
case 124:return 302;case 125:return 303;case 126:return 304;case 127:return 305;case 128:return 306;case 129:return 307;case 130:return 308;case 131:return 309;case 132:return 310;case 133:return 311;case 134:return 312;case 135:return 313;case 136:return 314;case 96:return 320;case 97:return 321;case 98:return 322;case 99:return 323;case 100:return 324;case 101:return 325;case 102:return 326;case 103:return 327;case 104:return 328;case 105:return 329;case 110:return 330;case 111:return 331;case 106:return 332;
case 109:return 333;case 107:return 334;case 16:return 340;case 17:return 341;case 18:return 342;case 91:return 343;case 93:return 348;default:return-1}}function qd(){var a=X,b=0;a.keys[340]&&(b|=1);a.keys[341]&&(b|=2);a.keys[342]&&(b|=4);a.keys[343]&&(b|=8);return b}function rd(a){X&&X.Ra&&!a.ctrlKey&&!a.metaKey&&(a=a.charCode,0==a||0<=a&&31>=a||G.get(X.Ra)(X.id,a))}
function sd(a,b){if(X){var c=pd(a);if(-1!=c){var d=b&&X.keys[c];X.keys[c]=b;X.Fa[a]=b;X.$a&&(d&&(b=2),G.get(X.$a)(X.id,c,a,b,qd()))}}}function td(){ud()}function vd(){ud()}function wd(a){sd(a.keyCode,1);8!==a.keyCode&&9!==a.keyCode||a.preventDefault()}function xd(a){sd(a.keyCode,0)}function yd(){if(X)for(var a=0;a<X.Fa.length;++a)X.Fa[a]&&sd(a,0)}function zd(a){X&&(Tc(a),a.target==e.canvas&&X.Ta&&G.get(X.Ta)(X.id,Pc,Qc))}function Ad(a){X&&a.target==e.canvas&&X.ya&&G.get(X.ya)(X.id,1)}
function Bd(a){X&&a.target==e.canvas&&X.ya&&G.get(X.ya)(X.id,0)}function Cd(a,b){if(X&&(Tc(a),a.target==e.canvas)){var c=a.button;0<c&&(c=1==c?2:1);if(1==b){X.buttons|=1<<c;try{a.target.setCapture()}catch(d){}}else X.buttons&=~(1<<c);X.fb&&G.get(X.fb)(X.id,c,b,qd())}}function Dd(a){X&&Cd(a,1)}function Ed(a){X&&Cd(a,0)}
function Fd(a){switch(a.type){case "DOMMouseScroll":break;case "mousewheel":break;case "wheel":switch(a.deltaMode){case 0:break;case 1:break;case 2:break;default:throw"unrecognized mouse wheel delta mode: "+a.deltaMode;}break;default:throw"unrecognized mouse wheel event: "+a.type;}if(X&&X.jb&&a.target==e.canvas){if("mousewheel"==a.type){var b=a.wheelDeltaX;var c=a.wheelDeltaY}else b=a.deltaX,c=a.deltaY;G.get(X.jb)(X.id,b,c);a.preventDefault()}}var Z={},Gd=null,Hd=null;
function ud(){if(mc!==Hd||!mc){Gd=navigator.getGamepads?navigator.getGamepads():navigator.webkitGetGamepads?navigator.webkitGetGamepads:null;Hd=mc;for(var a=0;a<Gd.length;++a){var b=Gd[a];if(b){Z[a]||(console.log("glfw joystick connected:",a),Z[a]={id:Aa(jb(b.id)),Wb:b.buttons.length,Vb:b.axes.length,buttons:Aa(Array(b.buttons.length)),axes:Aa(Array(4*b.axes.length))});for(var c=Z[a],d=0;d<b.buttons.length;++d)sa(c.buttons+d,b.buttons[d].pressed,"i8");for(d=0;d<b.axes.length;++d)sa(c.axes+4*d,b.axes[d],
"float")}else Z[a]&&(console.log("glfw joystick disconnected",a),Jd(Z[a].id),Jd(Z[a].buttons),Jd(Z[a].axes),delete Z[a])}}}
function Kd(a){function b(r){var p="/.glfw_dropped_files/"+r.name.replace(/\//g,"_"),u=new FileReader;u.onloadend=function(q){if(2!=u.readyState)++h,console.log("failed to read dropped file: "+r.name+": "+u.error);else{var v=new Uint8Array(q.target.result);var g=g||{};g.flags=g.flags||577;q=Mb(p,g.flags,g.mode);if("string"===typeof v){var t=new Uint8Array(Ga(v)+1);v=Fa(v,t,t.length);Qb(q,t,0,v,void 0,g.sb)}else if(ArrayBuffer.isView(v))Qb(q,v,0,v.byteLength,void 0,g.sb);else throw Error("Unsupported data type");
Ob(q);if(++h===f){G.get(X.Ga)(X.id,f,c);for(g=0;g<d.length;++g)Jd(d[g]);Jd(c)}}};u.readAsArrayBuffer(r);var n=Aa(jb(p));d.push(n);sa(c+4*k,n,"i8*")}if(X&&X.Ga&&a.dataTransfer&&a.dataTransfer.files&&0!=a.dataTransfer.files.length){a.preventDefault();var c=Aa(Array(4*a.dataTransfer.files.length)),d=[],f=a.dataTransfer.files.length,h=0;Ub("/",".glfw_dropped_files");for(var k=0;k<f;++k)b(a.dataTransfer.files[k]);return!1}}function Ld(a){if(X&&X.Ga)return a.preventDefault(),!1}
function Md(a){return 0===a%4&&(0!==a%100||0===a%400)}function Nd(a,b){for(var c=0,d=0;d<=b;c+=a[d++]);return c}var Od=[31,29,31,30,31,30,31,31,30,31,30,31],Pd=[31,28,31,30,31,30,31,31,30,31,30,31];function Qd(a,b){for(a=new Date(a.getTime());0<b;){var c=a.getMonth(),d=(Md(a.getFullYear())?Od:Pd)[c];if(b>d-a.getDate())b-=d-a.getDate()+1,a.setDate(1),11>c?a.setMonth(c+1):(a.setMonth(0),a.setFullYear(a.getFullYear()+1));else{a.setDate(a.getDate()+b);break}}return a}
function Rd(a,b,c,d){function f(g,t,w){for(g="number"===typeof g?g.toString():g||"";g.length<t;)g=w[0]+g;return g}function h(g,t){return f(g,t,"0")}function k(g,t){function w(T){return 0>T?-1:0<T?1:0}var A;0===(A=w(g.getFullYear()-t.getFullYear()))&&0===(A=w(g.getMonth()-t.getMonth()))&&(A=w(g.getDate()-t.getDate()));return A}function r(g){switch(g.getDay()){case 0:return new Date(g.getFullYear()-1,11,29);case 1:return g;case 2:return new Date(g.getFullYear(),0,3);case 3:return new Date(g.getFullYear(),
0,2);case 4:return new Date(g.getFullYear(),0,1);case 5:return new Date(g.getFullYear()-1,11,31);case 6:return new Date(g.getFullYear()-1,11,30)}}function p(g){g=Qd(new Date(g.ha+1900,0,1),g.Ca);var t=new Date(g.getFullYear()+1,0,4),w=r(new Date(g.getFullYear(),0,4));t=r(t);return 0>=k(w,g)?0>=k(t,g)?g.getFullYear()+1:g.getFullYear():g.getFullYear()-1}var u=C[d+40>>2];d={Pb:C[d>>2],Ob:C[d+4>>2],Aa:C[d+8>>2],wa:C[d+12>>2],ta:C[d+16>>2],ha:C[d+20>>2],Ba:C[d+24>>2],Ca:C[d+28>>2],oc:C[d+32>>2],Nb:C[d+
36>>2],Qb:u?Ea(u):""};c=Ea(c);u={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S","%Ec":"%c","%EC":"%C","%Ex":"%m/%d/%y","%EX":"%H:%M:%S","%Ey":"%y","%EY":"%Y","%Od":"%d","%Oe":"%e","%OH":"%H","%OI":"%I","%Om":"%m","%OM":"%M","%OS":"%S","%Ou":"%u","%OU":"%U","%OV":"%V","%Ow":"%w","%OW":"%W","%Oy":"%y"};for(var n in u)c=c.replace(new RegExp(n,"g"),u[n]);var q="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),
v="January February March April May June July August September October November December".split(" ");u={"%a":function(g){return q[g.Ba].substring(0,3)},"%A":function(g){return q[g.Ba]},"%b":function(g){return v[g.ta].substring(0,3)},"%B":function(g){return v[g.ta]},"%C":function(g){return h((g.ha+1900)/100|0,2)},"%d":function(g){return h(g.wa,2)},"%e":function(g){return f(g.wa,2," ")},"%g":function(g){return p(g).toString().substring(2)},"%G":function(g){return p(g)},"%H":function(g){return h(g.Aa,
2)},"%I":function(g){g=g.Aa;0==g?g=12:12<g&&(g-=12);return h(g,2)},"%j":function(g){return h(g.wa+Nd(Md(g.ha+1900)?Od:Pd,g.ta-1),3)},"%m":function(g){return h(g.ta+1,2)},"%M":function(g){return h(g.Ob,2)},"%n":function(){return"\n"},"%p":function(g){return 0<=g.Aa&&12>g.Aa?"AM":"PM"},"%S":function(g){return h(g.Pb,2)},"%t":function(){return"\t"},"%u":function(g){return g.Ba||7},"%U":function(g){var t=new Date(g.ha+1900,0,1),w=0===t.getDay()?t:Qd(t,7-t.getDay());g=new Date(g.ha+1900,g.ta,g.wa);return 0>
k(w,g)?h(Math.ceil((31-w.getDate()+(Nd(Md(g.getFullYear())?Od:Pd,g.getMonth()-1)-31)+g.getDate())/7),2):0===k(w,t)?"01":"00"},"%V":function(g){var t=new Date(g.ha+1901,0,4),w=r(new Date(g.ha+1900,0,4));t=r(t);var A=Qd(new Date(g.ha+1900,0,1),g.Ca);return 0>k(A,w)?"53":0>=k(t,A)?"01":h(Math.ceil((w.getFullYear()<g.ha+1900?g.Ca+32-w.getDate():g.Ca+1-w.getDate())/7),2)},"%w":function(g){return g.Ba},"%W":function(g){var t=new Date(g.ha,0,1),w=1===t.getDay()?t:Qd(t,0===t.getDay()?1:7-t.getDay()+1);g=
new Date(g.ha+1900,g.ta,g.wa);return 0>k(w,g)?h(Math.ceil((31-w.getDate()+(Nd(Md(g.getFullYear())?Od:Pd,g.getMonth()-1)-31)+g.getDate())/7),2):0===k(w,t)?"01":"00"},"%y":function(g){return(g.ha+1900).toString().substring(2)},"%Y":function(g){return g.ha+1900},"%z":function(g){g=g.Nb;var t=0<=g;g=Math.abs(g)/60;return(t?"+":"-")+String("0000"+(g/60*100+g%60)).slice(-4)},"%Z":function(g){return g.Qb},"%%":function(){return"%"}};for(n in u)0<=c.indexOf(n)&&(c=c.replace(new RegExp(n,"g"),u[n](d)));n=
jb(c,!1);if(n.length>b)return 0;B.set(n,a);return n.length-1}var Sd=[];function zb(a,b,c,d){a||(a=this);this.parent=a;this.ma=a.ma;this.va=null;this.id=tb++;this.name=b;this.mode=c;this.ea={};this.fa={};this.rdev=d}
Object.defineProperties(zb.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}},Cb:{get:function(){return 16384===(this.mode&61440)}},Bb:{get:function(){return 8192===(this.mode&61440)}}});Rb();M=Array(4096);Gb(L,"/");P("/tmp");P("/home");P("/home/web_user");
(function(){P("/dev");hb(259,{read:function(){return 0},write:function(b,c,d,f){return f}});Ib("/dev/null",259);gb(1280,kb);gb(1536,lb);Ib("/dev/tty",1280);Ib("/dev/tty1",1536);var a=db();Q("/dev","random",a);Q("/dev","urandom",a);P("/dev/shm");P("/dev/shm/tmp")})();
(function(){P("/proc");var a=P("/proc/self");P("/proc/self/fd");Gb({ma:function(){var b=nb(a,"fd",16895,73);b.ea={lookup:function(c,d){var f=sb[+d];if(!f)throw new K(8);c={parent:null,ma:{eb:"fake"},ea:{readlink:function(){return f.path}}};return c.parent=c}};return b}},"/proc/self/fd")})();e.FS_createPath=Ub;e.FS_createDataFile=Wb;e.FS_createPreloadedFile=Zb;e.FS_createLazyFile=Yb;e.FS_createDevice=Q;e.FS_unlink=Kb;e.requestFullscreen=function(a,b){Jc(a,b)};e.requestAnimationFrame=function(a){Oc(a)};
e.setCanvasSize=function(a,b,c){Vc(a,b,c)};e.pauseMainLoop=function(){U=null;hc++};e.resumeMainLoop=function(){hc++;var a=kc,b=lc,c=ic;ic=null;Xc(c,0,!1,jc,!0);Wc(a,b);U()};e.getUserMedia=function(){window.getUserMedia||(window.getUserMedia=navigator.getUserMedia||navigator.mozGetUserMedia);window.getUserMedia(void 0)};e.createContext=function(a,b,c,d){return Bc(a,b,c,d)};var V;function jb(a,b){var c=Array(Ga(a)+1);a=Fa(a,c,c.length);b&&(c.length=a);return c}
var Td={v:function(a){return Ba(a+16)+16},r:function(a,b,c){(new Za(a)).yb(b,c);$a++;throw a;},E:function(a,b,c){bc=c;try{var d=dc(a);switch(b){case 21509:case 21505:return d.tty?0:-59;case 21510:case 21511:case 21512:case 21506:case 21507:case 21508:return d.tty?0:-59;case 21519:if(!d.tty)return-59;var f=cc();return C[f>>2]=0;case 21520:return d.tty?-28:-59;case 21531:a=f=cc();if(!d.fa.Ab)throw new K(59);return d.fa.Ab(d,b,a);case 21523:return d.tty?0:-59;case 21524:return d.tty?0:-59;default:z("bad ioctl syscall "+
b)}}catch(h){return"undefined"!==typeof R&&h instanceof K||z(h),-h.la}},F:function(a,b,c){bc=c;try{var d=Ea(a),f=c?cc():0;return Mb(d,b,f).fd}catch(h){return"undefined"!==typeof R&&h instanceof K||z(h),-h.la}},k:function(){z()},d:function(a,b,c){Sd.length=0;var d;for(c>>=2;d=F[b++];)(d=105>d)&&c&1&&c++,Sd.push(d?wa[c++>>1]:C[c]),++c;return Xa[a].apply(null,Sd)},O:S,y:function(a,b,c){F.copyWithin(a,b,b+c)},c:function(){z("OOM")},N:function(a,b,c,d){Xc(function(){G.get(a)(b)},c,d,b)},A:function(a,b){try{var c=
0;$c().forEach(function(d,f){var h=b+c;f=C[a+4*f>>2]=h;for(h=0;h<d.length;++h)B[f++>>0]=d.charCodeAt(h);B[f>>0]=0;c+=d.length+1});return 0}catch(d){return"undefined"!==typeof R&&d instanceof K||z(d),d.la}},B:function(a,b){try{var c=$c();C[a>>2]=c.length;var d=0;c.forEach(function(f){d+=f.length+1});C[b>>2]=d;return 0}catch(f){return"undefined"!==typeof R&&f instanceof K||z(f),f.la}},l:function(a){try{var b=dc(a);Ob(b);return 0}catch(c){return"undefined"!==typeof R&&c instanceof K||z(c),c.la}},D:function(a,
b,c,d){try{a:{for(var f=dc(a),h=a=0;h<c;h++){var k=C[b+(8*h+4)>>2],r=f,p=C[b+8*h>>2],u=k,n=void 0,q=B;if(0>u||0>n)throw new K(28);if(null===r.fd)throw new K(8);if(1===(r.flags&2097155))throw new K(8);if(16384===(r.node.mode&61440))throw new K(31);if(!r.fa.read)throw new K(28);var v="undefined"!==typeof n;if(!v)n=r.position;else if(!r.seekable)throw new K(70);var g=r.fa.read(r,q,p,u,n);v||(r.position+=g);var t=g;if(0>t){var w=-1;break a}a+=t;if(t<k)break}w=a}C[d>>2]=w;return 0}catch(A){return"undefined"!==
typeof R&&A instanceof K||z(A),A.la}},x:function(a,b,c,d,f){try{var h=dc(a);a=4294967296*c+(b>>>0);if(-9007199254740992>=a||9007199254740992<=a)return-61;Pb(h,a,d);ua=[h.position>>>0,(D=h.position,1<=+Math.abs(D)?0<D?(Math.min(+Math.floor(D/4294967296),4294967295)|0)>>>0:~~+Math.ceil((D-+(~~D>>>0))/4294967296)>>>0:0)];C[f>>2]=ua[0];C[f+4>>2]=ua[1];h.La&&0===a&&0===d&&(h.La=null);return 0}catch(k){return"undefined"!==typeof R&&k instanceof K||z(k),k.la}},C:function(a,b,c,d){try{a:{for(var f=dc(a),
h=a=0;h<c;h++){var k=Qb(f,B,C[b+8*h>>2],C[b+(8*h+4)>>2],void 0);if(0>k){var r=-1;break a}a+=k}r=a}C[d>>2]=r;return 0}catch(p){return"undefined"!==typeof R&&p instanceof K||z(p),p.la}},n:function(a,b){V.attachShader(dd[a],fd[b])},a:function(a,b){35051==a?V.Yb=b:35052==a&&(V.Zb=b);V.bindBuffer(a,cd[b])},i:function(a){V.bindVertexArray(gd[a])},Q:function(a,b){V.blendFunc(a,b)},P:function(a,b,c,d){V.blendFuncSeparate(a,b,c,d)},b:function(a,b,c,d){c?V.bufferData(a,F,d,c,b):V.bufferData(a,b,d)},j:function(a,
b,c,d){V.bufferSubData(a,b,F,d,c)},U:function(a){V.clear(a)},V:function(a,b,c,d){V.clearColor(a,b,c,d)},o:function(a){V.compileShader(fd[a])},L:function(){var a=id(dd),b=V.createProgram();b.name=a;dd[a]=b;return a},q:function(a){var b=id(fd);fd[b]=V.createShader(a);return b},w:function(a,b,c,d){V.drawArraysInstanced(a,b,c,d)},R:function(a){V.enable(a)},f:function(a){V.enableVertexAttribArray(a)},g:function(a,b){md(a,b,"createBuffer",cd)},G:function(a,b){md(a,b,"createVertexArray",gd)},t:function(a,
b){b=Ea(b);var c=0;if("]"==b[b.length-1]){var d=b.lastIndexOf("[");c="]"!=b[d+1]?parseInt(b.slice(d+1)):0;b=b.slice(0,d)}return(a=hd[a]&&hd[a].ob[b])&&0<=c&&c<a[0]?a[1]+c:-1},K:function(a){V.linkProgram(dd[a]);var b=dd[a];a=hd[a]={ob:{},bb:0,fc:-1,hc:-1};for(var c=a.ob,d=V.getProgramParameter(b,35718),f=0;f<d;++f){var h=V.getActiveUniform(b,f),k=h.name;a.bb=Math.max(a.bb,k.length+1);"]"==k.slice(-1)&&(k=k.slice(0,k.lastIndexOf("[")));var r=V.getUniformLocation(b,k);if(r){var p=id(ed);c[k]=[h.size,
p];ed[p]=r;for(var u=1;u<h.size;++u)r=V.getUniformLocation(b,k+"["+u+"]"),p=id(ed),ed[p]=r}}},p:function(a,b,c,d){for(var f="",h=0;h<b;++h){var k=d?C[d+4*h>>2]:-1;f+=Ea(C[c+4*h>>2],0>k?void 0:k)}V.shaderSource(fd[a],f)},s:function(a,b){V.uniform1f(ed[a],b)},S:function(a){V.useProgram(dd[a])},h:function(a,b){V.vertexAttribDivisor(a,b)},e:function(a,b,c,d,f,h){V.vertexAttribPointer(a,b,c,!!d,f,h)},u:function(a,b,c,d){V.viewport(a,b,c,d)},I:function(a,b,c,d){var f;for(f=0;f<Y.length&&null!==Y[f];f++);
if(0<f)throw"glfwCreateWindow only supports one window at time currently";var h=f+1;if(0>=a||0>=b)h=0;else{d?Jc():Vc(a,b);for(f=0;f<Y.length&&null==Y[f];f++);d=0<W[139265];f==Y.length&&(d?e.ua=Bc(e.canvas,!0,!0,{antialias:1<W[135181],depth:0<W[135173],stencil:0<W[135174],alpha:0<W[135172]}):$b());!e.ua&&d?h=0:(a=new nd(h,a,b,c),h-1==Y.length?Y.push(a):Y[h-1]=a,X=a,h=a.id)}return h},J:function(){if(Y)return 1;S();W=od;Y=[];X=null;window.addEventListener("gamepadconnected",td,!0);window.addEventListener("gamepaddisconnected",
vd,!0);window.addEventListener("keydown",wd,!0);window.addEventListener("keypress",rd,!0);window.addEventListener("keyup",xd,!0);window.addEventListener("blur",yd,!0);e.canvas.addEventListener("touchmove",zd,!0);e.canvas.addEventListener("touchstart",Dd,!0);e.canvas.addEventListener("touchcancel",Ed,!0);e.canvas.addEventListener("touchend",Ed,!0);e.canvas.addEventListener("mousemove",zd,!0);e.canvas.addEventListener("mousedown",Dd,!0);e.canvas.addEventListener("mouseup",Ed,!0);e.canvas.addEventListener("wheel",
Fd,!0);e.canvas.addEventListener("mousewheel",Fd,!0);e.canvas.addEventListener("mouseenter",Ad,!0);e.canvas.addEventListener("mouseleave",Bd,!0);e.canvas.addEventListener("drop",Kd,!0);e.canvas.addEventListener("dragover",Ld,!0);Uc.push(function(a,b){if(X){var c=!0;document.fullscreen||document.fullScreen||document.mozFullScreen||document.webkitIsFullScreen?(X.mb=X.x,X.nb=X.y,X.lb=X.width,X.kb=X.height,X.x=X.y=0,X.width=screen.width,X.height=screen.height,X.Ka=!0):1==X.Ka?(X.x=X.mb,X.y=X.nb,X.width=
X.lb,X.height=X.kb,X.Ka=!1):X.width!=a||X.height!=b?(X.width=a,X.height=b):c=!1;c&&(Vc(X.width,X.height,!0),X&&X.Da&&G.get(X.Da)(X.id,X.width,X.height),X&&X.Wa&&G.get(X.Wa)(X.id,X.width,X.height))}});return 1},H:function(){},W:function(a,b,c){if(a=0>=a||!Y?null:Y[a-1])X.id==a.id&&(b==screen.width&&c==screen.height?Jc():(Kc(),Vc(b,c),a.width=b,a.height=c)),a.Da&&G.get(a.Da)(a.id,b,c)},T:function(){},M:function(){window.removeEventListener("gamepadconnected",td,!0);window.removeEventListener("gamepaddisconnected",
vd,!0);window.removeEventListener("keydown",wd,!0);window.removeEventListener("keypress",rd,!0);window.removeEventListener("keyup",xd,!0);window.removeEventListener("blur",yd,!0);e.canvas.removeEventListener("touchmove",zd,!0);e.canvas.removeEventListener("touchstart",Dd,!0);e.canvas.removeEventListener("touchcancel",Ed,!0);e.canvas.removeEventListener("touchend",Ed,!0);e.canvas.removeEventListener("mousemove",zd,!0);e.canvas.removeEventListener("mousedown",Dd,!0);e.canvas.removeEventListener("mouseup",
Ed,!0);e.canvas.removeEventListener("wheel",Fd,!0);e.canvas.removeEventListener("mousewheel",Fd,!0);e.canvas.removeEventListener("mouseenter",Ad,!0);e.canvas.removeEventListener("mouseleave",Bd,!0);e.canvas.removeEventListener("drop",Kd,!0);e.canvas.removeEventListener("dragover",Ld,!0);e.canvas.width=e.canvas.height=1;X=Y=null},m:function(a,b){W[a]=b},z:function(a,b,c,d){return Rd(a,b,c,d)}};
(function(){function a(f){e.asm=f.exports;xa=e.asm.X;Ha=f=xa.buffer;e.HEAP8=B=new Int8Array(f);e.HEAP16=ta=new Int16Array(f);e.HEAP32=C=new Int32Array(f);e.HEAPU8=F=new Uint8Array(f);e.HEAPU16=new Uint16Array(f);e.HEAPU32=Ia=new Uint32Array(f);e.HEAPF32=va=new Float32Array(f);e.HEAPF64=wa=new Float64Array(f);G=e.asm.ca;Ka.unshift(e.asm.Y);Ra("wasm-instantiate")}function b(f){a(f.instance)}function c(f){return Wa().then(function(h){return WebAssembly.instantiate(h,d)}).then(f,function(h){l("failed to asynchronously prepare wasm: "+
h);z(h)})}var d={a:Td};Qa("wasm-instantiate");if(e.instantiateWasm)try{return e.instantiateWasm(d,a)}catch(f){return l("Module.instantiateWasm callback failed with error: "+f),!1}(function(){return ra||"function"!==typeof WebAssembly.instantiateStreaming||Ta()||Sa("file://")||"function"!==typeof fetch?c(b):fetch(I,{credentials:"same-origin"}).then(function(f){return WebAssembly.instantiateStreaming(f,d).then(b,function(h){l("wasm streaming compile failed: "+h);l("falling back to ArrayBuffer instantiation");
return c(b)})})})();return{}})();e.___wasm_call_ctors=function(){return(e.___wasm_call_ctors=e.asm.Y).apply(null,arguments)};e._setValues=function(){return(e._setValues=e.asm.Z).apply(null,arguments)};e._main=function(){return(e._main=e.asm._).apply(null,arguments)};var Jd=e._free=function(){return(Jd=e._free=e.asm.$).apply(null,arguments)},Ba=e._malloc=function(){return(Ba=e._malloc=e.asm.aa).apply(null,arguments)};e.stackAlloc=function(){return(e.stackAlloc=e.asm.ba).apply(null,arguments)};
e.addRunDependency=Qa;e.removeRunDependency=Ra;e.FS_createPath=Ub;e.FS_createDataFile=Wb;e.FS_createPreloadedFile=Zb;e.FS_createLazyFile=Yb;e.FS_createDevice=Q;e.FS_unlink=Kb;var Ud;function na(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}Pa=function Vd(){Ud||Wd();Ud||(Pa=Vd)};
function Wd(){function a(){if(!Ud&&(Ud=!0,e.calledRun=!0,!ya)){e.noFSInit||Sb||(Sb=!0,Rb(),e.stdin=e.stdin,e.stdout=e.stdout,e.stderr=e.stderr,e.stdin?Q("/dev","stdin",e.stdin):Jb("/dev/tty","/dev/stdin"),e.stdout?Q("/dev","stdout",null,e.stdout):Jb("/dev/tty","/dev/stdout"),e.stderr?Q("/dev","stderr",null,e.stderr):Jb("/dev/tty1","/dev/stderr"),Mb("/dev/stdin",0),Mb("/dev/stdout",1),Mb("/dev/stderr",1));Ya(Ka);ub=!1;Ya(La);if(e.onRuntimeInitialized)e.onRuntimeInitialized();if(Xd){var b=e._main;try{var c=
b(0,0);Yc(c,!0)}catch(d){d instanceof na||"unwind"==d||((b=d)&&"object"===typeof d&&d.stack&&(b=[d,d.stack]),l("exception thrown: "+b),ca(1,d))}finally{}}if(e.postRun)for("function"==typeof e.postRun&&(e.postRun=[e.postRun]);e.postRun.length;)b=e.postRun.shift(),Ma.unshift(b);Ya(Ma)}}if(!(0<H)){if(e.preRun)for("function"==typeof e.preRun&&(e.preRun=[e.preRun]);e.preRun.length;)Na();Ya(Ja);0<H||(e.setStatus?(e.setStatus("Running..."),setTimeout(function(){setTimeout(function(){e.setStatus("")},1);
a()},1)):a())}}e.run=Wd;function Yc(a,b){za=a;if(!b||!noExitRuntime||0!==a){if(!noExitRuntime){if(e.onExit)e.onExit(a);ya=!0}ca(a,new na(a))}}if(e.preInit)for("function"==typeof e.preInit&&(e.preInit=[e.preInit]);0<e.preInit.length;)e.preInit.pop()();var Xd=!0;e.noInitialRun&&(Xd=!1);Wd();
