
var e;e||(e=typeof Module !== 'undefined' ? Module : {});e.Tb||(e.Tb=0);e.Tb++;
(function(a){function b(l,t,p){var r=new XMLHttpRequest;r.open("GET",l,!0);r.responseType="arraybuffer";r.onprogress=function(w){var h=t;w.total&&(h=w.total);if(w.loaded){r.eb?e.vb[l].loaded=w.loaded:(r.eb=!0,e.vb||(e.vb={}),e.vb[l]={loaded:w.loaded,total:h});var n=h=w=0,y;for(y in e.vb){var B=e.vb[y];w+=B.total;h+=B.loaded;n++}w=Math.ceil(w*e.Tb/n);e.setStatus&&e.setStatus("Downloading data... ("+h+"/"+w+")")}else!e.vb&&e.setStatus&&e.setStatus("Downloading data...")};r.onerror=function(){throw Error("NetworkError for: "+
l);};r.onload=function(){if(200==r.status||304==r.status||206==r.status||0==r.status&&r.response)p(r.response);else throw Error(r.statusText+" : "+r.responseURL);};r.send(null)}function c(l){console.error("package error:",l)}function d(){function l(w,h,n){this.start=w;this.Pb=h;this.audio=n}function t(w){if(!w)throw"Loading data file failed."+Error().stack;if(!(w instanceof ArrayBuffer))throw"bad input to processPackageData"+Error().stack;w=new Uint8Array(w);l.prototype.Oc=w;w=a.files;for(var h=0;h<
w.length;++h)l.prototype.eb[w[h].filename].onload();e.removeRunDependency("datafile_index.data")}e.FS_createPath("/","src",!0,!0);e.FS_createPath("/src","shaders",!0,!0);l.prototype={eb:{},open:function(w,h){this.name=h;this.eb[h]=this;e.addRunDependency("fp "+this.name)},send:function(){},onload:function(){this.Mc(this.Oc.subarray(this.start,this.Pb))},Mc:function(w){e.FS_createDataFile(this.name,null,w,!0,!0,!0);e.removeRunDependency("fp "+this.name);this.eb[this.name]=null}};for(var p=a.files,
r=0;r<p.length;++r)(new l(p[r].start,p[r].end,p[r].audio)).open("GET",p[r].filename);e.addRunDependency("datafile_index.data");e.Ac||(e.Ac={});e.Ac["index.data"]={Rd:!1};m?(t(m),m=null):k=t}if("object"===typeof window)window.encodeURIComponent(window.location.pathname.toString().substring(0,window.location.pathname.toString().lastIndexOf("/"))+"/");else if("undefined"!==typeof location)encodeURIComponent(location.pathname.toString().substring(0,location.pathname.toString().lastIndexOf("/"))+"/");
else throw"using preloaded data can only be done on a web page or in a web worker";"function"!==typeof e.locateFilePackage||e.locateFile||(e.locateFile=e.locateFilePackage,q("warning: you defined Module.locateFilePackage, that has been renamed to Module.locateFile (using your locateFilePackage for now)"));var f=e.locateFile?e.locateFile("index.data",""):"index.data",g=a.remote_package_size,k=null,m=e.getPreloadedPackage?e.getPreloadedPackage(f,g):null;m||b(f,g,function(l){k?(k(l),k=null):m=l},c);
e.calledRun?d():(e.preRun||(e.preRun=[]),e.preRun.push(d))})({files:[{filename:"/src/shaders/tri.vert",start:0,end:416,audio:0},{filename:"/src/shaders/lines.frag",start:416,end:416,audio:0},{filename:"/src/shaders/tri.frag",start:416,end:1446,audio:0}],remote_package_size:1446,package_uuid:"6638d9f9-7d1e-4c84-877f-37c778892108"});var aa={},ba;for(ba in e)e.hasOwnProperty(ba)&&(aa[ba]=e[ba]);var ca="./this.program";function ea(a,b){throw b;}var fa=!1,u=!1,v=!1,ha=!1;fa="object"===typeof window;
u="function"===typeof importScripts;v="object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node;ha=!fa&&!v&&!u;var x=e.ENVIRONMENT_IS_PTHREAD||!1;x&&(ia=e.buffer);var _scriptDir="undefined"!==typeof document&&document.currentScript?document.currentScript.src:void 0;u?_scriptDir=self.location.href:v&&(_scriptDir=__filename);var z="";function ja(a){return e.locateFile?e.locateFile(a,z):z+a}var ka,la,ma,na,oa;
if(v){z=u?require("path").dirname(z)+"/":__dirname+"/";ka=function(a,b){na||(na=require("fs"));oa||(oa=require("path"));a=oa.normalize(a);return na.readFileSync(a,b?null:"utf8")};ma=function(a){a=ka(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a};1<process.argv.length&&(ca=process.argv[1].replace(/\\/g,"/"));process.argv.slice(2);"undefined"!==typeof module&&(module.exports=e);process.on("uncaughtException",function(a){if(!(a instanceof pa))throw a;});process.on("unhandledRejection",
A);ea=function(a){process.exit(a)};e.inspect=function(){return"[Emscripten Module object]"};var qa;try{qa=require("worker_threads")}catch(a){throw console.error('The "worker_threads" module is not supported in this node.js build - perhaps a newer version is needed?'),a;}global.Worker=qa.Worker}else if(ha)"undefined"!=typeof read&&(ka=function(a){return read(a)}),ma=function(a){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(a));a=read(a,"binary");assert("object"===typeof a);return a},
"function"===typeof quit&&(ea=function(a){quit(a)}),"undefined"!==typeof print&&("undefined"===typeof console&&(console={}),console.log=print,console.warn=console.error="undefined"!==typeof printErr?printErr:print);else if(fa||u)u?z=self.location.href:"undefined"!==typeof document&&document.currentScript&&(z=document.currentScript.src),z=0!==z.indexOf("blob:")?z.substr(0,z.lastIndexOf("/")+1):"",v?(ka=function(a,b){na||(na=require("fs"));oa||(oa=require("path"));a=oa.normalize(a);return na.readFileSync(a,
b?null:"utf8")},ma=function(a){a=ka(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a}):(ka=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},u&&(ma=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),la=function(a,b,c){var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=function(){200==d.status||0==d.status&&d.response?b(d.response):
c()};d.onerror=c;d.send(null)});v&&"undefined"===typeof performance&&(global.performance=require("perf_hooks").performance);var ra=e.print||console.log.bind(console),q=e.printErr||console.warn.bind(console);for(ba in aa)aa.hasOwnProperty(ba)&&(e[ba]=aa[ba]);aa=null;e.thisProgram&&(ca=e.thisProgram);e.quit&&(ea=e.quit);function sa(a){ta||(ta={});ta[a]||(ta[a]=1,q(a))}var ta,ua;e.wasmBinary&&(ua=e.wasmBinary);var noExitRuntime=e.noExitRuntime||!0;"object"!==typeof WebAssembly&&A("no native wasm support detected");
function va(a,b,c){c=c||"i8";"*"===c.charAt(c.length-1)&&(c="i32");switch(c){case "i1":C[a>>0]=b;break;case "i8":C[a>>0]=b;break;case "i16":wa[a>>1]=b;break;case "i32":D[a>>2]=b;break;case "i64":xa=[b>>>0,(E=b,1<=+Math.abs(E)?0<E?(Math.min(+Math.floor(E/4294967296),4294967295)|0)>>>0:~~+Math.ceil((E-+(~~E>>>0))/4294967296)>>>0:0)];D[a>>2]=xa[0];D[a+4>>2]=xa[1];break;case "float":ya[a>>2]=b;break;case "double":za[a>>3]=b;break;default:A("invalid type for setValue: "+c)}}var F,Aa,Ba=!1,Ca;
function assert(a,b){a||A("Assertion failed: "+b)}function Da(a){var b=G(a.length);a.subarray||a.slice?H.set(a,b):H.set(new Uint8Array(a),b);return b}
function Ea(a,b,c){c=b+c;for(var d="";!(b>=c);){var f=a[b++];if(!f)break;if(f&128){var g=a[b++]&63;if(192==(f&224))d+=String.fromCharCode((f&31)<<6|g);else{var k=a[b++]&63;f=224==(f&240)?(f&15)<<12|g<<6|k:(f&7)<<18|g<<12|k<<6|a[b++]&63;65536>f?d+=String.fromCharCode(f):(f-=65536,d+=String.fromCharCode(55296|f>>10,56320|f&1023))}}else d+=String.fromCharCode(f)}return d}function I(a,b){return a?Ea(H,a,b):""}
function Fa(a,b,c,d){if(!(0<d))return 0;var f=c;d=c+d-1;for(var g=0;g<a.length;++g){var k=a.charCodeAt(g);if(55296<=k&&57343>=k){var m=a.charCodeAt(++g);k=65536+((k&1023)<<10)|m&1023}if(127>=k){if(c>=d)break;b[c++]=k}else{if(2047>=k){if(c+1>=d)break;b[c++]=192|k>>6}else{if(65535>=k){if(c+2>=d)break;b[c++]=224|k>>12}else{if(c+3>=d)break;b[c++]=240|k>>18;b[c++]=128|k>>12&63}b[c++]=128|k>>6&63}b[c++]=128|k&63}}b[c]=0;return c-f}
function Ga(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}return b}function Ha(a,b){for(var c="",d=0;!(d>=b/2);++d){var f=wa[a+2*d>>1];if(0==f)break;c+=String.fromCharCode(f)}return c}function Ia(a,b,c){void 0===c&&(c=2147483647);if(2>c)return 0;c-=2;var d=b;c=c<2*a.length?c/2:a.length;for(var f=0;f<c;++f)wa[b>>1]=a.charCodeAt(f),b+=2;wa[b>>1]=0;return b-d}
function Ja(a){return 2*a.length}function Ka(a,b){for(var c=0,d="";!(c>=b/4);){var f=D[a+4*c>>2];if(0==f)break;++c;65536<=f?(f-=65536,d+=String.fromCharCode(55296|f>>10,56320|f&1023)):d+=String.fromCharCode(f)}return d}function La(a,b,c){void 0===c&&(c=2147483647);if(4>c)return 0;var d=b;c=d+c-4;for(var f=0;f<a.length;++f){var g=a.charCodeAt(f);if(55296<=g&&57343>=g){var k=a.charCodeAt(++f);g=65536+((g&1023)<<10)|k&1023}D[b>>2]=g;b+=4;if(b+4>c)break}D[b>>2]=0;return b-d}
function Ma(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&++c;b+=4}return b}var ia,C,H,wa,Na,D,J,ya,za,Oa=e.INITIAL_MEMORY||134217728;
if(x)F=e.wasmMemory,ia=e.buffer;else if(e.wasmMemory)F=e.wasmMemory;else if(F=new WebAssembly.Memory({initial:Oa/65536,maximum:Oa/65536,shared:!0}),!(F.buffer instanceof SharedArrayBuffer))throw q("requested a shared WebAssembly.Memory but the returned buffer is not a SharedArrayBuffer, indicating that while the browser has SharedArrayBuffer it does not have WebAssembly threads support - you may need to set a flag"),v&&console.log("(on node you may need: --experimental-wasm-threads --experimental-wasm-bulk-memory and also use a recent version)"),
Error("bad memory");F&&(ia=F.buffer);Oa=ia.byteLength;var Pa=ia;ia=Pa;e.HEAP8=C=new Int8Array(Pa);e.HEAP16=wa=new Int16Array(Pa);e.HEAP32=D=new Int32Array(Pa);e.HEAPU8=H=new Uint8Array(Pa);e.HEAPU16=Na=new Uint16Array(Pa);e.HEAPU32=J=new Uint32Array(Pa);e.HEAPF32=ya=new Float32Array(Pa);e.HEAPF64=za=new Float64Array(Pa);var L,Qa=[],Ra=[],Sa=[],Ta=[];
function Ua(){x||(e.noFSInit||Va||(Va=!0,Wa(),e.stdin=e.stdin,e.stdout=e.stdout,e.stderr=e.stderr,e.stdin?N("/dev","stdin",e.stdin):Xa("/dev/tty","/dev/stdin"),e.stdout?N("/dev","stdout",null,e.stdout):Xa("/dev/tty","/dev/stdout"),e.stderr?N("/dev","stderr",null,e.stderr):Xa("/dev/tty1","/dev/stderr"),Ya("/dev/stdin",0),Ya("/dev/stdout",1),Ya("/dev/stderr",1)),Za(Ra))}function $a(){var a=e.preRun.shift();Qa.unshift(a)}var ab=0,bb=null,cb=null;
function db(){assert(!x,"addRunDependency cannot be used in a pthread worker");ab++;e.monitorRunDependencies&&e.monitorRunDependencies(ab)}function eb(){ab--;e.monitorRunDependencies&&e.monitorRunDependencies(ab);if(0==ab&&(null!==bb&&(clearInterval(bb),bb=null),cb)){var a=cb;cb=null;a()}}e.preloadedImages={};e.preloadedAudios={};
function A(a){if(e.onAbort)e.onAbort(a);x&&console.error("Pthread aborting at "+Error().stack);q(a);Ba=!0;Ca=1;throw new WebAssembly.RuntimeError("abort("+a+"). Build with -s ASSERTIONS=1 for more info.");}function fb(a){var b=gb;return String.prototype.startsWith?b.startsWith(a):0===b.indexOf(a)}function hb(){return fb("data:application/octet-stream;base64,")}var gb="index.wasm";hb()||(gb=ja(gb));
function ib(){var a=gb;try{if(a==gb&&ua)return new Uint8Array(ua);if(ma)return ma(a);throw"both async and sync fetching of the wasm failed";}catch(b){A(b)}}
function jb(){if(!ua&&(fa||u)){if("function"===typeof fetch&&!fb("file://"))return fetch(gb,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+gb+"'";return a.arrayBuffer()}).catch(function(){return ib()});if(la)return new Promise(function(a,b){la(gb,function(c){a(new Uint8Array(c))},b)})}return Promise.resolve().then(function(){return ib()})}
var E,xa,lb={16030596:function(){return window.innerWidth||document.documentElement.clientWidth||document.body.clientWidth},16030714:function(){return window.innerHeight||document.documentElement.clientHeight||document.body.clientHeight},16030837:function(){throw"Canceled!";},16030855:function(a,b){setTimeout(function(){kb(a,b)},0)}};
function Za(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(e);else{var c=b.Tc;"number"===typeof c?void 0===b.ub?L.get(c)():L.get(c)(b.ub):c(void 0===b.ub?null:b.ub)}}}function mb(a,b){if(0>=a||a>C.length||a&1||0>b)return-28;if(0==b)return 0;2147483647<=b&&(b=Infinity);var c=Atomics.load(D,nb>>2),d=0;if(c==a&&Atomics.compareExchange(D,nb>>2,c,0)==c&&(--b,d=1,0>=b))return 1;a=Atomics.notify(D,a>>2,b);if(0<=a)return a+d;throw"Atomics.notify returned an unexpected value "+a;}
e._emscripten_futex_wake=mb;
var O={lb:[],qb:[],ac:[],Zc:function(){for(var a=0;16>a;++a)O.cc()},$c:function(){for(var a=G(228),b=0;57>b;++b)J[a/4+b]=0;D[a+12>>2]=a;b=a+152;D[b>>2]=b;var c=G(512);for(b=0;128>b;++b)J[c/4+b]=0;Atomics.store(J,a+100>>2,c);Atomics.store(J,a+40>>2,a);ob(a,!u,1);pb(a)},ad:function(){O.receiveObjectTransfer=O.hd;O.threadInit=O.xd;O.threadCancel=O.wd;O.threadExit=O.Hc;O.setExitStatus=O.od},jb:{},Ic:[],ge:function(){},ld:function(){for(;0<O.Ic.length;)O.Ic.pop()();x&&qb()&&rb()},Bc:function(a,b){Atomics.store(J,
a+56>>2,1);Atomics.store(J,a+60>>2,0);O.ld();Atomics.store(J,a+4>>2,b);Atomics.store(J,a+0>>2,1);mb(a+0,2147483647);ob(0,0,0)},od:function(a){Ca=a},Hc:function(a){var b=qb();b&&(O.Bc(b,a),x&&postMessage({cmd:"exit"}))},wd:function(){O.Bc(qb(),-1);postMessage({cmd:"cancelDone"})},vd:function(){for(var a in O.jb){var b=O.jb[a];b&&b.worker&&O.Kb(b.worker)}O.jb={};for(a=0;a<O.lb.length;++a){var c=O.lb[a];c.terminate()}O.lb=[];for(a=0;a<O.qb.length;++a)c=O.qb[a],b=c.gb,O.Vb(b),c.terminate();O.qb=[]},Vb:function(a){if(a){if(a.kb){var b=
D[a.kb+100>>2];D[a.kb+100>>2]=0;P(b);P(a.kb)}a.kb=0;a.Qb&&a.sb&&P(a.sb);a.sb=0;a.worker&&(a.worker.gb=null)}},Kb:function(a){O.md(function(){delete O.jb[a.gb.kb];O.lb.push(a);O.qb.splice(O.qb.indexOf(a),1);O.Vb(a.gb);a.gb=void 0})},md:function(a){D[sb>>2]=0;try{a()}finally{D[sb>>2]=1}},hd:function(){},xd:function(){qb();for(var a in O.ac)O.ac[a]()},qc:function(a,b){a.onmessage=function(c){var d=c.data,f=d.cmd;a.gb&&(O.Rc=a.gb.kb);if(d.targetThread&&d.targetThread!=qb()){var g=O.jb[d.he];g?g.worker.postMessage(c.data,
d.transferList):console.error('Internal error! Worker sent a message "'+f+'" to target pthread '+d.targetThread+", but that thread no longer exists!")}else if("processQueuedMainThreadWork"===f)tb();else if("spawnThread"===f)ub(c.data);else if("cleanupThread"===f){c=d.thread;if(x)throw"Internal Error! cleanupThread() can only ever be called from main application thread!";if(!c)throw"Internal Error! Null pthread_ptr in cleanupThread!";if(d=O.jb[c])D[c+12>>2]=0,O.Kb(d.worker)}else if("killThread"===
f){c=d.thread;if(x)throw"Internal Error! killThread() can only ever be called from main application thread!";if(!c)throw"Internal Error! Null pthread_ptr in killThread!";D[c+12>>2]=0;c=O.jb[c];c.worker.terminate();O.Vb(c);O.qb.splice(O.qb.indexOf(c.worker),1);c.worker.gb=void 0}else if("cancelThread"===f){c=d.thread;if(x)throw"Internal Error! cancelThread() can only ever be called from main application thread!";if(!c)throw"Internal Error! Null pthread_ptr in cancelThread!";O.jb[c].worker.postMessage({cmd:"cancel"})}else if("loaded"===
f)a.loaded=!0,b&&b(a),a.Db&&(a.Db(),delete a.Db);else if("print"===f)ra("Thread "+d.threadId+": "+d.text);else if("printErr"===f)q("Thread "+d.threadId+": "+d.text);else if("alert"===f)alert("Thread "+d.threadId+": "+d.text);else if("exit"===f)a.gb&&Atomics.load(J,a.gb.kb+64>>2)&&O.Kb(a);else if("exitProcess"===f)try{vb(d.returnCode)}catch(k){if(k instanceof pa)return;throw k;}else"cancelDone"===f?O.Kb(a):"objectTransfer"!==f&&("setimmediate"===c.data.target?a.postMessage(c.data):q("worker sent an unknown command "+
f));O.Rc=void 0};a.onerror=function(c){q("pthread sent an error! "+c.filename+":"+c.lineno+": "+c.message)};v&&(a.on("message",function(c){a.onmessage({data:c})}),a.on("error",function(c){a.onerror(c)}),a.on("exit",function(){}));a.postMessage({cmd:"load",urlOrBlob:e.mainScriptUrlOrBlob||_scriptDir,wasmMemory:F,wasmModule:Aa})},cc:function(){var a=ja("index.worker.js");O.lb.push(new Worker(a))},Uc:function(){0==O.lb.length&&(O.cc(),O.qc(O.lb[0]));return O.lb.pop()},Hd:function(a){for(a=performance.now()+
a;performance.now()<a;);}};e.establishStackSpace=function(a,b){wb(a,b);xb(a)};e.invokeEntryPoint=function(a,b){return L.get(a)(b)};var yb=0;function zb(){return noExitRuntime||0<yb}e.keepRuntimeAlive=zb;var Ab;v?Ab=function(){var a=process.hrtime();return 1E3*a[0]+a[1]/1E6}:x?Ab=function(){return performance.now()-e.__performance_now_clock_drift}:"undefined"!==typeof dateNow?Ab=dateNow:Ab=function(){return performance.now()};
function Bb(a){this.yb=a-16;this.td=function(b){D[this.yb+8>>2]=b};this.qd=function(b){D[this.yb+0>>2]=b};this.rd=function(){D[this.yb+4>>2]=0};this.pd=function(){C[this.yb+12>>0]=0};this.sd=function(){C[this.yb+13>>0]=0};this.Xc=function(b,c){this.td(b);this.qd(c);this.rd();this.pd();this.sd()}}var Cb=0;function Db(a,b){for(var c=0,d=a.length-1;0<=d;d--){var f=a[d];"."===f?a.splice(d,1):".."===f?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a}
function Eb(a){var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=Db(a.split("/").filter(function(d){return!!d}),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a}function Fb(a){var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b}function Gb(a){if("/"===a)return"/";a=Eb(a);a=a.replace(/\/$/,"");var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)}
function Hb(){if("object"===typeof crypto&&"function"===typeof crypto.getRandomValues){var a=new Uint8Array(1);return function(){crypto.getRandomValues(a);return a[0]}}if(v)try{var b=require("crypto");return function(){return b.randomBytes(1)[0]}}catch(c){}return function(){A("randomDevice")}}
function Ib(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:"/";if("string"!==typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=Db(a.split("/").filter(function(d){return!!d}),!b).join("/");return(b?"/":"")+a||"."}var Jb=[];function Kb(a,b){Jb[a]={input:[],output:[],xb:b};Lb(a,Mb)}
var Mb={open:function(a){var b=Jb[a.node.rdev];if(!b)throw new Q(43);a.tty=b;a.seekable=!1},close:function(a){a.tty.xb.flush(a.tty)},flush:function(a){a.tty.xb.flush(a.tty)},read:function(a,b,c,d){if(!a.tty||!a.tty.xb.nc)throw new Q(60);for(var f=0,g=0;g<d;g++){try{var k=a.tty.xb.nc(a.tty)}catch(m){throw new Q(29);}if(void 0===k&&0===f)throw new Q(6);if(null===k||void 0===k)break;f++;b[c+g]=k}f&&(a.node.timestamp=Date.now());return f},write:function(a,b,c,d){if(!a.tty||!a.tty.xb.Zb)throw new Q(60);
try{for(var f=0;f<d;f++)a.tty.xb.Zb(a.tty,b[c+f])}catch(g){throw new Q(29);}d&&(a.node.timestamp=Date.now());return f}},Ob={nc:function(a){if(!a.input.length){var b=null;if(v){var c=Buffer.eb?Buffer.eb(256):new Buffer(256),d=0;try{d=na.readSync(process.stdin.fd,c,0,256,null)}catch(f){if(-1!=f.toString().indexOf("EOF"))d=0;else throw f;}0<d?b=c.slice(0,d).toString("utf-8"):b=null}else"undefined"!=typeof window&&"function"==typeof window.prompt?(b=window.prompt("Input: "),null!==b&&(b+="\n")):"function"==
typeof readline&&(b=readline(),null!==b&&(b+="\n"));if(!b)return null;a.input=Nb(b,!0)}return a.input.shift()},Zb:function(a,b){null===b||10===b?(ra(Ea(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(ra(Ea(a.output,0)),a.output=[])}},Pb={Zb:function(a,b){null===b||10===b?(q(Ea(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(q(Ea(a.output,0)),a.output=[])}},R={hb:null,nb:function(){return R.createNode(null,
"/",16895,0)},createNode:function(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new Q(63);R.hb||(R.hb={dir:{node:{pb:R.$a.pb,fb:R.$a.fb,lookup:R.$a.lookup,Ib:R.$a.Ib,rename:R.$a.rename,unlink:R.$a.unlink,rmdir:R.$a.rmdir,readdir:R.$a.readdir,symlink:R.$a.symlink},stream:{rb:R.ab.rb}},file:{node:{pb:R.$a.pb,fb:R.$a.fb},stream:{rb:R.ab.rb,read:R.ab.read,write:R.ab.write,bc:R.ab.bc,uc:R.ab.uc,xc:R.ab.xc}},link:{node:{pb:R.$a.pb,fb:R.$a.fb,readlink:R.$a.readlink},stream:{}},fc:{node:{pb:R.$a.pb,
fb:R.$a.fb},stream:Qb}});c=Rb(a,b,c,d);16384===(c.mode&61440)?(c.$a=R.hb.dir.node,c.ab=R.hb.dir.stream,c.Za={}):32768===(c.mode&61440)?(c.$a=R.hb.file.node,c.ab=R.hb.file.stream,c.bb=0,c.Za=null):40960===(c.mode&61440)?(c.$a=R.hb.link.node,c.ab=R.hb.link.stream):8192===(c.mode&61440)&&(c.$a=R.hb.fc.node,c.ab=R.hb.fc.stream);c.timestamp=Date.now();a&&(a.Za[b]=c,a.timestamp=c.timestamp);return c},Sd:function(a){return a.Za?a.Za.subarray?a.Za.subarray(0,a.bb):new Uint8Array(a.Za):new Uint8Array(0)},
jc:function(a,b){var c=a.Za?a.Za.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)>>>0),0!=c&&(b=Math.max(b,256)),c=a.Za,a.Za=new Uint8Array(b),0<a.bb&&a.Za.set(c.subarray(0,a.bb),0))},kd:function(a,b){if(a.bb!=b)if(0==b)a.Za=null,a.bb=0;else{var c=a.Za;a.Za=new Uint8Array(b);c&&a.Za.set(c.subarray(0,Math.min(b,a.bb)));a.bb=b}},$a:{pb:function(a){var b={};b.dev=8192===(a.mode&61440)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;16384===(a.mode&61440)?b.size=4096:32768===
(a.mode&61440)?b.size=a.bb:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.atime=new Date(a.timestamp);b.mtime=new Date(a.timestamp);b.ctime=new Date(a.timestamp);b.Pc=4096;b.blocks=Math.ceil(b.size/b.Pc);return b},fb:function(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);void 0!==b.size&&R.kd(a,b.size)},lookup:function(){throw Sb[44];},Ib:function(a,b,c,d){return R.createNode(a,b,c,d)},rename:function(a,b,c){if(16384===(a.mode&61440)){try{var d=Tb(b,
c)}catch(g){}if(d)for(var f in d.Za)throw new Q(55);}delete a.parent.Za[a.name];a.parent.timestamp=Date.now();a.name=c;b.Za[c]=a;b.timestamp=a.parent.timestamp;a.parent=b},unlink:function(a,b){delete a.Za[b];a.timestamp=Date.now()},rmdir:function(a,b){var c=Tb(a,b),d;for(d in c.Za)throw new Q(55);delete a.Za[b];a.timestamp=Date.now()},readdir:function(a){var b=[".",".."],c;for(c in a.Za)a.Za.hasOwnProperty(c)&&b.push(c);return b},symlink:function(a,b,c){a=R.createNode(a,b,41471,0);a.link=c;return a},
readlink:function(a){if(40960!==(a.mode&61440))throw new Q(28);return a.link}},ab:{read:function(a,b,c,d,f){var g=a.node.Za;if(f>=a.node.bb)return 0;a=Math.min(a.node.bb-f,d);if(8<a&&g.subarray)b.set(g.subarray(f,f+a),c);else for(d=0;d<a;d++)b[c+d]=g[f+d];return a},write:function(a,b,c,d,f,g){if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.Za||a.Za.subarray)){if(g)return a.Za=b.subarray(c,c+d),a.bb=d;if(0===a.bb&&0===f)return a.Za=b.slice(c,c+d),a.bb=d;if(f+d<=a.bb)return a.Za.set(b.subarray(c,
c+d),f),d}R.jc(a,f+d);if(a.Za.subarray&&b.subarray)a.Za.set(b.subarray(c,c+d),f);else for(g=0;g<d;g++)a.Za[f+g]=b[c+g];a.bb=Math.max(a.bb,f+d);return d},rb:function(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.bb);if(0>b)throw new Q(28);return b},bc:function(a,b,c){R.jc(a.node,b+c);a.node.bb=Math.max(a.node.bb,b+c)},uc:function(a,b,c,d,f,g){if(0!==b)throw new Q(28);if(32768!==(a.node.mode&61440))throw new Q(43);a=a.node.Za;if(g&2||a.buffer!==ia){if(0<d||d+c<a.length)a.subarray?
a=a.subarray(d,d+c):a=Array.prototype.slice.call(a,d,d+c);d=!0;g=16384*Math.ceil(c/16384);for(b=G(g);c<g;)C[b+c++]=0;c=b;if(!c)throw new Q(48);C.set(a,c)}else d=!1,c=a.byteOffset;return{yb:c,Fd:d}},xc:function(a,b,c,d,f){if(32768!==(a.node.mode&61440))throw new Q(43);if(f&2)return 0;R.ab.write(a,b,0,d,c,!1);return 0}}},Ub=null,Vb={},Wb=[],Xb=1,Yb=null,Zb=!0,$b={},Q=null,Sb={};
function ac(a,b){a=Ib("/",a);b=b||{};if(!a)return{path:"",node:null};var c={kc:!0,$b:0},d;for(d in c)void 0===b[d]&&(b[d]=c[d]);if(8<b.$b)throw new Q(32);a=Db(a.split("/").filter(function(k){return!!k}),!1);var f=Ub;c="/";for(d=0;d<a.length;d++){var g=d===a.length-1;if(g&&b.parent)break;f=Tb(f,a[d]);c=Eb(c+"/"+a[d]);f.Cb&&(!g||g&&b.kc)&&(f=f.Cb.root);if(!g||b.Ub)for(g=0;40960===(f.mode&61440);)if(f=bc(c),c=Ib(Fb(c),f),f=ac(c,{$b:b.$b}).node,40<g++)throw new Q(32);}return{path:c,node:f}}
function cc(a){for(var b;;){if(a===a.parent)return a=a.nb.vc,b?"/"!==a[a.length-1]?a+"/"+b:a+b:a;b=b?a.name+"/"+b:a.name;a=a.parent}}function dc(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%Yb.length}function Tb(a,b){var c;if(c=(c=ec(a,"x"))?c:a.$a.lookup?0:2)throw new Q(c,a);for(c=Yb[dc(a.id,b)];c;c=c.wb){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.$a.lookup(a,b)}
function Rb(a,b,c,d){a=new fc(a,b,c,d);b=dc(a.parent.id,a.name);a.wb=Yb[b];return Yb[b]=a}var hc={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090};function ic(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}function ec(a,b){if(Zb)return 0;if(-1===b.indexOf("r")||a.mode&292){if(-1!==b.indexOf("w")&&!(a.mode&146)||-1!==b.indexOf("x")&&!(a.mode&73))return 2}else return 2;return 0}function jc(a,b){try{return Tb(a,b),20}catch(c){}return ec(a,"wx")}
function kc(){var a=4096;for(var b=0;b<=a;b++)if(!Wb[b])return b;throw new Q(33);}function lc(a){mc||(mc=function(){},mc.prototype={});var b=new mc,c;for(c in a)b[c]=a[c];a=b;b=kc();a.fd=b;return Wb[b]=a}var Qb={open:function(a){a.ab=Vb[a.node.rdev].ab;a.ab.open&&a.ab.open(a)},rb:function(){throw new Q(70);}};function Lb(a,b){Vb[a]={ab:b}}
function nc(a,b){var c="/"===b,d=!b;if(c&&Ub)throw new Q(10);if(!c&&!d){var f=ac(b,{kc:!1});b=f.path;f=f.node;if(f.Cb)throw new Q(10);if(16384!==(f.mode&61440))throw new Q(54);}b={type:a,de:{},vc:b,ed:[]};a=a.nb(b);a.nb=b;b.root=a;c?Ub=a:f&&(f.Cb=b,f.nb&&f.nb.ed.push(b))}function oc(a,b,c){var d=ac(a,{parent:!0}).node;a=Gb(a);if(!a||"."===a||".."===a)throw new Q(28);var f=jc(d,a);if(f)throw new Q(f);if(!d.$a.Ib)throw new Q(63);return d.$a.Ib(d,a,b,c)}function S(a){return oc(a,16895,0)}
function pc(a,b,c){"undefined"===typeof c&&(c=b,b=438);return oc(a,b|8192,c)}function Xa(a,b){if(!Ib(a))throw new Q(44);var c=ac(b,{parent:!0}).node;if(!c)throw new Q(44);b=Gb(b);var d=jc(c,b);if(d)throw new Q(d);if(!c.$a.symlink)throw new Q(63);c.$a.symlink(c,b,a)}
function qc(a){var b=ac(a,{parent:!0}).node,c=Gb(a),d=Tb(b,c);a:{try{var f=Tb(b,c)}catch(k){f=k.mb;break a}var g=ec(b,"wx");f=g?g:16384===(f.mode&61440)?31:0}if(f)throw new Q(f);if(!b.$a.unlink)throw new Q(63);if(d.Cb)throw new Q(10);try{$b.willDeletePath&&$b.willDeletePath(a)}catch(k){q("FS.trackingDelegate['willDeletePath']('"+a+"') threw an exception: "+k.message)}b.$a.unlink(b,c);b=dc(d.parent.id,d.name);if(Yb[b]===d)Yb[b]=d.wb;else for(b=Yb[b];b;){if(b.wb===d){b.wb=d.wb;break}b=b.wb}try{if($b.onDeletePath)$b.onDeletePath(a)}catch(k){q("FS.trackingDelegate['onDeletePath']('"+
a+"') threw an exception: "+k.message)}}function bc(a){a=ac(a).node;if(!a)throw new Q(44);if(!a.$a.readlink)throw new Q(28);return Ib(cc(a.parent),a.$a.readlink(a))}function rc(a,b){a="string"===typeof a?ac(a,{Ub:!0}).node:a;if(!a.$a.fb)throw new Q(63);a.$a.fb(a,{mode:b&4095|a.mode&-4096,timestamp:Date.now()})}
function Ya(a,b,c){if(""===a)throw new Q(44);if("string"===typeof b){var d=hc[b];if("undefined"===typeof d)throw Error("Unknown file open mode: "+b);b=d}c=b&64?("undefined"===typeof c?438:c)&4095|32768:0;if("object"===typeof a)var f=a;else{a=Eb(a);try{f=ac(a,{Ub:!(b&131072)}).node}catch(g){}}d=!1;if(b&64)if(f){if(b&128)throw new Q(20);}else f=oc(a,c,0),d=!0;if(!f)throw new Q(44);8192===(f.mode&61440)&&(b&=-513);if(b&65536&&16384!==(f.mode&61440))throw new Q(54);if(!d&&(c=f?40960===(f.mode&61440)?
32:16384===(f.mode&61440)&&("r"!==ic(b)||b&512)?31:ec(f,ic(b)):44))throw new Q(c);if(b&512){c=f;c="string"===typeof c?ac(c,{Ub:!0}).node:c;if(!c.$a.fb)throw new Q(63);if(16384===(c.mode&61440))throw new Q(31);if(32768!==(c.mode&61440))throw new Q(28);if(d=ec(c,"w"))throw new Q(d);c.$a.fb(c,{size:0,timestamp:Date.now()})}b&=-131713;f=lc({node:f,path:cc(f),flags:b,seekable:!0,position:0,ab:f.ab,Dd:[],error:!1});f.ab.open&&f.ab.open(f);!e.logReadFiles||b&1||(sc||(sc={}),a in sc||(sc[a]=1,q("FS.trackingDelegate error on read file: "+
a)));try{$b.onOpenFile&&(c=0,1!==(b&2097155)&&(c|=1),0!==(b&2097155)&&(c|=2),$b.onOpenFile(a,c))}catch(g){q("FS.trackingDelegate['onOpenFile']('"+a+"', flags) threw an exception: "+g.message)}return f}function tc(a){if(null===a.fd)throw new Q(8);a.Xb&&(a.Xb=null);try{a.ab.close&&a.ab.close(a)}catch(b){throw b;}finally{Wb[a.fd]=null}a.fd=null}
function uc(a,b,c){if(null===a.fd)throw new Q(8);if(!a.seekable||!a.ab.rb)throw new Q(70);if(0!=c&&1!=c&&2!=c)throw new Q(28);a.position=a.ab.rb(a,b,c);a.Dd=[]}
function vc(a,b,c,d,f,g){if(0>d||0>f)throw new Q(28);if(null===a.fd)throw new Q(8);if(0===(a.flags&2097155))throw new Q(8);if(16384===(a.node.mode&61440))throw new Q(31);if(!a.ab.write)throw new Q(28);a.seekable&&a.flags&1024&&uc(a,0,2);var k="undefined"!==typeof f;if(!k)f=a.position;else if(!a.seekable)throw new Q(70);b=a.ab.write(a,b,c,d,f,g);k||(a.position+=b);try{if(a.path&&$b.onWriteToFile)$b.onWriteToFile(a.path)}catch(m){q("FS.trackingDelegate['onWriteToFile']('"+a.path+"') threw an exception: "+
m.message)}return b}function Wa(){Q||(Q=function(a,b){this.node=b;this.nd=function(c){this.mb=c};this.nd(a);this.message="FS error"},Q.prototype=Error(),Q.prototype.constructor=Q,[44].forEach(function(a){Sb[a]=new Q(a);Sb[a].stack="<generic error, no stack>"}))}var Va;function wc(a,b){var c=0;a&&(c|=365);b&&(c|=146);return c}function xc(a,b){a="string"===typeof a?a:cc(a);for(b=b.split("/").reverse();b.length;){var c=b.pop();if(c){var d=Eb(a+"/"+c);try{S(d)}catch(f){}a=d}}return d}
function yc(a,b,c,d){a=Eb(("string"===typeof a?a:cc(a))+"/"+b);c=wc(c,d);return oc(a,(void 0!==c?c:438)&4095|32768,0)}function zc(a,b,c,d,f,g){a=b?Eb(("string"===typeof a?a:cc(a))+"/"+b):a;d=wc(d,f);f=oc(a,(void 0!==d?d:438)&4095|32768,0);if(c){if("string"===typeof c){a=Array(c.length);b=0;for(var k=c.length;b<k;++b)a[b]=c.charCodeAt(b);c=a}rc(f,d|146);a=Ya(f,577);vc(a,c,0,c.length,0,g);tc(a);rc(f,d)}return f}
function N(a,b,c,d){a=Eb(("string"===typeof a?a:cc(a))+"/"+b);b=wc(!!c,!!d);N.rc||(N.rc=64);var f=N.rc++<<8|0;Lb(f,{open:function(g){g.seekable=!1},close:function(){d&&d.buffer&&d.buffer.length&&d(10)},read:function(g,k,m,l){for(var t=0,p=0;p<l;p++){try{var r=c()}catch(w){throw new Q(29);}if(void 0===r&&0===t)throw new Q(6);if(null===r||void 0===r)break;t++;k[m+p]=r}t&&(g.node.timestamp=Date.now());return t},write:function(g,k,m,l){for(var t=0;t<l;t++)try{d(k[m+t])}catch(p){throw new Q(29);}l&&(g.node.timestamp=
Date.now());return t}});return pc(a,b,f)}function Ac(a){if(!(a.cd||a.dd||a.link||a.Za)){if("undefined"!==typeof XMLHttpRequest)throw Error("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");if(ka)try{a.Za=Nb(ka(a.url),!0),a.bb=a.Za.length}catch(b){throw new Q(29);}else throw Error("Cannot load without read() or XMLHttpRequest.");}}
function Bc(a,b,c,d,f){function g(){this.Yb=!1;this.eb=[]}g.prototype.get=function(p){if(!(p>this.length-1||0>p)){var r=p%this.chunkSize;return this.oc(p/this.chunkSize|0)[r]}};g.prototype.Pb=function(p){this.oc=p};g.prototype.dc=function(){var p=new XMLHttpRequest;p.open("HEAD",c,!1);p.send(null);if(!(200<=p.status&&300>p.status||304===p.status))throw Error("Couldn't load "+c+". Status: "+p.status);var r=Number(p.getResponseHeader("Content-length")),w,h=(w=p.getResponseHeader("Accept-Ranges"))&&
"bytes"===w;p=(w=p.getResponseHeader("Content-Encoding"))&&"gzip"===w;var n=1048576;h||(n=r);var y=this;y.Pb(function(B){var K=B*n,da=(B+1)*n-1;da=Math.min(da,r-1);if("undefined"===typeof y.eb[B]){var Ze=y.eb;if(K>da)throw Error("invalid range ("+K+", "+da+") or no bytes requested!");if(da>r-1)throw Error("only "+r+" bytes available! programmer error!");var M=new XMLHttpRequest;M.open("GET",c,!1);r!==n&&M.setRequestHeader("Range","bytes="+K+"-"+da);"undefined"!=typeof Uint8Array&&(M.responseType=
"arraybuffer");M.overrideMimeType&&M.overrideMimeType("text/plain; charset=x-user-defined");M.send(null);if(!(200<=M.status&&300>M.status||304===M.status))throw Error("Couldn't load "+c+". Status: "+M.status);K=void 0!==M.response?new Uint8Array(M.response||[]):Nb(M.responseText||"",!0);Ze[B]=K}if("undefined"===typeof y.eb[B])throw Error("doXHR failed!");return y.eb[B]});if(p||!r)n=r=1,n=r=this.oc(0).length,ra("LazyFiles on gzip forces download of the whole file when length is accessed");this.Lc=
r;this.Kc=n;this.Yb=!0};if("undefined"!==typeof XMLHttpRequest){if(!u)throw"Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc";var k=new g;Object.defineProperties(k,{length:{get:function(){this.Yb||this.dc();return this.Lc}},chunkSize:{get:function(){this.Yb||this.dc();return this.Kc}}});var m=void 0}else m=c,k=void 0;var l=yc(a,b,d,f);k?l.Za=k:m&&(l.Za=null,l.url=m);Object.defineProperties(l,{bb:{get:function(){return this.Za.length}}});
var t={};Object.keys(l.ab).forEach(function(p){var r=l.ab[p];t[p]=function(){Ac(l);return r.apply(null,arguments)}});t.read=function(p,r,w,h,n){Ac(l);p=p.node.Za;if(n>=p.length)return 0;h=Math.min(p.length-n,h);if(p.slice)for(var y=0;y<h;y++)r[w+y]=p[n+y];else for(y=0;y<h;y++)r[w+y]=p.get(n+y);return h};l.ab=t;return l}
function Cc(a,b,c,d,f,g,k,m,l,t){function p(h){function n(B){t&&t();m||zc(a,b,B,d,f,l);g&&g();eb(w)}var y=!1;e.preloadPlugins.forEach(function(B){!y&&B.canHandle(r)&&(B.handle(h,r,n,function(){k&&k();eb(w)}),y=!0)});y||n(h)}Dc();var r=b?Ib(Eb(a+"/"+b)):a,w="cp "+r;db(w);"string"==typeof c?Ec(c,function(h){p(h)},k):p(c)}var Fc={},mc,sc,Gc=void 0;function Hc(){Gc+=4;return D[Gc-4>>2]}function Ic(a){a=Wb[a];if(!a)throw new Q(8);return a}
function Jc(a,b,c){if(x)return T(2,1,a,b,c);Gc=c;try{var d=Ic(a);switch(b){case 21509:case 21505:return d.tty?0:-59;case 21510:case 21511:case 21512:case 21506:case 21507:case 21508:return d.tty?0:-59;case 21519:if(!d.tty)return-59;var f=Hc();return D[f>>2]=0;case 21520:return d.tty?-28:-59;case 21531:a=f=Hc();if(!d.ab.bd)throw new Q(59);return d.ab.bd(d,b,a);case 21523:return d.tty?0:-59;case 21524:return d.tty?0:-59;default:A("bad ioctl syscall "+b)}}catch(g){return"undefined"!==typeof Fc&&g instanceof
Q||A(g),-g.mb}}function Kc(a,b,c){if(x)return T(3,1,a,b,c);Gc=c;try{var d=I(a),f=c?Hc():0;return Ya(d,b,f).fd}catch(g){return"undefined"!==typeof Fc&&g instanceof Q||A(g),-g.mb}}function Lc(a){switch(a){case 1:return 0;case 2:return 1;case 4:return 2;case 8:return 3;default:throw new TypeError("Unknown type size: "+a);}}var Mc=void 0;function U(a){for(var b="";H[a];)b+=Mc[H[a++]];return b}var Nc={},Oc={},Pc={};
function Qc(a){if(void 0===a)return"_unknown";a=a.replace(/[^a-zA-Z0-9_]/g,"$");var b=a.charCodeAt(0);return 48<=b&&57>=b?"_"+a:a}function Rc(a,b){a=Qc(a);return(new Function("body","return function "+a+'() {\n    "use strict";    return body.apply(this, arguments);\n};\n'))(b)}
function Sc(a){var b=Error,c=Rc(a,function(d){this.name=a;this.message=d;d=Error(d).stack;void 0!==d&&(this.stack=this.toString()+"\n"+d.replace(/^Error(:[^\n]*)?\n/,""))});c.prototype=Object.create(b.prototype);c.prototype.constructor=c;c.prototype.toString=function(){return void 0===this.message?this.name:this.name+": "+this.message};return c}var Tc=void 0;function V(a){throw new Tc(a);}var Uc=void 0;
function Vc(a,b){function c(m){m=b(m);if(m.length!==d.length)throw new Uc("Mismatched type converter count");for(var l=0;l<d.length;++l)Wc(d[l],m[l])}var d=[];d.forEach(function(m){Pc[m]=a});var f=Array(a.length),g=[],k=0;a.forEach(function(m,l){Oc.hasOwnProperty(m)?f[l]=Oc[m]:(g.push(m),Nc.hasOwnProperty(m)||(Nc[m]=[]),Nc[m].push(function(){f[l]=Oc[m];++k;k===g.length&&c(f)}))});0===g.length&&c(f)}
function Wc(a,b,c){c=c||{};if(!("argPackAdvance"in b))throw new TypeError("registerType registeredInstance requires argPackAdvance");var d=b.name;a||V('type "'+d+'" must have a positive integer typeid pointer');if(Oc.hasOwnProperty(a)){if(c.Wc)return;V("Cannot register type '"+d+"' twice")}Oc[a]=b;delete Pc[a];Nc.hasOwnProperty(a)&&(b=Nc[a],delete Nc[a],b.forEach(function(f){f()}))}var Xc=[],W=[{},{value:void 0},{value:null},{value:!0},{value:!1}];
function Yc(a){switch(a){case void 0:return 1;case null:return 2;case !0:return 3;case !1:return 4;default:var b=Xc.length?Xc.pop():W.length;W[b]={jd:1,value:a};return b}}function Zc(a){return this.fromWireType(J[a>>2])}function $c(a){if(null===a)return"null";var b=typeof a;return"object"===b||"array"===b||"function"===b?a.toString():""+a}
function ad(a,b){switch(b){case 2:return function(c){return this.fromWireType(ya[c>>2])};case 3:return function(c){return this.fromWireType(za[c>>3])};default:throw new TypeError("Unknown float type: "+a);}}function bd(a){var b=Function;if(!(b instanceof Function))throw new TypeError("new_ called with constructor type "+typeof b+" which is not a function");var c=Rc(b.name||"unknownFunctionName",function(){});c.prototype=b.prototype;c=new c;a=b.apply(c,a);return a instanceof Object?a:c}
function cd(a){for(;a.length;){var b=a.pop();a.pop()(b)}}function dd(a,b){var c=e;if(void 0===c[a].ib){var d=c[a];c[a]=function(){c[a].ib.hasOwnProperty(arguments.length)||V("Function '"+b+"' called with an invalid number of arguments ("+arguments.length+") - expects one of ("+c[a].ib+")!");return c[a].ib[arguments.length].apply(this,arguments)};c[a].ib=[];c[a].ib[d.Nc]=d}}
function ed(a,b,c){e.hasOwnProperty(a)?((void 0===c||void 0!==e[a].ib&&void 0!==e[a].ib[c])&&V("Cannot register public name '"+a+"' twice"),dd(a,a),e.hasOwnProperty(c)&&V("Cannot register multiple overloads of a function with the same number of arguments ("+c+")!"),e[a].ib[c]=b):(e[a]=b,void 0!==c&&(e[a].ce=c))}function fd(a,b){for(var c=[],d=0;d<a;d++)c.push(D[(b>>2)+d]);return c}
function gd(a,b){var c=[];return function(){c.length=arguments.length;for(var d=0;d<arguments.length;d++)c[d]=arguments[d];-1!=a.indexOf("j")?(d=e["dynCall_"+a],d=c&&c.length?d.apply(null,[b].concat(c)):d.call(null,b)):d=L.get(b).apply(null,c);return d}}function hd(a,b){a=U(a);var c=-1!=a.indexOf("j")?gd(a,b):L.get(b);"function"!==typeof c&&V("unknown function pointer with signature "+a+": "+b);return c}var id=void 0;function jd(a){a=kd(a);var b=U(a);P(a);return b}
function ld(a,b){function c(g){f[g]||Oc[g]||(Pc[g]?Pc[g].forEach(c):(d.push(g),f[g]=!0))}var d=[],f={};b.forEach(c);throw new id(a+": "+d.map(jd).join([", "]));}function md(a,b,c){switch(b){case 0:return c?function(d){return C[d]}:function(d){return H[d]};case 1:return c?function(d){return wa[d>>1]}:function(d){return Na[d>>1]};case 2:return c?function(d){return D[d>>2]}:function(d){return J[d>>2]};default:throw new TypeError("Unknown integer type: "+a);}}
function nd(a,b){od=a;pd=b;if(qd)if(rd||(yb+=1,rd=!0),0==a)sd=function(){var d=Math.max(0,td+b-Ab())|0;setTimeout(ud,d)};else if(1==a)sd=function(){vd(ud)};else if(2==a){if("undefined"===typeof setImmediate){var c=[];addEventListener("message",function(d){if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);setImmediate=function(d){c.push(d);u?(void 0===e.setImmediates&&(e.setImmediates=[]),e.setImmediates.push(d),postMessage({target:"setimmediate"})):postMessage("setimmediate",
"*")}}sd=function(){setImmediate(ud)}}}function wd(){if(!zb())try{if(x){var a=Ca;x?O.Hc(a):vb(a);v&&process.exit(a);throw"unwind";}vb(Ca)}catch(b){if(!(b instanceof pa))throw b;}}
function xd(a,b,c,d,f){function g(){return k<yd?(--yb,wd(),!1):!0}assert(!qd,"emscripten_set_main_loop: there can only be one main loop function at once: call emscripten_cancel_main_loop to cancel the previous one before setting a new one with different parameters.");qd=a;zd=d;var k=yd;rd=!1;ud=function(){if(!Ba)if(0<Ad.length){var m=Date.now(),l=Ad.shift();l.Tc(l.ub);if(Bd){var t=Bd,p=0==t%1?t-1:Math.floor(t);Bd=l.Ld?p:(8*t+(p+.5))/9}console.log('main loop blocker "'+l.name+'" took '+(Date.now()-
m)+" ms");e.setStatus&&(m=e.statusMessage||"Please wait...",l=Bd,t=Cd.Qd,l?l<t?e.setStatus(m+" ("+(t-l)+"/"+t+")"):e.setStatus(m):e.setStatus(""));g()&&setTimeout(ud,0)}else g()&&(Dd=Dd+1|0,1==od&&1<pd&&0!=Dd%pd?sd():(0==od&&(td=Ab()),Ba||e.preMainLoop&&!1===e.preMainLoop()||(Ed(a),e.postMainLoop&&e.postMainLoop()),g()&&("object"===typeof SDL&&SDL.audio&&SDL.audio.gd&&SDL.audio.gd(),sd())))};f||(b&&0<b?nd(0,1E3/b):nd(1,1),sd());if(c)throw"unwind";}
function Ed(a){try{a()}catch(b){if(b instanceof pa)return;if("unwind"!==b)throw b&&"object"===typeof b&&b.stack&&q("exception thrown: "+[b,b.stack]),b;}x&&wd()}var rd=!1,sd=null,yd=0,qd=null,zd=0,od=0,pd=0,Dd=0,Ad=[],Cd={},td,ud,Bd,Fd=!1,Gd=!1,Hd=[];
function Dc(){function a(){Gd=document.pointerLockElement===e.canvas||document.mozPointerLockElement===e.canvas||document.webkitPointerLockElement===e.canvas||document.msPointerLockElement===e.canvas}e.preloadPlugins||(e.preloadPlugins=[]);if(!Id){Id=!0;try{Jd=!0}catch(c){Jd=!1,console.log("warning: no blob constructor, cannot create blobs with mimetypes")}Kd="undefined"!=typeof MozBlobBuilder?MozBlobBuilder:"undefined"!=typeof WebKitBlobBuilder?WebKitBlobBuilder:Jd?null:console.log("warning: no BlobBuilder");
Ld="undefined"!=typeof window?window.URL?window.URL:window.webkitURL:void 0;e.yc||"undefined"!==typeof Ld||(console.log("warning: Browser does not support creating object URLs. Built-in browser image decoding will not be available."),e.yc=!0);e.preloadPlugins.push({canHandle:function(c){return!e.yc&&/\.(jpg|jpeg|png|bmp)$/i.test(c)},handle:function(c,d,f,g){var k=null;if(Jd)try{k=new Blob([c],{type:Md(d)}),k.size!==c.length&&(k=new Blob([(new Uint8Array(c)).buffer],{type:Md(d)}))}catch(t){sa("Blob constructor present but fails: "+
t+"; falling back to blob builder")}k||(k=new Kd,k.append((new Uint8Array(c)).buffer),k=k.getBlob());var m=Ld.createObjectURL(k),l=new Image;l.onload=function(){assert(l.complete,"Image "+d+" could not be decoded");var t=document.createElement("canvas");t.width=l.width;t.height=l.height;t.getContext("2d").drawImage(l,0,0);e.preloadedImages[d]=t;Ld.revokeObjectURL(m);f&&f(c)};l.onerror=function(){console.log("Image "+m+" could not be decoded");g&&g()};l.src=m}});e.preloadPlugins.push({canHandle:function(c){return!e.be&&
c.substr(-4)in{".ogg":1,".wav":1,".mp3":1}},handle:function(c,d,f,g){function k(r){l||(l=!0,e.preloadedAudios[d]=r,f&&f(c))}function m(){l||(l=!0,e.preloadedAudios[d]=new Audio,g&&g())}var l=!1;if(Jd){try{var t=new Blob([c],{type:Md(d)})}catch(r){return m()}t=Ld.createObjectURL(t);var p=new Audio;p.addEventListener("canplaythrough",function(){k(p)},!1);p.onerror=function(){if(!l){console.log("warning: browser could not fully decode audio "+d+", trying slower base64 approach");for(var r="",w=0,h=0,
n=0;n<c.length;n++)for(w=w<<8|c[n],h+=8;6<=h;){var y=w>>h-6&63;h-=6;r+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[y]}2==h?(r+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(w&3)<<4],r+="=="):4==h&&(r+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(w&15)<<2],r+="=");p.src="data:audio/x-"+d.substr(-3)+";base64,"+r;k(p)}};p.src=t;Nd(function(){k(p)})}else return m()}});var b=e.canvas;b&&(b.requestPointerLock=b.requestPointerLock||b.mozRequestPointerLock||
b.webkitRequestPointerLock||b.msRequestPointerLock||function(){},b.exitPointerLock=document.exitPointerLock||document.mozExitPointerLock||document.webkitExitPointerLock||document.msExitPointerLock||function(){},b.exitPointerLock=b.exitPointerLock.bind(document),document.addEventListener("pointerlockchange",a,!1),document.addEventListener("mozpointerlockchange",a,!1),document.addEventListener("webkitpointerlockchange",a,!1),document.addEventListener("mspointerlockchange",a,!1),e.elementPointerLock&&
b.addEventListener("click",function(c){!Gd&&e.canvas.requestPointerLock&&(e.canvas.requestPointerLock(),c.preventDefault())},!1))}}
function Od(a,b,c,d){if(b&&e.Bb&&a==e.canvas)return e.Bb;var f;if(b){var g={antialias:!1,alpha:!1,sc:2};if(d)for(var k in d)g[k]=d[k];if("undefined"!==typeof Pd&&(f=Qd(a,g)))var m=Rd[f].tb}else m=a.getContext("2d");if(!m)return null;c&&(b||assert("undefined"===typeof X,"cannot set in module if GLctx is used, but we are a non-GL context that would replace it"),e.Bb=m,b&&(Sd=Rd[f],e.Bb=X=Sd&&Sd.tb),e.je=b,Hd.forEach(function(l){l()}),Dc());return m}var Td=!1,Ud=void 0,Vd=void 0;
function Wd(a,b){function c(){Fd=!1;var g=d.parentNode;(document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===g?(d.exitFullscreen=Xd,Ud&&d.requestPointerLock(),Fd=!0,Vd?("undefined"!=typeof SDL&&(D[SDL.screen>>2]=J[SDL.screen>>2]|8388608),Yd(e.canvas),Zd()):Yd(d)):(g.parentNode.insertBefore(d,g),g.parentNode.removeChild(g),Vd?("undefined"!=typeof SDL&&(D[SDL.screen>>2]=J[SDL.screen>>2]&
-8388609),Yd(e.canvas),Zd()):Yd(d));if(e.onFullScreen)e.onFullScreen(Fd);if(e.onFullscreen)e.onFullscreen(Fd)}Ud=a;Vd=b;"undefined"===typeof Ud&&(Ud=!0);"undefined"===typeof Vd&&(Vd=!1);var d=e.canvas;Td||(Td=!0,document.addEventListener("fullscreenchange",c,!1),document.addEventListener("mozfullscreenchange",c,!1),document.addEventListener("webkitfullscreenchange",c,!1),document.addEventListener("MSFullscreenChange",c,!1));var f=document.createElement("div");d.parentNode.insertBefore(f,d);f.appendChild(d);
f.requestFullscreen=f.requestFullscreen||f.mozRequestFullScreen||f.msRequestFullscreen||(f.webkitRequestFullscreen?function(){f.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT)}:null)||(f.webkitRequestFullScreen?function(){f.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT)}:null);f.requestFullscreen()}
function Xd(){if(!Fd)return!1;(document.exitFullscreen||document.cancelFullScreen||document.mozCancelFullScreen||document.msExitFullscreen||document.webkitCancelFullScreen||function(){}).apply(document,[]);return!0}var $d=0;function vd(a){if("function"===typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===$d)$d=b+1E3/60;else for(;b+2>=$d;)$d+=1E3/60;setTimeout(a,Math.max($d-b,0))}}function Nd(a){yb+=1;setTimeout(function(){--yb;Ed(a)},1E4)}
function Md(a){return{jpg:"image/jpeg",jpeg:"image/jpeg",png:"image/png",bmp:"image/bmp",ogg:"audio/ogg",wav:"audio/wav",mp3:"audio/mpeg"}[a.substr(a.lastIndexOf(".")+1)]}var ae=0,be=0,ce=0,de=0;
function ee(a){if(Gd)"mousemove"!=a.type&&"mozMovementX"in a?ce=de=0:(ce=a.movementX||a.mozMovementX||a.webkitMovementX||0,de=a.movementY||a.mozMovementY||a.webkitMovementY||0),"undefined"!=typeof SDL?(ae=SDL.Zd+ce,be=SDL.$d+de):(ae+=ce,be+=de);else{var b=e.canvas.getBoundingClientRect(),c=e.canvas.width,d=e.canvas.height,f="undefined"!==typeof window.scrollX?window.scrollX:window.pageXOffset,g="undefined"!==typeof window.scrollY?window.scrollY:window.pageYOffset;"touchstart"!==a.type&&"touchend"!==
a.type&&"touchmove"!==a.type&&(f=a.pageX-(f+b.left),a=a.pageY-(g+b.top),f*=c/b.width,a*=d/b.height,ce=f-ae,de=a-be,ae=f,be=a)}}function Ec(a,b,c){var d="al "+a;la(a,function(f){assert(f,'Loading data file "'+a+'" failed (no arrayBuffer).');b(new Uint8Array(f));d&&eb(d)},function(){if(c)c();else throw'Loading data file "'+a+'" failed.';});d&&db(d)}var fe=[];function Zd(){var a=e.canvas;fe.forEach(function(b){b(a.width,a.height)})}function ge(a,b,c){Yd(e.canvas,a,b);c||Zd()}
function Yd(a,b,c){b&&c?(a.Ed=b,a.Vc=c):(b=a.Ed,c=a.Vc);var d=b,f=c;e.forcedAspectRatio&&0<e.forcedAspectRatio&&(d/f<e.forcedAspectRatio?d=Math.round(f*e.forcedAspectRatio):f=Math.round(d/e.forcedAspectRatio));if((document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===a.parentNode&&"undefined"!=typeof screen){var g=Math.min(screen.width/d,screen.height/f);d=Math.round(d*g);f=Math.round(f*
g)}Vd?(a.width!=d&&(a.width=d),a.height!=f&&(a.height=f),"undefined"!=typeof a.style&&(a.style.removeProperty("width"),a.style.removeProperty("height"))):(a.width!=b&&(a.width=b),a.height!=c&&(a.height=c),"undefined"!=typeof a.style&&(d!=b||f!=c?(a.style.setProperty("width",d+"px","important"),a.style.setProperty("height",f+"px","important")):(a.style.removeProperty("width"),a.style.removeProperty("height"))))}var Id,Jd,Kd,Ld;
function T(a,b){for(var c=arguments.length-2,d=he(),f=ie(8*c),g=f>>3,k=0;k<c;k++)za[g+k]=arguments[2+k];c=je(a,c,f,b);xb(d);return c}var ke=[],le=[],me=[0,"undefined"!==typeof document?document:0,"undefined"!==typeof window?window:0];function ne(a){a=2<a?I(a):a;return me[a]||("undefined"!==typeof document?document.querySelector(a):void 0)}
function oe(a,b,c){var d=ne(a);if(!d)return-4;d.Gb&&(D[d.Gb>>2]=b,D[d.Gb+4>>2]=c);if(d.zc||!d.Kd)d.zc&&(d=d.zc),a=!1,d.Fb&&d.Fb.tb&&(a=d.Fb.tb.getParameter(2978),a=0===a[0]&&0===a[1]&&a[2]===d.width&&a[3]===d.height),d.width=b,d.height=c,a&&d.Fb.tb.viewport(0,0,b,c);else{if(d.Gb){a=a?I(a):"";d=D[d.Gb+8>>2];var f=he(),g=ie(12),k=0;if(a){k=Ga(a)+1;var m=G(k);Fa(a,H,m,k);k=m}D[g>>2]=k;D[g+4>>2]=b;D[g+8>>2]=c;pe(0,d,657457152,0,k,g);xb(f);return 1}return-4}return 0}
function qe(a,b,c){return x?T(4,1,a,b,c):oe(a,b,c)}var re=1,se=[],te=[],ue=[],ve=[],we=[],Rd={},xe={};function ye(a){for(var b=re++,c=a.length;c<b;c++)a[c]=null;return b}function Qd(a,b){a.mc||(a.mc=a.getContext,a.getContext=function(d,f){f=a.mc(d,f);return"webgl"==d==f instanceof WebGLRenderingContext?f:null});var c=a.getContext("webgl2",b);return c?ze(c,b):0}
function ze(a,b){var c=G(8);D[c+4>>2]=qb();var d={Td:c,attributes:b,version:b.sc,tb:a};a.canvas&&(a.canvas.Fb=d);Rd[c]=d;("undefined"===typeof b.ic||b.ic)&&Ae(d);return c}
function Ae(a){a||(a=Sd);if(!a.Yc){a.Yc=!0;var b=a.tb;b.Od=b.getExtension("WEBGL_draw_instanced_base_vertex_base_instance");b.Xd=b.getExtension("WEBGL_multi_draw_instanced_base_vertex_base_instance");b.Pd=b.getExtension("EXT_disjoint_timer_query");b.ae=b.getExtension("WEBGL_multi_draw");(b.getSupportedExtensions()||[]).forEach(function(c){0>c.indexOf("lose_context")&&0>c.indexOf("debug")&&b.getExtension(c)})}}var Pd={},Be,Sd,Ce=["default","low-power","high-performance"],De={};
function Ee(){if(!Fe){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"===typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:ca||"./this.program"},b;for(b in De)a[b]=De[b];var c=[];for(b in a)c.push(b+"="+a[b]);Fe=c}return Fe}var Fe;
function Ge(a,b){if(x)return T(5,1,a,b);try{var c=0;Ee().forEach(function(d,f){var g=b+c;f=D[a+4*f>>2]=g;for(g=0;g<d.length;++g)C[f++>>0]=d.charCodeAt(g);C[f>>0]=0;c+=d.length+1});return 0}catch(d){return"undefined"!==typeof Fc&&d instanceof Q||A(d),d.mb}}function He(a,b){if(x)return T(6,1,a,b);try{var c=Ee();D[a>>2]=c.length;var d=0;c.forEach(function(f){d+=f.length+1});D[b>>2]=d;return 0}catch(f){return"undefined"!==typeof Fc&&f instanceof Q||A(f),f.mb}}
function Ie(a){if(x)return T(7,1,a);try{var b=Ic(a);tc(b);return 0}catch(c){return"undefined"!==typeof Fc&&c instanceof Q||A(c),c.mb}}
function Je(a,b,c,d){if(x)return T(8,1,a,b,c,d);try{a:{for(var f=Ic(a),g=a=0;g<c;g++){var k=D[b+(8*g+4)>>2],m=f,l=D[b+8*g>>2],t=k,p=void 0,r=C;if(0>t||0>p)throw new Q(28);if(null===m.fd)throw new Q(8);if(1===(m.flags&2097155))throw new Q(8);if(16384===(m.node.mode&61440))throw new Q(31);if(!m.ab.read)throw new Q(28);var w="undefined"!==typeof p;if(!w)p=m.position;else if(!m.seekable)throw new Q(70);var h=m.ab.read(m,r,l,t,p);w||(m.position+=h);var n=h;if(0>n){var y=-1;break a}a+=n;if(n<k)break}y=
a}D[d>>2]=y;return 0}catch(B){return"undefined"!==typeof Fc&&B instanceof Q||A(B),B.mb}}
function Ke(a,b,c,d,f){if(x)return T(9,1,a,b,c,d,f);try{var g=Ic(a);a=4294967296*c+(b>>>0);if(-9007199254740992>=a||9007199254740992<=a)return-61;uc(g,a,d);xa=[g.position>>>0,(E=g.position,1<=+Math.abs(E)?0<E?(Math.min(+Math.floor(E/4294967296),4294967295)|0)>>>0:~~+Math.ceil((E-+(~~E>>>0))/4294967296)>>>0:0)];D[f>>2]=xa[0];D[f+4>>2]=xa[1];g.Xb&&0===a&&0===d&&(g.Xb=null);return 0}catch(k){return"undefined"!==typeof Fc&&k instanceof Q||A(k),k.mb}}
function Le(a,b,c,d){if(x)return T(10,1,a,b,c,d);try{a:{for(var f=Ic(a),g=a=0;g<c;g++){var k=vc(f,C,D[b+8*g>>2],D[b+(8*g+4)>>2],void 0);if(0>k){var m=-1;break a}a+=k}m=a}D[d>>2]=m;return 0}catch(l){return"undefined"!==typeof Fc&&l instanceof Q||A(l),l.mb}}function Me(a,b,c,d){for(var f=0;f<a;f++){var g=X[c](),k=g&&ye(d);g?(g.name=k,d[k]=g):Be||(Be=1282);D[b+4*f>>2]=k}}
function Ne(a,b,c,d){this.id=a;this.y=this.x=0;this.Wb=!1;this.Gc=this.Fc=0;this.width=b;this.height=c;this.Ec=b;this.Dc=c;this.title=d;this.attributes=Oe;this.buttons=0;this.keys=[];this.Rb=[];this.ec=this.pc=this.Sb=this.Cc=this.Hb=this.hc=this.wc=this.lc=this.Ob=this.title=null}
var Y=null,Z=null,Oe=null,Pe={131073:0,131074:0,131075:1,131076:1,131077:1,135169:8,135170:8,135171:8,135172:8,135173:24,135174:8,135175:0,135176:0,135177:0,135178:0,135179:0,135180:0,135181:0,135182:0,135183:0,139265:196609,139266:1,139267:0,139268:0,139269:0,139270:0,139271:0,139272:0};
function Qe(a){switch(a){case 32:return 32;case 222:return 39;case 188:return 44;case 173:return 45;case 189:return 45;case 190:return 46;case 191:return 47;case 48:return 48;case 49:return 49;case 50:return 50;case 51:return 51;case 52:return 52;case 53:return 53;case 54:return 54;case 55:return 55;case 56:return 56;case 57:return 57;case 59:return 59;case 61:return 61;case 187:return 61;case 65:return 65;case 66:return 66;case 67:return 67;case 68:return 68;case 69:return 69;case 70:return 70;case 71:return 71;
case 72:return 72;case 73:return 73;case 74:return 74;case 75:return 75;case 76:return 76;case 77:return 77;case 78:return 78;case 79:return 79;case 80:return 80;case 81:return 81;case 82:return 82;case 83:return 83;case 84:return 84;case 85:return 85;case 86:return 86;case 87:return 87;case 88:return 88;case 89:return 89;case 90:return 90;case 219:return 91;case 220:return 92;case 221:return 93;case 192:return 94;case 27:return 256;case 13:return 257;case 9:return 258;case 8:return 259;case 45:return 260;
case 46:return 261;case 39:return 262;case 37:return 263;case 40:return 264;case 38:return 265;case 33:return 266;case 34:return 267;case 36:return 268;case 35:return 269;case 20:return 280;case 145:return 281;case 144:return 282;case 44:return 283;case 19:return 284;case 112:return 290;case 113:return 291;case 114:return 292;case 115:return 293;case 116:return 294;case 117:return 295;case 118:return 296;case 119:return 297;case 120:return 298;case 121:return 299;case 122:return 300;case 123:return 301;
case 124:return 302;case 125:return 303;case 126:return 304;case 127:return 305;case 128:return 306;case 129:return 307;case 130:return 308;case 131:return 309;case 132:return 310;case 133:return 311;case 134:return 312;case 135:return 313;case 136:return 314;case 96:return 320;case 97:return 321;case 98:return 322;case 99:return 323;case 100:return 324;case 101:return 325;case 102:return 326;case 103:return 327;case 104:return 328;case 105:return 329;case 110:return 330;case 111:return 331;case 106:return 332;
case 109:return 333;case 107:return 334;case 16:return 340;case 17:return 341;case 18:return 342;case 91:return 343;case 93:return 348;default:return-1}}function Re(){var a=Y,b=0;a.keys[340]&&(b|=1);a.keys[341]&&(b|=2);a.keys[342]&&(b|=4);a.keys[343]&&(b|=8);return b}function Se(a){Y&&Y.ec&&!a.ctrlKey&&!a.metaKey&&(a=a.charCode,0==a||0<=a&&31>=a||L.get(Y.ec)(Y.id,a))}
function Te(a,b){if(Y){var c=Qe(a);if(-1!=c){var d=b&&Y.keys[c];Y.keys[c]=b;Y.Rb[a]=b;Y.pc&&(d&&(b=2),L.get(Y.pc)(Y.id,c,a,b,Re()))}}}function Ue(){Ve()}function We(){Ve()}function Xe(a){Te(a.keyCode,1);8!==a.keyCode&&9!==a.keyCode||a.preventDefault()}function Ye(a){Te(a.keyCode,0)}function $e(){if(Y)for(var a=0;a<Y.Rb.length;++a)Y.Rb[a]&&Te(a,0)}function af(a){Y&&(ee(a),a.target==e.canvas&&Y.hc&&L.get(Y.hc)(Y.id,ae,be))}function bf(a){Y&&a.target==e.canvas&&Y.Hb&&L.get(Y.Hb)(Y.id,1)}
function cf(a){Y&&a.target==e.canvas&&Y.Hb&&L.get(Y.Hb)(Y.id,0)}function df(a,b){if(Y&&(ee(a),a.target==e.canvas)){var c=a.button;0<c&&(c=1==c?2:1);if(1==b){Y.buttons|=1<<c;try{a.target.setCapture()}catch(d){}}else Y.buttons&=~(1<<c);Y.wc&&L.get(Y.wc)(Y.id,c,b,Re())}}function ef(a){Y&&df(a,1)}function ff(a){Y&&df(a,0)}
function gf(a){switch(a.type){case "DOMMouseScroll":break;case "mousewheel":break;case "wheel":switch(a.deltaMode){case 0:break;case 1:break;case 2:break;default:throw"unrecognized mouse wheel delta mode: "+a.deltaMode;}break;default:throw"unrecognized mouse wheel event: "+a.type;}if(Y&&Y.Cc&&a.target==e.canvas){if("mousewheel"==a.type){var b=a.wheelDeltaX;var c=a.wheelDeltaY}else b=a.deltaX,c=a.deltaY;L.get(Y.Cc)(Y.id,b,c);a.preventDefault()}}var hf={},jf=null,kf=null;
function Ve(){if(Dd!==kf||!Dd){jf=navigator.getGamepads?navigator.getGamepads():navigator.webkitGetGamepads?navigator.webkitGetGamepads:null;kf=Dd;for(var a=0;a<jf.length;++a){var b=jf[a];if(b){hf[a]||(console.log("glfw joystick connected:",a),hf[a]={id:Da(Nb(b.id)),Id:b.buttons.length,Gd:b.axes.length,buttons:Da(Array(b.buttons.length)),axes:Da(Array(4*b.axes.length))});for(var c=hf[a],d=0;d<b.buttons.length;++d)va(c.buttons+d,b.buttons[d].pressed,"i8");for(d=0;d<b.axes.length;++d)va(c.axes+4*d,
b.axes[d],"float")}else hf[a]&&(console.log("glfw joystick disconnected",a),P(hf[a].id),P(hf[a].buttons),P(hf[a].axes),delete hf[a])}}}
function lf(a){function b(m){var l="/.glfw_dropped_files/"+m.name.replace(/\//g,"_"),t=new FileReader;t.onloadend=function(r){if(2!=t.readyState)++g,console.log("failed to read dropped file: "+m.name+": "+t.error);else{var w=new Uint8Array(r.target.result);var h=h||{};h.flags=h.flags||577;r=Ya(l,h.flags,h.mode);if("string"===typeof w){var n=new Uint8Array(Ga(w)+1);w=Fa(w,n,0,n.length);vc(r,n,0,w,void 0,h.Qc)}else if(ArrayBuffer.isView(w))vc(r,w,0,w.byteLength,void 0,h.Qc);else throw Error("Unsupported data type");
tc(r);if(++g===f){L.get(Y.Sb)(Y.id,f,c);for(h=0;h<d.length;++h)P(d[h]);P(c)}}};t.readAsArrayBuffer(m);var p=Da(Nb(l));d.push(p);va(c+4*k,p,"i8*")}if(Y&&Y.Sb&&a.dataTransfer&&a.dataTransfer.files&&0!=a.dataTransfer.files.length){a.preventDefault();var c=Da(Array(4*a.dataTransfer.files.length)),d=[],f=a.dataTransfer.files.length,g=0;xc("/",".glfw_dropped_files");for(var k=0;k<f;++k)b(a.dataTransfer.files[k]);return!1}}function mf(a){if(Y&&Y.Sb)return a.preventDefault(),!1}
function ub(a){if(x)throw"Internal Error! spawnThread() can only ever be called from main application thread!";var b=O.Uc();if(!b)return 6;if(void 0!==b.gb)throw"Internal error!";if(!a.Jb)throw"Internal error, no pthread ptr!";O.qb.push(b);for(var c=G(512),d=0;128>d;++d)D[c+4*d>>2]=0;var f=a.sb+a.zb;d=O.jb[a.Jb]={worker:b,sb:a.sb,zb:a.zb,Qb:a.Qb,kb:a.Jb};var g=d.kb>>2;Atomics.store(J,g+16,a.detached);Atomics.store(J,g+25,c);Atomics.store(J,g+10,d.kb);Atomics.store(J,g+20,a.zb);Atomics.store(J,g+19,
f);Atomics.store(J,g+26,a.zb);Atomics.store(J,g+28,f);Atomics.store(J,g+29,a.detached);c=nf()+40;Atomics.store(J,g+43,c);b.gb=d;var k={cmd:"run",start_routine:a.ud,arg:a.ub,threadInfoStruct:a.Jb,stackBase:a.sb,stackSize:a.zb};b.Db=function(){k.time=performance.now();b.postMessage(k,a.Cd)};b.loaded&&(b.Db(),delete b.Db);return 0}function of(a){return 0===a%4&&(0!==a%100||0===a%400)}function pf(a,b){for(var c=0,d=0;d<=b;c+=a[d++]);return c}
var qf=[31,29,31,30,31,30,31,31,30,31,30,31],rf=[31,28,31,30,31,30,31,31,30,31,30,31];function sf(a,b){for(a=new Date(a.getTime());0<b;){var c=a.getMonth(),d=(of(a.getFullYear())?qf:rf)[c];if(b>d-a.getDate())b-=d-a.getDate()+1,a.setDate(1),11>c?a.setMonth(c+1):(a.setMonth(0),a.setFullYear(a.getFullYear()+1));else{a.setDate(a.getDate()+b);break}}return a}
function tf(a,b,c,d){function f(h,n,y){for(h="number"===typeof h?h.toString():h||"";h.length<n;)h=y[0]+h;return h}function g(h,n){return f(h,n,"0")}function k(h,n){function y(K){return 0>K?-1:0<K?1:0}var B;0===(B=y(h.getFullYear()-n.getFullYear()))&&0===(B=y(h.getMonth()-n.getMonth()))&&(B=y(h.getDate()-n.getDate()));return B}function m(h){switch(h.getDay()){case 0:return new Date(h.getFullYear()-1,11,29);case 1:return h;case 2:return new Date(h.getFullYear(),0,3);case 3:return new Date(h.getFullYear(),
0,2);case 4:return new Date(h.getFullYear(),0,1);case 5:return new Date(h.getFullYear()-1,11,31);case 6:return new Date(h.getFullYear()-1,11,30)}}function l(h){h=sf(new Date(h.cb+1900,0,1),h.Nb);var n=new Date(h.getFullYear()+1,0,4),y=m(new Date(h.getFullYear(),0,4));n=m(n);return 0>=k(y,h)?0>=k(n,h)?h.getFullYear()+1:h.getFullYear():h.getFullYear()-1}var t=D[d+40>>2];d={Ad:D[d>>2],zd:D[d+4>>2],Lb:D[d+8>>2],Eb:D[d+12>>2],Ab:D[d+16>>2],cb:D[d+20>>2],Mb:D[d+24>>2],Nb:D[d+28>>2],ie:D[d+32>>2],yd:D[d+
36>>2],Bd:t?I(t):""};c=I(c);t={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S","%Ec":"%c","%EC":"%C","%Ex":"%m/%d/%y","%EX":"%H:%M:%S","%Ey":"%y","%EY":"%Y","%Od":"%d","%Oe":"%e","%OH":"%H","%OI":"%I","%Om":"%m","%OM":"%M","%OS":"%S","%Ou":"%u","%OU":"%U","%OV":"%V","%Ow":"%w","%OW":"%W","%Oy":"%y"};for(var p in t)c=c.replace(new RegExp(p,"g"),t[p]);var r="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),
w="January February March April May June July August September October November December".split(" ");t={"%a":function(h){return r[h.Mb].substring(0,3)},"%A":function(h){return r[h.Mb]},"%b":function(h){return w[h.Ab].substring(0,3)},"%B":function(h){return w[h.Ab]},"%C":function(h){return g((h.cb+1900)/100|0,2)},"%d":function(h){return g(h.Eb,2)},"%e":function(h){return f(h.Eb,2," ")},"%g":function(h){return l(h).toString().substring(2)},"%G":function(h){return l(h)},"%H":function(h){return g(h.Lb,
2)},"%I":function(h){h=h.Lb;0==h?h=12:12<h&&(h-=12);return g(h,2)},"%j":function(h){return g(h.Eb+pf(of(h.cb+1900)?qf:rf,h.Ab-1),3)},"%m":function(h){return g(h.Ab+1,2)},"%M":function(h){return g(h.zd,2)},"%n":function(){return"\n"},"%p":function(h){return 0<=h.Lb&&12>h.Lb?"AM":"PM"},"%S":function(h){return g(h.Ad,2)},"%t":function(){return"\t"},"%u":function(h){return h.Mb||7},"%U":function(h){var n=new Date(h.cb+1900,0,1),y=0===n.getDay()?n:sf(n,7-n.getDay());h=new Date(h.cb+1900,h.Ab,h.Eb);return 0>
k(y,h)?g(Math.ceil((31-y.getDate()+(pf(of(h.getFullYear())?qf:rf,h.getMonth()-1)-31)+h.getDate())/7),2):0===k(y,n)?"01":"00"},"%V":function(h){var n=new Date(h.cb+1901,0,4),y=m(new Date(h.cb+1900,0,4));n=m(n);var B=sf(new Date(h.cb+1900,0,1),h.Nb);return 0>k(B,y)?"53":0>=k(n,B)?"01":g(Math.ceil((y.getFullYear()<h.cb+1900?h.Nb+32-y.getDate():h.Nb+1-y.getDate())/7),2)},"%w":function(h){return h.Mb},"%W":function(h){var n=new Date(h.cb,0,1),y=1===n.getDay()?n:sf(n,0===n.getDay()?1:7-n.getDay()+1);h=
new Date(h.cb+1900,h.Ab,h.Eb);return 0>k(y,h)?g(Math.ceil((31-y.getDate()+(pf(of(h.getFullYear())?qf:rf,h.getMonth()-1)-31)+h.getDate())/7),2):0===k(y,n)?"01":"00"},"%y":function(h){return(h.cb+1900).toString().substring(2)},"%Y":function(h){return h.cb+1900},"%z":function(h){h=h.yd;var n=0<=h;h=Math.abs(h)/60;return(n?"+":"-")+String("0000"+(h/60*100+h%60)).slice(-4)},"%Z":function(h){return h.Bd},"%%":function(){return"%"}};for(p in t)0<=c.indexOf(p)&&(c=c.replace(new RegExp(p,"g"),t[p](d)));p=
Nb(c,!1);if(p.length>b)return 0;C.set(p,a);return p.length-1}x||O.Zc();function fc(a,b,c,d){a||(a=this);this.parent=a;this.nb=a.nb;this.Cb=null;this.id=Xb++;this.name=b;this.mode=c;this.$a={};this.ab={};this.rdev=d}
Object.defineProperties(fc.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}},dd:{get:function(){return 16384===(this.mode&61440)}},cd:{get:function(){return 8192===(this.mode&61440)}}});Wa();Yb=Array(4096);nc(R,"/");S("/tmp");S("/home");S("/home/web_user");
(function(){S("/dev");Lb(259,{read:function(){return 0},write:function(b,c,d,f){return f}});pc("/dev/null",259);Kb(1280,Ob);Kb(1536,Pb);pc("/dev/tty",1280);pc("/dev/tty1",1536);var a=Hb();N("/dev","random",a);N("/dev","urandom",a);S("/dev/shm");S("/dev/shm/tmp")})();
(function(){S("/proc");var a=S("/proc/self");S("/proc/self/fd");nc({nb:function(){var b=Rb(a,"fd",16895,73);b.$a={lookup:function(c,d){var f=Wb[+d];if(!f)throw new Q(8);c={parent:null,nb:{vc:"fake"},$a:{readlink:function(){return f.path}}};return c.parent=c}};return b}},"/proc/self/fd")})();e.FS_createPath=xc;e.FS_createDataFile=zc;e.FS_createPreloadedFile=Cc;e.FS_createLazyFile=Bc;e.FS_createDevice=N;e.FS_unlink=qc;for(var uf=Array(256),vf=0;256>vf;++vf)uf[vf]=String.fromCharCode(vf);Mc=uf;
Tc=e.BindingError=Sc("BindingError");Uc=e.InternalError=Sc("InternalError");e.count_emval_handles=function(){for(var a=0,b=5;b<W.length;++b)void 0!==W[b]&&++a;return a};e.get_first_emval=function(){for(var a=5;a<W.length;++a)if(void 0!==W[a])return W[a];return null};id=e.UnboundTypeError=Sc("UnboundTypeError");e.requestFullscreen=function(a,b){Wd(a,b)};e.requestAnimationFrame=function(a){vd(a)};e.setCanvasSize=function(a,b,c){ge(a,b,c)};e.pauseMainLoop=function(){sd=null;yd++};
e.resumeMainLoop=function(){yd++;var a=od,b=pd,c=qd;qd=null;xd(c,0,!1,zd,!0);nd(a,b);sd()};e.getUserMedia=function(){window.getUserMedia||(window.getUserMedia=navigator.getUserMedia||navigator.mozGetUserMedia);window.getUserMedia(void 0)};e.createContext=function(a,b,c,d){return Od(a,b,c,d)};var X,wf=[null,function(a,b){if(x)return T(1,1,a,b)},Jc,Kc,qe,Ge,He,Ie,Je,Ke,Le];function Nb(a,b){var c=Array(Ga(a)+1);a=Fa(a,c,0,c.length);b&&(c.length=a);return c}
var zf={b:function(a,b,c,d){A("Assertion failed: "+I(a)+", at: "+[b?I(b):"unknown filename",c,d?I(d):"unknown function"])},c:function(a){return G(a+16)+16},d:function(a,b,c){(new Bb(a)).Xc(b,c);Cb++;throw a;},Z:Jc,_:Kc,aa:function(a,b,c,d,f){var g=Lc(c);b=U(b);Wc(a,{name:b,fromWireType:function(k){return!!k},toWireType:function(k,m){return m?d:f},argPackAdvance:8,readValueFromPointer:function(k){if(1===c)var m=C;else if(2===c)m=wa;else if(4===c)m=D;else throw new TypeError("Unknown boolean type size: "+
b);return this.fromWireType(m[k>>g])},ob:null})},$:function(a,b){b=U(b);Wc(a,{name:b,fromWireType:function(c){var d=W[c].value;4<c&&0===--W[c].jd&&(W[c]=void 0,Xc.push(c));return d},toWireType:function(c,d){return Yc(d)},argPackAdvance:8,readValueFromPointer:Zc,ob:null})},A:function(a,b,c){c=Lc(c);b=U(b);Wc(a,{name:b,fromWireType:function(d){return d},toWireType:function(d,f){if("number"!==typeof f&&"boolean"!==typeof f)throw new TypeError('Cannot convert "'+$c(f)+'" to '+this.name);return f},argPackAdvance:8,
readValueFromPointer:ad(b,c),ob:null})},q:function(a,b,c,d,f,g){var k=fd(b,c);a=U(a);f=hd(d,f);ed(a,function(){ld("Cannot call "+a+" due to unbound types",k)},b-1);Vc(k,function(m){var l=[m[0],null].concat(m.slice(1)),t=m=a,p=f,r=l.length;2>r&&V("argTypes array size mismatch! Must at least get return value and 'this' types!");for(var w=null!==l[1]&&!1,h=!1,n=1;n<l.length;++n)if(null!==l[n]&&void 0===l[n].ob){h=!0;break}var y="void"!==l[0].name,B="",K="";for(n=0;n<r-2;++n)B+=(0!==n?", ":"")+"arg"+
n,K+=(0!==n?", ":"")+"arg"+n+"Wired";t="return function "+Qc(t)+"("+B+") {\nif (arguments.length !== "+(r-2)+") {\nthrowBindingError('function "+t+" called with ' + arguments.length + ' arguments, expected "+(r-2)+" args!');\n}\n";h&&(t+="var destructors = [];\n");var da=h?"destructors":"null";B="throwBindingError invoker fn runDestructors retType classParam".split(" ");p=[V,p,g,cd,l[0],l[1]];w&&(t+="var thisWired = classParam.toWireType("+da+", this);\n");for(n=0;n<r-2;++n)t+="var arg"+n+"Wired = argType"+
n+".toWireType("+da+", arg"+n+"); // "+l[n+2].name+"\n",B.push("argType"+n),p.push(l[n+2]);w&&(K="thisWired"+(0<K.length?", ":"")+K);t+=(y?"var rv = ":"")+"invoker(fn"+(0<K.length?", ":"")+K+");\n";if(h)t+="runDestructors(destructors);\n";else for(n=w?1:2;n<l.length;++n)r=1===n?"thisWired":"arg"+(n-2)+"Wired",null!==l[n].ob&&(t+=r+"_dtor("+r+"); // "+l[n].name+"\n",B.push(r+"_dtor"),p.push(l[n].ob));y&&(t+="var ret = retType.fromWireType(rv);\nreturn ret;\n");B.push(t+"}\n");l=bd(B).apply(null,p);
n=b-1;if(!e.hasOwnProperty(m))throw new Uc("Replacing nonexistant public symbol");void 0!==e[m].ib&&void 0!==n?e[m].ib[n]=l:(e[m]=l,e[m].Nc=n);return[]})},g:function(a,b,c,d,f){function g(t){return t}b=U(b);-1===f&&(f=4294967295);var k=Lc(c);if(0===d){var m=32-8*c;g=function(t){return t<<m>>>m}}var l=-1!=b.indexOf("unsigned");Wc(a,{name:b,fromWireType:g,toWireType:function(t,p){if("number"!==typeof p&&"boolean"!==typeof p)throw new TypeError('Cannot convert "'+$c(p)+'" to '+this.name);if(p<d||p>f)throw new TypeError('Passing a number "'+
$c(p)+'" from JS side to C/C++ side to an argument of type "'+b+'", which is outside the valid range ['+d+", "+f+"]!");return l?p>>>0:p|0},argPackAdvance:8,readValueFromPointer:md(b,k,0!==d),ob:null})},f:function(a,b,c){function d(g){g>>=2;return new f(ia,J[g+1],J[g])}var f=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array][b];c=U(c);Wc(a,{name:c,fromWireType:d,argPackAdvance:8,readValueFromPointer:d},{Wc:!0})},B:function(a,b){b=U(b);var c="std::string"===
b;Wc(a,{name:b,fromWireType:function(d){var f=J[d>>2];if(c)for(var g=d+4,k=0;k<=f;++k){var m=d+4+k;if(k==f||0==H[m]){g=I(g,m-g);if(void 0===l)var l=g;else l+=String.fromCharCode(0),l+=g;g=m+1}}else{l=Array(f);for(k=0;k<f;++k)l[k]=String.fromCharCode(H[d+4+k]);l=l.join("")}P(d);return l},toWireType:function(d,f){f instanceof ArrayBuffer&&(f=new Uint8Array(f));var g="string"===typeof f;g||f instanceof Uint8Array||f instanceof Uint8ClampedArray||f instanceof Int8Array||V("Cannot pass non-string to std::string");
var k=(c&&g?function(){return Ga(f)}:function(){return f.length})(),m=G(4+k+1);J[m>>2]=k;if(c&&g)Fa(f,H,m+4,k+1);else if(g)for(g=0;g<k;++g){var l=f.charCodeAt(g);255<l&&(P(m),V("String has UTF-16 code units that do not fit in 8 bits"));H[m+4+g]=l}else for(g=0;g<k;++g)H[m+4+g]=f[g];null!==d&&d.push(P,m);return m},argPackAdvance:8,readValueFromPointer:Zc,ob:function(d){P(d)}})},r:function(a,b,c){c=U(c);if(2===b){var d=Ha;var f=Ia;var g=Ja;var k=function(){return Na};var m=1}else 4===b&&(d=Ka,f=La,g=
Ma,k=function(){return J},m=2);Wc(a,{name:c,fromWireType:function(l){for(var t=J[l>>2],p=k(),r,w=l+4,h=0;h<=t;++h){var n=l+4+h*b;if(h==t||0==p[n>>m])w=d(w,n-w),void 0===r?r=w:(r+=String.fromCharCode(0),r+=w),w=n+b}P(l);return r},toWireType:function(l,t){"string"!==typeof t&&V("Cannot pass non-string to C++ string type "+c);var p=g(t),r=G(4+p+b);J[r>>2]=p>>m;f(t,r+4,p+b);null!==l&&l.push(P,r);return r},argPackAdvance:8,readValueFromPointer:Zc,ob:function(l){P(l)}})},ba:function(a,b){b=U(b);Wc(a,{Ud:!0,
name:b,argPackAdvance:0,fromWireType:function(){},toWireType:function(){}})},W:function(a,b){if(a==b)postMessage({cmd:"processQueuedMainThreadWork"});else if(x)postMessage({targetThread:a,cmd:"processThreadQueue"});else{a=(a=O.jb[a])&&a.worker;if(!a)return;a.postMessage({cmd:"processThreadQueue"})}return 1},v:function(){A()},i:function(a,b,c){le.length=0;var d;for(c>>=2;d=H[b++];)(d=105>d)&&c&1&&c++,le.push(d?za[c++>>1]:D[c]),++c;return lb[a].apply(null,le)},ia:function(){sd=null;yd++;qd=null},S:function(){v||
u||sa("Blocking on the main thread is very dangerous, see https://emscripten.org/docs/porting/pthreads.html#blocking-on-the-main-browser-thread")},x:function(){},l:function(a,b,c){if(0>=a||a>C.length||a&1)return-28;if(fa){if(Atomics.load(D,a>>2)!=b)return-6;var d=performance.now();c=d+c;for(Atomics.exchange(D,nb>>2,a);;){d=performance.now();if(d>c)return Atomics.exchange(D,nb>>2,0),-73;d=Atomics.exchange(D,nb>>2,0);if(0==d)break;tb();if(Atomics.load(D,a>>2)!=b)return-6;Atomics.exchange(D,nb>>2,a)}return 0}a=
Atomics.wait(D,a>>2,b,c);if("timed-out"===a)return-73;if("not-equal"===a)return-6;if("ok"===a)return 0;throw"Atomics.wait returned an unexpected value "+a;},k:mb,n:Ab,O:function(a,b,c){H.copyWithin(a,b,b+c)},T:function(a,b,c){ke.length=b;c>>=3;for(var d=0;d<b;d++)ke[d]=za[c+d];return(0>a?lb[-a-1]:wf[a]).apply(null,ke)},j:function(){A("OOM")},U:function(a,b,c){return ne(a)?oe(a,b,c):qe(a,b,c)},w:function(){},ka:function(a,b,c,d){xd(function(){L.get(a)(b)},c,d,b)},V:function(a,b){b>>=2;b={alpha:!!D[b],
depth:!!D[b+1],stencil:!!D[b+2],antialias:!!D[b+3],premultipliedAlpha:!!D[b+4],preserveDrawingBuffer:!!D[b+5],powerPreference:Ce[D[b+6]],failIfMajorPerformanceCaveat:!!D[b+7],sc:D[b+8],Yd:D[b+9],ic:D[b+10],Sc:D[b+11],ee:D[b+12],fe:D[b+13]};a=ne(a);return!a||b.Sc?0:Qd(a,b)},Q:Ge,R:He,y:Ie,Y:Je,L:Ke,X:Le,E:function(a,b){X.attachShader(te[a],ve[b])},e:function(a,b){35051==a?X.Md=b:35052==a&&(X.Nd=b);X.bindBuffer(a,se[b])},s:function(a){X.bindVertexArray(we[a])},ma:function(a,b){X.blendFunc(a,b)},la:function(a,
b,c,d){X.blendFuncSeparate(a,b,c,d)},h:function(a,b,c,d){c?X.bufferData(a,H,d,c,b):X.bufferData(a,b,d)},u:function(a,b,c,d){X.bufferSubData(a,b,H,d,c)},qa:function(a){X.clear(a)},ra:function(a,b,c,d){X.clearColor(a,b,c,d)},F:function(a){X.compileShader(ve[a])},ha:function(){var a=ye(te),b=X.createProgram();b.name=a;te[a]=b;return a},H:function(a){var b=ye(ve);ve[b]=X.createShader(a);return b},D:function(a){if(a){var b=ve[a];b?(X.deleteShader(b),ve[a]=null):Be||(Be=1281)}},ta:function(a,b,c,d){X.drawArraysInstanced(a,
b,c,d)},na:function(a){X.enable(a)},m:function(a){X.enableVertexAttribArray(a)},p:function(a,b){Me(a,b,"createBuffer",se)},ca:function(a,b){Me(a,b,"createVertexArray",we)},J:function(a,b){b=I(b);var c=0;if("]"==b[b.length-1]){var d=b.lastIndexOf("[");c="]"!=b[d+1]?parseInt(b.slice(d+1)):0;b=b.slice(0,d)}return(a=xe[a]&&xe[a].Jc[b])&&0<=c&&c<a[0]?a[1]+c:-1},ga:function(a){X.linkProgram(te[a]);var b=te[a];a=xe[a]={Jc:{},tc:0,Vd:-1,Wd:-1};for(var c=a.Jc,d=X.getProgramParameter(b,35718),f=0;f<d;++f){var g=
X.getActiveUniform(b,f),k=g.name;a.tc=Math.max(a.tc,k.length+1);"]"==k.slice(-1)&&(k=k.slice(0,k.lastIndexOf("[")));var m=X.getUniformLocation(b,k);if(m){var l=ye(ue);c[k]=[g.size,l];ue[l]=m;for(var t=1;t<g.size;++t)m=X.getUniformLocation(b,k+"["+t+"]"),l=ye(ue),ue[l]=m}}},G:function(a,b,c,d){for(var f="",g=0;g<b;++g){var k=d?D[d+4*g>>2]:-1;f+=I(D[c+4*g>>2],0>k?void 0:k)}X.shaderSource(ve[a],f)},I:function(a,b){X.uniform1f(ue[a],b)},oa:function(a){X.useProgram(te[a])},t:function(a,b){X.vertexAttribDivisor(a,
b)},o:function(a,b,c,d,f,g){X.vertexAttribPointer(a,b,c,!!d,f,g)},K:function(a,b,c,d){X.viewport(a,b,c,d)},ea:function(a,b,c,d){var f;for(f=0;f<Z.length&&null!==Z[f];f++);if(0<f)throw"glfwCreateWindow only supports one window at time currently";var g=f+1;if(0>=a||0>=b)g=0;else{d?Wd():ge(a,b);for(f=0;f<Z.length&&null==Z[f];f++);d=0<Oe[139265];f==Z.length&&(d?e.Bb=Od(e.canvas,!0,!0,{antialias:1<Oe[135181],depth:0<Oe[135173],stencil:0<Oe[135174],alpha:0<Oe[135172]}):Dc());!e.Bb&&d?g=0:(a=new Ne(g,a,
b,c),g-1==Z.length?Z.push(a):Z[g-1]=a,Y=a,g=a.id)}return g},fa:function(){if(Z)return 1;Ab();Oe=Pe;Z=[];Y=null;window.addEventListener("gamepadconnected",Ue,!0);window.addEventListener("gamepaddisconnected",We,!0);window.addEventListener("keydown",Xe,!0);window.addEventListener("keypress",Se,!0);window.addEventListener("keyup",Ye,!0);window.addEventListener("blur",$e,!0);e.canvas.addEventListener("touchmove",af,!0);e.canvas.addEventListener("touchstart",ef,!0);e.canvas.addEventListener("touchcancel",
ff,!0);e.canvas.addEventListener("touchend",ff,!0);e.canvas.addEventListener("mousemove",af,!0);e.canvas.addEventListener("mousedown",ef,!0);e.canvas.addEventListener("mouseup",ff,!0);e.canvas.addEventListener("wheel",gf,!0);e.canvas.addEventListener("mousewheel",gf,!0);e.canvas.addEventListener("mouseenter",bf,!0);e.canvas.addEventListener("mouseleave",cf,!0);e.canvas.addEventListener("drop",lf,!0);e.canvas.addEventListener("dragover",mf,!0);fe.push(function(a,b){if(Y){var c=!0;document.fullscreen||
document.fullScreen||document.mozFullScreen||document.webkitIsFullScreen?(Y.Fc=Y.x,Y.Gc=Y.y,Y.Ec=Y.width,Y.Dc=Y.height,Y.x=Y.y=0,Y.width=screen.width,Y.height=screen.height,Y.Wb=!0):1==Y.Wb?(Y.x=Y.Fc,Y.y=Y.Gc,Y.width=Y.Ec,Y.height=Y.Dc,Y.Wb=!1):Y.width!=a||Y.height!=b?(Y.width=a,Y.height=b):c=!1;c&&(ge(Y.width,Y.height,!0),Y&&Y.Ob&&L.get(Y.Ob)(Y.id,Y.width,Y.height),Y&&Y.lc&&L.get(Y.lc)(Y.id,Y.width,Y.height))}});return 1},da:function(){},sa:function(a,b,c){if(a=0>=a||!Z?null:Z[a-1])Y.id==a.id&&(b==
screen.width&&c==screen.height?Wd():(Xd(),ge(b,c),a.width=b,a.height=c)),a.Ob&&L.get(a.Ob)(a.id,b,c)},pa:function(){},ja:function(){window.removeEventListener("gamepadconnected",Ue,!0);window.removeEventListener("gamepaddisconnected",We,!0);window.removeEventListener("keydown",Xe,!0);window.removeEventListener("keypress",Se,!0);window.removeEventListener("keyup",Ye,!0);window.removeEventListener("blur",$e,!0);e.canvas.removeEventListener("touchmove",af,!0);e.canvas.removeEventListener("touchstart",
ef,!0);e.canvas.removeEventListener("touchcancel",ff,!0);e.canvas.removeEventListener("touchend",ff,!0);e.canvas.removeEventListener("mousemove",af,!0);e.canvas.removeEventListener("mousedown",ef,!0);e.canvas.removeEventListener("mouseup",ff,!0);e.canvas.removeEventListener("wheel",gf,!0);e.canvas.removeEventListener("mousewheel",gf,!0);e.canvas.removeEventListener("mouseenter",bf,!0);e.canvas.removeEventListener("mouseleave",cf,!0);e.canvas.removeEventListener("drop",lf,!0);e.canvas.removeEventListener("dragover",
mf,!0);e.canvas.width=e.canvas.height=1;Y=Z=null},C:function(a,b){Oe[a]=b},N:function(){O.$c()},a:F,z:function(a,b,c,d){if("undefined"===typeof SharedArrayBuffer)return q("Current environment does not support SharedArrayBuffer, pthreads are not available!"),6;if(!a)return q("pthread_create called with a null thread pointer!"),28;var f=[];if(x&&0===f.length)return xf(687865856,a,b,c,d);var g=0,k=0;if(b&&-1!=b){var m=D[b>>2];m+=81920;g=D[b+8>>2];k=0!==D[b+12>>2]}else m=2097152;(b=0==g)?g=yf(16,m):(g-=
m,assert(0<g));for(var l=G(228),t=0;57>t;++t)J[(l>>2)+t]=0;D[a>>2]=l;D[l+12>>2]=l;a=l+152;D[a>>2]=a;c={sb:g,zb:m,Qb:b,detached:k,ud:c,Jb:l,ub:d,Cd:f};return x?(c.Jd="spawnThread",postMessage(c,f),0):ub(c)},M:function(){},P:function(a,b,c,d){return tf(a,b,c,d)}};
(function(){function a(f,g){e.asm=f.exports;L=e.asm.Aa;Ra.unshift(e.asm.ua);O.ac.push(e.asm.za);Aa=g;if(!x){var k=O.lb.length;O.lb.forEach(function(m){O.qc(m,function(){--k||eb("wasm-instantiate")})})}}function b(f){a(f.instance,f.module)}function c(f){return jb().then(function(g){return WebAssembly.instantiate(g,d)}).then(f,function(g){q("failed to asynchronously prepare wasm: "+g);A(g)})}var d={a:zf};x||db("wasm-instantiate");if(e.instantiateWasm)try{return e.instantiateWasm(d,a)}catch(f){return q("Module.instantiateWasm callback failed with error: "+
f),!1}(function(){return ua||"function"!==typeof WebAssembly.instantiateStreaming||hb()||fb("file://")||"function"!==typeof fetch?c(b):fetch(gb,{credentials:"same-origin"}).then(function(f){return WebAssembly.instantiateStreaming(f,d).then(b,function(g){q("wasm streaming compile failed: "+g);q("falling back to ArrayBuffer instantiation");return c(b)})})})();return{}})();e.___wasm_call_ctors=function(){return(e.___wasm_call_ctors=e.asm.ua).apply(null,arguments)};
e._setValues=function(){return(e._setValues=e.asm.va).apply(null,arguments)};var G=e._malloc=function(){return(G=e._malloc=e.asm.wa).apply(null,arguments)};e._main=function(){return(e._main=e.asm.xa).apply(null,arguments)};e._restart=function(){return(e._restart=e.asm.ya).apply(null,arguments)};e._emscripten_tls_init=function(){return(e._emscripten_tls_init=e.asm.za).apply(null,arguments)};var kd=e.___getTypeName=function(){return(kd=e.___getTypeName=e.asm.Ba).apply(null,arguments)};
e.___embind_register_native_and_builtin_types=function(){return(e.___embind_register_native_and_builtin_types=e.asm.Ca).apply(null,arguments)};
var P=e._free=function(){return(P=e._free=e.asm.Da).apply(null,arguments)},nf=e._emscripten_get_global_libc=function(){return(nf=e._emscripten_get_global_libc=e.asm.Ea).apply(null,arguments)},qb=e._pthread_self=function(){return(qb=e._pthread_self=e.asm.Fa).apply(null,arguments)},rb=e.___pthread_tsd_run_dtors=function(){return(rb=e.___pthread_tsd_run_dtors=e.asm.Ga).apply(null,arguments)};
e._emscripten_current_thread_process_queued_calls=function(){return(e._emscripten_current_thread_process_queued_calls=e.asm.Ha).apply(null,arguments)};
var pb=e._emscripten_register_main_browser_thread_id=function(){return(pb=e._emscripten_register_main_browser_thread_id=e.asm.Ia).apply(null,arguments)},kb=e.__emscripten_do_dispatch_to_thread=function(){return(kb=e.__emscripten_do_dispatch_to_thread=e.asm.Ja).apply(null,arguments)},xf=e._emscripten_sync_run_in_main_thread_4=function(){return(xf=e._emscripten_sync_run_in_main_thread_4=e.asm.Ka).apply(null,arguments)},tb=e._emscripten_main_thread_process_queued_calls=function(){return(tb=e._emscripten_main_thread_process_queued_calls=
e.asm.La).apply(null,arguments)},je=e._emscripten_run_in_main_runtime_thread_js=function(){return(je=e._emscripten_run_in_main_runtime_thread_js=e.asm.Ma).apply(null,arguments)},pe=e.__emscripten_call_on_thread=function(){return(pe=e.__emscripten_call_on_thread=e.asm.Na).apply(null,arguments)},ob=e.__emscripten_thread_init=function(){return(ob=e.__emscripten_thread_init=e.asm.Oa).apply(null,arguments)},he=e.stackSave=function(){return(he=e.stackSave=e.asm.Pa).apply(null,arguments)},xb=e.stackRestore=
function(){return(xb=e.stackRestore=e.asm.Qa).apply(null,arguments)},ie=e.stackAlloc=function(){return(ie=e.stackAlloc=e.asm.Ra).apply(null,arguments)},wb=e._emscripten_stack_set_limits=function(){return(wb=e._emscripten_stack_set_limits=e.asm.Sa).apply(null,arguments)},yf=e._memalign=function(){return(yf=e._memalign=e.asm.Ta).apply(null,arguments)};e.dynCall_jiji=function(){return(e.dynCall_jiji=e.asm.Ua).apply(null,arguments)};
e.dynCall_viijii=function(){return(e.dynCall_viijii=e.asm.Va).apply(null,arguments)};e.dynCall_iiiiiijj=function(){return(e.dynCall_iiiiiijj=e.asm.Wa).apply(null,arguments)};e.dynCall_iiiiij=function(){return(e.dynCall_iiiiij=e.asm.Xa).apply(null,arguments)};e.dynCall_iiiiijj=function(){return(e.dynCall_iiiiijj=e.asm.Ya).apply(null,arguments)};var sb=e.__emscripten_allow_main_runtime_queued_calls=16030584,nb=e.__emscripten_main_thread_futex=20034388;e.addRunDependency=db;e.removeRunDependency=eb;
e.FS_createPath=xc;e.FS_createDataFile=zc;e.FS_createPreloadedFile=Cc;e.FS_createLazyFile=Bc;e.FS_createDevice=N;e.FS_unlink=qc;e.PThread=O;e.PThread=O;e.wasmMemory=F;e.ExitStatus=pa;var Af;function pa(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}cb=function Bf(){Af||Cf();Af||(cb=Bf)};
function Cf(){function a(){if(!Af&&(Af=!0,e.calledRun=!0,!Ba)){Ua();x||(Zb=!1,Za(Sa));if(e.onRuntimeInitialized)e.onRuntimeInitialized();if(Df){var b=e._main;try{var c=b(0,0);vb(c,!0)}catch(d){d instanceof pa||"unwind"==d||((b=d)&&"object"===typeof d&&d.stack&&(b=[d,d.stack]),q("exception thrown: "+b),ea(1,d))}finally{}}if(!x){if(e.postRun)for("function"==typeof e.postRun&&(e.postRun=[e.postRun]);e.postRun.length;)b=e.postRun.shift(),Ta.unshift(b);Za(Ta)}}}if(!(0<ab))if(x)Ua(),postMessage({cmd:"loaded"});
else{if(!x){if(e.preRun)for("function"==typeof e.preRun&&(e.preRun=[e.preRun]);e.preRun.length;)$a();Za(Qa)}0<ab||(e.setStatus?(e.setStatus("Running..."),setTimeout(function(){setTimeout(function(){e.setStatus("")},1);a()},1)):a())}}e.run=Cf;function vb(a,b){Ca=a;if(!b||!zb()||0!==a){if(!b&&x)throw postMessage({cmd:"exitProcess",returnCode:a}),new pa(a);if(!zb()){O.vd();if(e.onExit)e.onExit(a);Ba=!0}ea(a,new pa(a))}}if(e.preInit)for("function"==typeof e.preInit&&(e.preInit=[e.preInit]);0<e.preInit.length;)e.preInit.pop()();
var Df=!0;e.noInitialRun&&(Df=!1);x&&(noExitRuntime=!1,O.ad());Cf();
