
var e;e||(e=typeof Module !== 'undefined' ? Module : {});e.Sb||(e.Sb=0);e.Sb++;
(function(a){function b(m,n,q){var r=new XMLHttpRequest;r.open("GET",m,!0);r.responseType="arraybuffer";r.onprogress=function(v){var k=n;v.total&&(k=v.total);if(v.loaded){r.cb?e.ub[m].loaded=v.loaded:(r.cb=!0,e.ub||(e.ub={}),e.ub[m]={loaded:v.loaded,total:k});var p=k=v=0,x;for(x in e.ub){var A=e.ub[x];v+=A.total;k+=A.loaded;p++}v=Math.ceil(v*e.Sb/p);e.setStatus&&e.setStatus("Downloading data... ("+k+"/"+v+")")}else!e.ub&&e.setStatus&&e.setStatus("Downloading data...")};r.onerror=function(){throw Error("NetworkError for: "+
m);};r.onload=function(){if(200==r.status||304==r.status||206==r.status||0==r.status&&r.response)q(r.response);else throw Error(r.statusText+" : "+r.responseURL);};r.send(null)}function c(m){console.error("package error:",m)}function d(){function m(v,k,p){this.start=v;this.Ob=k;this.audio=p}function n(v){if(!v)throw"Loading data file failed."+Error().stack;if(!(v instanceof ArrayBuffer))throw"bad input to processPackageData"+Error().stack;v=new Uint8Array(v);m.prototype.Mc=v;v=a.files;for(var k=0;k<
v.length;++k)m.prototype.cb[v[k].filename].onload();e.removeRunDependency("datafile_index.data")}e.FS_createPath("/","src",!0,!0);e.FS_createPath("/src","shaders",!0,!0);m.prototype={cb:{},open:function(v,k){this.name=k;this.cb[k]=this;e.addRunDependency("fp "+this.name)},send:function(){},onload:function(){this.Jc(this.Mc.subarray(this.start,this.Ob))},Jc:function(v){e.FS_createDataFile(this.name,null,v,!0,!0,!0);e.removeRunDependency("fp "+this.name);this.cb[this.name]=null}};for(var q=a.files,
r=0;r<q.length;++r)(new m(q[r].start,q[r].end,q[r].audio)).open("GET",q[r].filename);e.addRunDependency("datafile_index.data");e.zc||(e.zc={});e.zc["index.data"]={Rd:!1};l?(n(l),l=null):h=n}if("object"===typeof window)window.encodeURIComponent(window.location.pathname.toString().substring(0,window.location.pathname.toString().lastIndexOf("/"))+"/");else if("undefined"!==typeof location)encodeURIComponent(location.pathname.toString().substring(0,location.pathname.toString().lastIndexOf("/"))+"/");
else throw"using preloaded data can only be done on a web page or in a web worker";"function"!==typeof e.locateFilePackage||e.locateFile||(e.locateFile=e.locateFilePackage,t("warning: you defined Module.locateFilePackage, that has been renamed to Module.locateFile (using your locateFilePackage for now)"));var f=e.locateFile?e.locateFile("index.data",""):"index.data",g=a.remote_package_size,h=null,l=e.getPreloadedPackage?e.getPreloadedPackage(f,g):null;l||b(f,g,function(m){h?(h(m),h=null):l=m},c);
e.calledRun?d():(e.preRun||(e.preRun=[]),e.preRun.push(d))})({files:[{filename:"/src/shaders/tri.vert",start:0,end:416,audio:0},{filename:"/src/shaders/lines.frag",start:416,end:416,audio:0},{filename:"/src/shaders/tri.frag",start:416,end:1446,audio:0}],remote_package_size:1446,package_uuid:"b49f3796-4081-4ec2-8969-92e30423d502"});var aa={},ba;for(ba in e)e.hasOwnProperty(ba)&&(aa[ba]=e[ba]);var ca="./this.program";function da(a,b){throw b;}var ea=!1,u=!1,w=!1,fa=!1;ea="object"===typeof window;
u="function"===typeof importScripts;w="object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node;fa=!ea&&!w&&!u;var z=e.ENVIRONMENT_IS_PTHREAD||!1;z&&(ha=e.buffer);var _scriptDir="undefined"!==typeof document&&document.currentScript?document.currentScript.src:void 0;u?_scriptDir=self.location.href:w&&(_scriptDir=__filename);var B="";function ia(a){return e.locateFile?e.locateFile(a,B):B+a}var ja,ka,la,ma,na;
if(w){B=u?require("path").dirname(B)+"/":__dirname+"/";ja=function(a,b){ma||(ma=require("fs"));na||(na=require("path"));a=na.normalize(a);return ma.readFileSync(a,b?null:"utf8")};la=function(a){a=ja(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a};1<process.argv.length&&(ca=process.argv[1].replace(/\\/g,"/"));process.argv.slice(2);"undefined"!==typeof module&&(module.exports=e);process.on("uncaughtException",function(a){if(!(a instanceof oa))throw a;});process.on("unhandledRejection",
C);da=function(a){process.exit(a)};e.inspect=function(){return"[Emscripten Module object]"};var pa;try{pa=require("worker_threads")}catch(a){throw console.error('The "worker_threads" module is not supported in this node.js build - perhaps a newer version is needed?'),a;}global.Worker=pa.Worker}else if(fa)"undefined"!=typeof read&&(ja=function(a){return read(a)}),la=function(a){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(a));a=read(a,"binary");assert("object"===typeof a);return a},
"function"===typeof quit&&(da=function(a){quit(a)}),"undefined"!==typeof print&&("undefined"===typeof console&&(console={}),console.log=print,console.warn=console.error="undefined"!==typeof printErr?printErr:print);else if(ea||u)u?B=self.location.href:"undefined"!==typeof document&&document.currentScript&&(B=document.currentScript.src),B=0!==B.indexOf("blob:")?B.substr(0,B.lastIndexOf("/")+1):"",w?(ja=function(a,b){ma||(ma=require("fs"));na||(na=require("path"));a=na.normalize(a);return ma.readFileSync(a,
b?null:"utf8")},la=function(a){a=ja(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a}):(ja=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},u&&(la=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),ka=function(a,b,c){var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=function(){200==d.status||0==d.status&&d.response?b(d.response):
c()};d.onerror=c;d.send(null)});w&&"undefined"===typeof performance&&(global.performance=require("perf_hooks").performance);var qa=e.print||console.log.bind(console),t=e.printErr||console.warn.bind(console);for(ba in aa)aa.hasOwnProperty(ba)&&(e[ba]=aa[ba]);aa=null;e.thisProgram&&(ca=e.thisProgram);e.quit&&(da=e.quit);function ra(a){sa||(sa={});sa[a]||(sa[a]=1,t(a))}var sa,ta;e.wasmBinary&&(ta=e.wasmBinary);var noExitRuntime=e.noExitRuntime||!0;"object"!==typeof WebAssembly&&C("no native wasm support detected");
function ua(a,b,c){c=c||"i8";"*"===c.charAt(c.length-1)&&(c="i32");switch(c){case "i1":D[a>>0]=b;break;case "i8":D[a>>0]=b;break;case "i16":va[a>>1]=b;break;case "i32":E[a>>2]=b;break;case "i64":wa=[b>>>0,(F=b,1<=+Math.abs(F)?0<F?(Math.min(+Math.floor(F/4294967296),4294967295)|0)>>>0:~~+Math.ceil((F-+(~~F>>>0))/4294967296)>>>0:0)];E[a>>2]=wa[0];E[a+4>>2]=wa[1];break;case "float":xa[a>>2]=b;break;case "double":ya[a>>3]=b;break;default:C("invalid type for setValue: "+c)}}var za,Aa,Ba=!1,Ca;
function assert(a,b){a||C("Assertion failed: "+b)}function Da(a){var b=G(a.length);a.subarray||a.slice?I.set(a,b):I.set(new Uint8Array(a),b);return b}
function Ea(a,b,c){c=b+c;for(var d="";!(b>=c);){var f=a[b++];if(!f)break;if(f&128){var g=a[b++]&63;if(192==(f&224))d+=String.fromCharCode((f&31)<<6|g);else{var h=a[b++]&63;f=224==(f&240)?(f&15)<<12|g<<6|h:(f&7)<<18|g<<12|h<<6|a[b++]&63;65536>f?d+=String.fromCharCode(f):(f-=65536,d+=String.fromCharCode(55296|f>>10,56320|f&1023))}}else d+=String.fromCharCode(f)}return d}function J(a,b){return a?Ea(I,a,b):""}
function Fa(a,b,c,d){if(!(0<d))return 0;var f=c;d=c+d-1;for(var g=0;g<a.length;++g){var h=a.charCodeAt(g);if(55296<=h&&57343>=h){var l=a.charCodeAt(++g);h=65536+((h&1023)<<10)|l&1023}if(127>=h){if(c>=d)break;b[c++]=h}else{if(2047>=h){if(c+1>=d)break;b[c++]=192|h>>6}else{if(65535>=h){if(c+2>=d)break;b[c++]=224|h>>12}else{if(c+3>=d)break;b[c++]=240|h>>18;b[c++]=128|h>>12&63}b[c++]=128|h>>6&63}b[c++]=128|h&63}}b[c]=0;return c-f}
function Ga(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}return b}function Ha(a,b){for(var c="",d=0;!(d>=b/2);++d){var f=va[a+2*d>>1];if(0==f)break;c+=String.fromCharCode(f)}return c}function Ia(a,b,c){void 0===c&&(c=2147483647);if(2>c)return 0;c-=2;var d=b;c=c<2*a.length?c/2:a.length;for(var f=0;f<c;++f)va[b>>1]=a.charCodeAt(f),b+=2;va[b>>1]=0;return b-d}
function Ja(a){return 2*a.length}function Ka(a,b){for(var c=0,d="";!(c>=b/4);){var f=E[a+4*c>>2];if(0==f)break;++c;65536<=f?(f-=65536,d+=String.fromCharCode(55296|f>>10,56320|f&1023)):d+=String.fromCharCode(f)}return d}function La(a,b,c){void 0===c&&(c=2147483647);if(4>c)return 0;var d=b;c=d+c-4;for(var f=0;f<a.length;++f){var g=a.charCodeAt(f);if(55296<=g&&57343>=g){var h=a.charCodeAt(++f);g=65536+((g&1023)<<10)|h&1023}E[b>>2]=g;b+=4;if(b+4>c)break}E[b>>2]=0;return b-d}
function Ma(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&++c;b+=4}return b}var ha,D,I,va,Na,E,K,xa,ya,Oa=e.INITIAL_MEMORY||134217728;
if(z)za=e.wasmMemory,ha=e.buffer;else if(e.wasmMemory)za=e.wasmMemory;else if(za=new WebAssembly.Memory({initial:Oa/65536,maximum:Oa/65536,shared:!0}),!(za.buffer instanceof SharedArrayBuffer))throw t("requested a shared WebAssembly.Memory but the returned buffer is not a SharedArrayBuffer, indicating that while the browser has SharedArrayBuffer it does not have WebAssembly threads support - you may need to set a flag"),w&&console.log("(on node you may need: --experimental-wasm-threads --experimental-wasm-bulk-memory and also use a recent version)"),
Error("bad memory");za&&(ha=za.buffer);Oa=ha.byteLength;var Pa=ha;ha=Pa;e.HEAP8=D=new Int8Array(Pa);e.HEAP16=va=new Int16Array(Pa);e.HEAP32=E=new Int32Array(Pa);e.HEAPU8=I=new Uint8Array(Pa);e.HEAPU16=Na=new Uint16Array(Pa);e.HEAPU32=K=new Uint32Array(Pa);e.HEAPF32=xa=new Float32Array(Pa);e.HEAPF64=ya=new Float64Array(Pa);var L,Qa=[],Ra=[],Sa=[],Ta=[];
function Ua(){z||(e.noFSInit||Va||(Va=!0,Wa(),e.stdin=e.stdin,e.stdout=e.stdout,e.stderr=e.stderr,e.stdin?M("/dev","stdin",e.stdin):Xa("/dev/tty","/dev/stdin"),e.stdout?M("/dev","stdout",null,e.stdout):Xa("/dev/tty","/dev/stdout"),e.stderr?M("/dev","stderr",null,e.stderr):Xa("/dev/tty1","/dev/stderr"),Ya("/dev/stdin",0),Ya("/dev/stdout",1),Ya("/dev/stderr",1)),Za(Ra))}function $a(){var a=e.preRun.shift();Qa.unshift(a)}var bb=0,cb=null,db=null;
function eb(){assert(!z,"addRunDependency cannot be used in a pthread worker");bb++;e.monitorRunDependencies&&e.monitorRunDependencies(bb)}function fb(){bb--;e.monitorRunDependencies&&e.monitorRunDependencies(bb);if(0==bb&&(null!==cb&&(clearInterval(cb),cb=null),db)){var a=db;db=null;a()}}e.preloadedImages={};e.preloadedAudios={};
function C(a){if(e.onAbort)e.onAbort(a);z&&console.error("Pthread aborting at "+Error().stack);t(a);Ba=!0;Ca=1;throw new WebAssembly.RuntimeError("abort("+a+"). Build with -s ASSERTIONS=1 for more info.");}function gb(a){var b=hb;return String.prototype.startsWith?b.startsWith(a):0===b.indexOf(a)}function ib(){return gb("data:application/octet-stream;base64,")}var hb="index.wasm";ib()||(hb=ia(hb));
function jb(){var a=hb;try{if(a==hb&&ta)return new Uint8Array(ta);if(la)return la(a);throw"both async and sync fetching of the wasm failed";}catch(b){C(b)}}
function kb(){if(!ta&&(ea||u)){if("function"===typeof fetch&&!gb("file://"))return fetch(hb,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+hb+"'";return a.arrayBuffer()}).catch(function(){return jb()});if(ka)return new Promise(function(a,b){ka(hb,function(c){a(new Uint8Array(c))},b)})}return Promise.resolve().then(function(){return jb()})}
var F,wa,mb={16030596:function(){return window.innerWidth||document.documentElement.clientWidth||document.body.clientWidth},16030714:function(){return window.innerHeight||document.documentElement.clientHeight||document.body.clientHeight},16030837:function(){throw"Canceled!";},16030855:function(a,b){setTimeout(function(){lb(a,b)},0)}};
function Za(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(e);else{var c=b.Tc;"number"===typeof c?void 0===b.tb?L.get(c)():L.get(c)(b.tb):c(void 0===b.tb?null:b.tb)}}}function nb(a,b){if(0>=a||a>D.length||a&1||0>b)return-28;if(0==b)return 0;2147483647<=b&&(b=Infinity);var c=Atomics.load(E,ob>>2),d=0;if(c==a&&Atomics.compareExchange(E,ob>>2,c,0)==c&&(--b,d=1,0>=b))return 1;a=Atomics.notify(E,a>>2,b);if(0<=a)return a+d;throw"Atomics.notify returned an unexpected value "+a;}
e._emscripten_futex_wake=nb;
var O={kb:[],pb:[],$b:[],Zc:function(){for(var a=0;16>a;++a)O.bc()},$c:function(){for(var a=G(228),b=0;57>b;++b)K[a/4+b]=0;E[a+12>>2]=a;b=a+152;E[b>>2]=b;var c=G(512);for(b=0;128>b;++b)K[c/4+b]=0;Atomics.store(K,a+100>>2,c);Atomics.store(K,a+40>>2,a);pb(a,!u,1);qb(a)},ad:function(){O.receiveObjectTransfer=O.hd;O.threadInit=O.xd;O.threadCancel=O.wd;O.threadExit=O.Gc;O.setExitStatus=O.od},ib:{},Hc:[],he:function(){},ld:function(){for(;0<O.Hc.length;)O.Hc.pop()();z&&rb()&&sb()},Ac:function(a,b){Atomics.store(K,
a+56>>2,1);Atomics.store(K,a+60>>2,0);O.ld();Atomics.store(K,a+4>>2,b);Atomics.store(K,a+0>>2,1);nb(a+0,2147483647);pb(0,0,0)},od:function(a){Ca=a},Gc:function(a){var b=rb();b&&(O.Ac(b,a),z&&postMessage({cmd:"exit"}))},wd:function(){O.Ac(rb(),-1);postMessage({cmd:"cancelDone"})},vd:function(){for(var a in O.ib){var b=O.ib[a];b&&b.worker&&O.Jb(b.worker)}O.ib={};for(a=0;a<O.kb.length;++a){var c=O.kb[a];c.terminate()}O.kb=[];for(a=0;a<O.pb.length;++a)c=O.pb[a],b=c.fb,O.Ub(b),c.terminate();O.pb=[]},Ub:function(a){if(a){if(a.jb){var b=
E[a.jb+100>>2];E[a.jb+100>>2]=0;P(b);P(a.jb)}a.jb=0;a.Pb&&a.rb&&P(a.rb);a.rb=0;a.worker&&(a.worker.fb=null)}},Jb:function(a){O.md(function(){delete O.ib[a.fb.jb];O.kb.push(a);O.pb.splice(O.pb.indexOf(a),1);O.Ub(a.fb);a.fb=void 0})},md:function(a){E[tb>>2]=0;try{a()}finally{E[tb>>2]=1}},hd:function(){},xd:function(){rb();for(var a in O.$b)O.$b[a]()},pc:function(a,b){a.onmessage=function(c){var d=c.data,f=d.cmd;a.fb&&(O.Rc=a.fb.jb);if(d.targetThread&&d.targetThread!=rb()){var g=O.ib[d.ie];g?g.worker.postMessage(c.data,
d.transferList):console.error('Internal error! Worker sent a message "'+f+'" to target pthread '+d.targetThread+", but that thread no longer exists!")}else if("processQueuedMainThreadWork"===f)ub();else if("spawnThread"===f)vb(c.data);else if("cleanupThread"===f){c=d.thread;if(z)throw"Internal Error! cleanupThread() can only ever be called from main application thread!";if(!c)throw"Internal Error! Null pthread_ptr in cleanupThread!";if(d=O.ib[c])E[c+12>>2]=0,O.Jb(d.worker)}else if("killThread"===
f){c=d.thread;if(z)throw"Internal Error! killThread() can only ever be called from main application thread!";if(!c)throw"Internal Error! Null pthread_ptr in killThread!";E[c+12>>2]=0;c=O.ib[c];c.worker.terminate();O.Ub(c);O.pb.splice(O.pb.indexOf(c.worker),1);c.worker.fb=void 0}else if("cancelThread"===f){c=d.thread;if(z)throw"Internal Error! cancelThread() can only ever be called from main application thread!";if(!c)throw"Internal Error! Null pthread_ptr in cancelThread!";O.ib[c].worker.postMessage({cmd:"cancel"})}else if("loaded"===
f)a.loaded=!0,b&&b(a),a.Cb&&(a.Cb(),delete a.Cb);else if("print"===f)qa("Thread "+d.threadId+": "+d.text);else if("printErr"===f)t("Thread "+d.threadId+": "+d.text);else if("alert"===f)alert("Thread "+d.threadId+": "+d.text);else if("exit"===f)a.fb&&Atomics.load(K,a.fb.jb+64>>2)&&O.Jb(a);else if("exitProcess"===f)try{wb(d.returnCode)}catch(h){if(h instanceof oa)return;throw h;}else"cancelDone"===f?O.Jb(a):"objectTransfer"!==f&&("setimmediate"===c.data.target?a.postMessage(c.data):t("worker sent an unknown command "+
f));O.Rc=void 0};a.onerror=function(c){t("pthread sent an error! "+c.filename+":"+c.lineno+": "+c.message)};w&&(a.on("message",function(c){a.onmessage({data:c})}),a.on("error",function(c){a.onerror(c)}),a.on("exit",function(){}));a.postMessage({cmd:"load",urlOrBlob:e.mainScriptUrlOrBlob||_scriptDir,wasmMemory:za,wasmModule:Aa})},bc:function(){var a=ia("index.worker.js");O.kb.push(new Worker(a))},Uc:function(){0==O.kb.length&&(O.bc(),O.pc(O.kb[0]));return O.kb.pop()},Hd:function(a){for(a=performance.now()+
a;performance.now()<a;);}};e.establishStackSpace=function(a,b){xb(a,b);yb(a)};e.invokeEntryPoint=function(a,b){return L.get(a)(b)};var zb=0;function Ab(){return noExitRuntime||0<zb}e.keepRuntimeAlive=Ab;var Bb;w?Bb=function(){var a=process.hrtime();return 1E3*a[0]+a[1]/1E6}:z?Bb=function(){return performance.now()-e.__performance_now_clock_drift}:"undefined"!==typeof dateNow?Bb=dateNow:Bb=function(){return performance.now()};
function Cb(a){this.xb=a-16;this.td=function(b){E[this.xb+8>>2]=b};this.qd=function(b){E[this.xb+0>>2]=b};this.rd=function(){E[this.xb+4>>2]=0};this.pd=function(){D[this.xb+12>>0]=0};this.sd=function(){D[this.xb+13>>0]=0};this.Xc=function(b,c){this.td(b);this.qd(c);this.rd();this.pd();this.sd()}}var Db=0;function Eb(a,b){for(var c=0,d=a.length-1;0<=d;d--){var f=a[d];"."===f?a.splice(d,1):".."===f?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a}
function Fb(a){var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=Eb(a.split("/").filter(function(d){return!!d}),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a}function Gb(a){var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b}function Hb(a){if("/"===a)return"/";a=Fb(a);a=a.replace(/\/$/,"");var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)}
function Ib(){if("object"===typeof crypto&&"function"===typeof crypto.getRandomValues){var a=new Uint8Array(1);return function(){crypto.getRandomValues(a);return a[0]}}if(w)try{var b=require("crypto");return function(){return b.randomBytes(1)[0]}}catch(c){}return function(){C("randomDevice")}}
function Jb(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:"/";if("string"!==typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=Eb(a.split("/").filter(function(d){return!!d}),!b).join("/");return(b?"/":"")+a||"."}var Kb=[];function Lb(a,b){Kb[a]={input:[],output:[],wb:b};Mb(a,Nb)}
var Nb={open:function(a){var b=Kb[a.node.rdev];if(!b)throw new Q(43);a.tty=b;a.seekable=!1},close:function(a){a.tty.wb.flush(a.tty)},flush:function(a){a.tty.wb.flush(a.tty)},read:function(a,b,c,d){if(!a.tty||!a.tty.wb.mc)throw new Q(60);for(var f=0,g=0;g<d;g++){try{var h=a.tty.wb.mc(a.tty)}catch(l){throw new Q(29);}if(void 0===h&&0===f)throw new Q(6);if(null===h||void 0===h)break;f++;b[c+g]=h}f&&(a.node.timestamp=Date.now());return f},write:function(a,b,c,d){if(!a.tty||!a.tty.wb.Yb)throw new Q(60);
try{for(var f=0;f<d;f++)a.tty.wb.Yb(a.tty,b[c+f])}catch(g){throw new Q(29);}d&&(a.node.timestamp=Date.now());return f}},Pb={mc:function(a){if(!a.input.length){var b=null;if(w){var c=Buffer.cb?Buffer.cb(256):new Buffer(256),d=0;try{d=ma.readSync(process.stdin.fd,c,0,256,null)}catch(f){if(-1!=f.toString().indexOf("EOF"))d=0;else throw f;}0<d?b=c.slice(0,d).toString("utf-8"):b=null}else"undefined"!=typeof window&&"function"==typeof window.prompt?(b=window.prompt("Input: "),null!==b&&(b+="\n")):"function"==
typeof readline&&(b=readline(),null!==b&&(b+="\n"));if(!b)return null;a.input=Ob(b,!0)}return a.input.shift()},Yb:function(a,b){null===b||10===b?(qa(Ea(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(qa(Ea(a.output,0)),a.output=[])}},Qb={Yb:function(a,b){null===b||10===b?(t(Ea(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(t(Ea(a.output,0)),a.output=[])}},R={gb:null,mb:function(){return R.createNode(null,
"/",16895,0)},createNode:function(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new Q(63);R.gb||(R.gb={dir:{node:{ob:R.Za.ob,eb:R.Za.eb,lookup:R.Za.lookup,Hb:R.Za.Hb,rename:R.Za.rename,unlink:R.Za.unlink,rmdir:R.Za.rmdir,readdir:R.Za.readdir,symlink:R.Za.symlink},stream:{qb:R.$a.qb}},file:{node:{ob:R.Za.ob,eb:R.Za.eb},stream:{qb:R.$a.qb,read:R.$a.read,write:R.$a.write,ac:R.$a.ac,tc:R.$a.tc,wc:R.$a.wc}},link:{node:{ob:R.Za.ob,eb:R.Za.eb,readlink:R.Za.readlink},stream:{}},ec:{node:{ob:R.Za.ob,
eb:R.Za.eb},stream:Rb}});c=Sb(a,b,c,d);16384===(c.mode&61440)?(c.Za=R.gb.dir.node,c.$a=R.gb.dir.stream,c.Ya={}):32768===(c.mode&61440)?(c.Za=R.gb.file.node,c.$a=R.gb.file.stream,c.ab=0,c.Ya=null):40960===(c.mode&61440)?(c.Za=R.gb.link.node,c.$a=R.gb.link.stream):8192===(c.mode&61440)&&(c.Za=R.gb.ec.node,c.$a=R.gb.ec.stream);c.timestamp=Date.now();a&&(a.Ya[b]=c,a.timestamp=c.timestamp);return c},Sd:function(a){return a.Ya?a.Ya.subarray?a.Ya.subarray(0,a.ab):new Uint8Array(a.Ya):new Uint8Array(0)},
ic:function(a,b){var c=a.Ya?a.Ya.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)>>>0),0!=c&&(b=Math.max(b,256)),c=a.Ya,a.Ya=new Uint8Array(b),0<a.ab&&a.Ya.set(c.subarray(0,a.ab),0))},kd:function(a,b){if(a.ab!=b)if(0==b)a.Ya=null,a.ab=0;else{var c=a.Ya;a.Ya=new Uint8Array(b);c&&a.Ya.set(c.subarray(0,Math.min(b,a.ab)));a.ab=b}},Za:{ob:function(a){var b={};b.dev=8192===(a.mode&61440)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;16384===(a.mode&61440)?b.size=4096:32768===
(a.mode&61440)?b.size=a.ab:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.atime=new Date(a.timestamp);b.mtime=new Date(a.timestamp);b.ctime=new Date(a.timestamp);b.Oc=4096;b.blocks=Math.ceil(b.size/b.Oc);return b},eb:function(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);void 0!==b.size&&R.kd(a,b.size)},lookup:function(){throw Tb[44];},Hb:function(a,b,c,d){return R.createNode(a,b,c,d)},rename:function(a,b,c){if(16384===(a.mode&61440)){try{var d=Ub(b,
c)}catch(g){}if(d)for(var f in d.Ya)throw new Q(55);}delete a.parent.Ya[a.name];a.parent.timestamp=Date.now();a.name=c;b.Ya[c]=a;b.timestamp=a.parent.timestamp;a.parent=b},unlink:function(a,b){delete a.Ya[b];a.timestamp=Date.now()},rmdir:function(a,b){var c=Ub(a,b),d;for(d in c.Ya)throw new Q(55);delete a.Ya[b];a.timestamp=Date.now()},readdir:function(a){var b=[".",".."],c;for(c in a.Ya)a.Ya.hasOwnProperty(c)&&b.push(c);return b},symlink:function(a,b,c){a=R.createNode(a,b,41471,0);a.link=c;return a},
readlink:function(a){if(40960!==(a.mode&61440))throw new Q(28);return a.link}},$a:{read:function(a,b,c,d,f){var g=a.node.Ya;if(f>=a.node.ab)return 0;a=Math.min(a.node.ab-f,d);if(8<a&&g.subarray)b.set(g.subarray(f,f+a),c);else for(d=0;d<a;d++)b[c+d]=g[f+d];return a},write:function(a,b,c,d,f,g){if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.Ya||a.Ya.subarray)){if(g)return a.Ya=b.subarray(c,c+d),a.ab=d;if(0===a.ab&&0===f)return a.Ya=b.slice(c,c+d),a.ab=d;if(f+d<=a.ab)return a.Ya.set(b.subarray(c,
c+d),f),d}R.ic(a,f+d);if(a.Ya.subarray&&b.subarray)a.Ya.set(b.subarray(c,c+d),f);else for(g=0;g<d;g++)a.Ya[f+g]=b[c+g];a.ab=Math.max(a.ab,f+d);return d},qb:function(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.ab);if(0>b)throw new Q(28);return b},ac:function(a,b,c){R.ic(a.node,b+c);a.node.ab=Math.max(a.node.ab,b+c)},tc:function(a,b,c,d,f,g){if(0!==b)throw new Q(28);if(32768!==(a.node.mode&61440))throw new Q(43);a=a.node.Ya;if(g&2||a.buffer!==ha){if(0<d||d+c<a.length)a.subarray?
a=a.subarray(d,d+c):a=Array.prototype.slice.call(a,d,d+c);d=!0;g=16384*Math.ceil(c/16384);for(b=G(g);c<g;)D[b+c++]=0;c=b;if(!c)throw new Q(48);D.set(a,c)}else d=!1,c=a.byteOffset;return{xb:c,Fd:d}},wc:function(a,b,c,d,f){if(32768!==(a.node.mode&61440))throw new Q(43);if(f&2)return 0;R.$a.write(a,b,0,d,c,!1);return 0}}},Vb=null,Wb={},Xb=[],Yb=1,Zb=null,$b=!0,ac={},Q=null,Tb={};
function bc(a,b){a=Jb("/",a);b=b||{};if(!a)return{path:"",node:null};var c={jc:!0,Zb:0},d;for(d in c)void 0===b[d]&&(b[d]=c[d]);if(8<b.Zb)throw new Q(32);a=Eb(a.split("/").filter(function(h){return!!h}),!1);var f=Vb;c="/";for(d=0;d<a.length;d++){var g=d===a.length-1;if(g&&b.parent)break;f=Ub(f,a[d]);c=Fb(c+"/"+a[d]);f.Bb&&(!g||g&&b.jc)&&(f=f.Bb.root);if(!g||b.Tb)for(g=0;40960===(f.mode&61440);)if(f=cc(c),c=Jb(Gb(c),f),f=bc(c,{Zb:b.Zb}).node,40<g++)throw new Q(32);}return{path:c,node:f}}
function dc(a){for(var b;;){if(a===a.parent)return a=a.mb.uc,b?"/"!==a[a.length-1]?a+"/"+b:a+b:a;b=b?a.name+"/"+b:a.name;a=a.parent}}function ec(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%Zb.length}function Ub(a,b){var c;if(c=(c=fc(a,"x"))?c:a.Za.lookup?0:2)throw new Q(c,a);for(c=Zb[ec(a.id,b)];c;c=c.vb){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.Za.lookup(a,b)}
function Sb(a,b,c,d){a=new hc(a,b,c,d);b=ec(a.parent.id,a.name);a.vb=Zb[b];return Zb[b]=a}var ic={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090};function jc(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}function fc(a,b){if($b)return 0;if(-1===b.indexOf("r")||a.mode&292){if(-1!==b.indexOf("w")&&!(a.mode&146)||-1!==b.indexOf("x")&&!(a.mode&73))return 2}else return 2;return 0}function kc(a,b){try{return Ub(a,b),20}catch(c){}return fc(a,"wx")}
function lc(){var a=4096;for(var b=0;b<=a;b++)if(!Xb[b])return b;throw new Q(33);}function mc(a){nc||(nc=function(){},nc.prototype={});var b=new nc,c;for(c in a)b[c]=a[c];a=b;b=lc();a.fd=b;return Xb[b]=a}var Rb={open:function(a){a.$a=Wb[a.node.rdev].$a;a.$a.open&&a.$a.open(a)},qb:function(){throw new Q(70);}};function Mb(a,b){Wb[a]={$a:b}}
function oc(a,b){var c="/"===b,d=!b;if(c&&Vb)throw new Q(10);if(!c&&!d){var f=bc(b,{jc:!1});b=f.path;f=f.node;if(f.Bb)throw new Q(10);if(16384!==(f.mode&61440))throw new Q(54);}b={type:a,de:{},uc:b,ed:[]};a=a.mb(b);a.mb=b;b.root=a;c?Vb=a:f&&(f.Bb=b,f.mb&&f.mb.ed.push(b))}function pc(a,b,c){var d=bc(a,{parent:!0}).node;a=Hb(a);if(!a||"."===a||".."===a)throw new Q(28);var f=kc(d,a);if(f)throw new Q(f);if(!d.Za.Hb)throw new Q(63);return d.Za.Hb(d,a,b,c)}function S(a){return pc(a,16895,0)}
function qc(a,b,c){"undefined"===typeof c&&(c=b,b=438);return pc(a,b|8192,c)}function Xa(a,b){if(!Jb(a))throw new Q(44);var c=bc(b,{parent:!0}).node;if(!c)throw new Q(44);b=Hb(b);var d=kc(c,b);if(d)throw new Q(d);if(!c.Za.symlink)throw new Q(63);c.Za.symlink(c,b,a)}
function rc(a){var b=bc(a,{parent:!0}).node,c=Hb(a),d=Ub(b,c);a:{try{var f=Ub(b,c)}catch(h){f=h.lb;break a}var g=fc(b,"wx");f=g?g:16384===(f.mode&61440)?31:0}if(f)throw new Q(f);if(!b.Za.unlink)throw new Q(63);if(d.Bb)throw new Q(10);try{ac.willDeletePath&&ac.willDeletePath(a)}catch(h){t("FS.trackingDelegate['willDeletePath']('"+a+"') threw an exception: "+h.message)}b.Za.unlink(b,c);b=ec(d.parent.id,d.name);if(Zb[b]===d)Zb[b]=d.vb;else for(b=Zb[b];b;){if(b.vb===d){b.vb=d.vb;break}b=b.vb}try{if(ac.onDeletePath)ac.onDeletePath(a)}catch(h){t("FS.trackingDelegate['onDeletePath']('"+
a+"') threw an exception: "+h.message)}}function cc(a){a=bc(a).node;if(!a)throw new Q(44);if(!a.Za.readlink)throw new Q(28);return Jb(dc(a.parent),a.Za.readlink(a))}function sc(a,b){a="string"===typeof a?bc(a,{Tb:!0}).node:a;if(!a.Za.eb)throw new Q(63);a.Za.eb(a,{mode:b&4095|a.mode&-4096,timestamp:Date.now()})}
function Ya(a,b,c){if(""===a)throw new Q(44);if("string"===typeof b){var d=ic[b];if("undefined"===typeof d)throw Error("Unknown file open mode: "+b);b=d}c=b&64?("undefined"===typeof c?438:c)&4095|32768:0;if("object"===typeof a)var f=a;else{a=Fb(a);try{f=bc(a,{Tb:!(b&131072)}).node}catch(g){}}d=!1;if(b&64)if(f){if(b&128)throw new Q(20);}else f=pc(a,c,0),d=!0;if(!f)throw new Q(44);8192===(f.mode&61440)&&(b&=-513);if(b&65536&&16384!==(f.mode&61440))throw new Q(54);if(!d&&(c=f?40960===(f.mode&61440)?
32:16384===(f.mode&61440)&&("r"!==jc(b)||b&512)?31:fc(f,jc(b)):44))throw new Q(c);if(b&512){c=f;c="string"===typeof c?bc(c,{Tb:!0}).node:c;if(!c.Za.eb)throw new Q(63);if(16384===(c.mode&61440))throw new Q(31);if(32768!==(c.mode&61440))throw new Q(28);if(d=fc(c,"w"))throw new Q(d);c.Za.eb(c,{size:0,timestamp:Date.now()})}b&=-131713;f=mc({node:f,path:dc(f),flags:b,seekable:!0,position:0,$a:f.$a,Dd:[],error:!1});f.$a.open&&f.$a.open(f);!e.logReadFiles||b&1||(tc||(tc={}),a in tc||(tc[a]=1,t("FS.trackingDelegate error on read file: "+
a)));try{ac.onOpenFile&&(c=0,1!==(b&2097155)&&(c|=1),0!==(b&2097155)&&(c|=2),ac.onOpenFile(a,c))}catch(g){t("FS.trackingDelegate['onOpenFile']('"+a+"', flags) threw an exception: "+g.message)}return f}function uc(a){if(null===a.fd)throw new Q(8);a.Wb&&(a.Wb=null);try{a.$a.close&&a.$a.close(a)}catch(b){throw b;}finally{Xb[a.fd]=null}a.fd=null}
function vc(a,b,c){if(null===a.fd)throw new Q(8);if(!a.seekable||!a.$a.qb)throw new Q(70);if(0!=c&&1!=c&&2!=c)throw new Q(28);a.position=a.$a.qb(a,b,c);a.Dd=[]}
function wc(a,b,c,d,f,g){if(0>d||0>f)throw new Q(28);if(null===a.fd)throw new Q(8);if(0===(a.flags&2097155))throw new Q(8);if(16384===(a.node.mode&61440))throw new Q(31);if(!a.$a.write)throw new Q(28);a.seekable&&a.flags&1024&&vc(a,0,2);var h="undefined"!==typeof f;if(!h)f=a.position;else if(!a.seekable)throw new Q(70);b=a.$a.write(a,b,c,d,f,g);h||(a.position+=b);try{if(a.path&&ac.onWriteToFile)ac.onWriteToFile(a.path)}catch(l){t("FS.trackingDelegate['onWriteToFile']('"+a.path+"') threw an exception: "+
l.message)}return b}function Wa(){Q||(Q=function(a,b){this.node=b;this.nd=function(c){this.lb=c};this.nd(a);this.message="FS error"},Q.prototype=Error(),Q.prototype.constructor=Q,[44].forEach(function(a){Tb[a]=new Q(a);Tb[a].stack="<generic error, no stack>"}))}var Va;function xc(a,b){var c=0;a&&(c|=365);b&&(c|=146);return c}function yc(a,b){a="string"===typeof a?a:dc(a);for(b=b.split("/").reverse();b.length;){var c=b.pop();if(c){var d=Fb(a+"/"+c);try{S(d)}catch(f){}a=d}}return d}
function zc(a,b,c,d){a=Fb(("string"===typeof a?a:dc(a))+"/"+b);c=xc(c,d);return pc(a,(void 0!==c?c:438)&4095|32768,0)}function Ac(a,b,c,d,f,g){a=b?Fb(("string"===typeof a?a:dc(a))+"/"+b):a;d=xc(d,f);f=pc(a,(void 0!==d?d:438)&4095|32768,0);if(c){if("string"===typeof c){a=Array(c.length);b=0;for(var h=c.length;b<h;++b)a[b]=c.charCodeAt(b);c=a}sc(f,d|146);a=Ya(f,577);wc(a,c,0,c.length,0,g);uc(a);sc(f,d)}return f}
function M(a,b,c,d){a=Fb(("string"===typeof a?a:dc(a))+"/"+b);b=xc(!!c,!!d);M.qc||(M.qc=64);var f=M.qc++<<8|0;Mb(f,{open:function(g){g.seekable=!1},close:function(){d&&d.buffer&&d.buffer.length&&d(10)},read:function(g,h,l,m){for(var n=0,q=0;q<m;q++){try{var r=c()}catch(v){throw new Q(29);}if(void 0===r&&0===n)throw new Q(6);if(null===r||void 0===r)break;n++;h[l+q]=r}n&&(g.node.timestamp=Date.now());return n},write:function(g,h,l,m){for(var n=0;n<m;n++)try{d(h[l+n])}catch(q){throw new Q(29);}m&&(g.node.timestamp=
Date.now());return n}});return qc(a,b,f)}function Bc(a){if(!(a.cd||a.dd||a.link||a.Ya)){if("undefined"!==typeof XMLHttpRequest)throw Error("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");if(ja)try{a.Ya=Ob(ja(a.url),!0),a.ab=a.Ya.length}catch(b){throw new Q(29);}else throw Error("Cannot load without read() or XMLHttpRequest.");}}
function Cc(a,b,c,d,f){function g(){this.Xb=!1;this.cb=[]}g.prototype.get=function(q){if(!(q>this.length-1||0>q)){var r=q%this.chunkSize;return this.nc(q/this.chunkSize|0)[r]}};g.prototype.Ob=function(q){this.nc=q};g.prototype.cc=function(){var q=new XMLHttpRequest;q.open("HEAD",c,!1);q.send(null);if(!(200<=q.status&&300>q.status||304===q.status))throw Error("Couldn't load "+c+". Status: "+q.status);var r=Number(q.getResponseHeader("Content-length")),v,k=(v=q.getResponseHeader("Accept-Ranges"))&&
"bytes"===v;q=(v=q.getResponseHeader("Content-Encoding"))&&"gzip"===v;var p=1048576;k||(p=r);var x=this;x.Ob(function(A){var y=A*p,H=(A+1)*p-1;H=Math.min(H,r-1);if("undefined"===typeof x.cb[A]){var ab=x.cb;if(y>H)throw Error("invalid range ("+y+", "+H+") or no bytes requested!");if(H>r-1)throw Error("only "+r+" bytes available! programmer error!");var N=new XMLHttpRequest;N.open("GET",c,!1);r!==p&&N.setRequestHeader("Range","bytes="+y+"-"+H);"undefined"!=typeof Uint8Array&&(N.responseType="arraybuffer");
N.overrideMimeType&&N.overrideMimeType("text/plain; charset=x-user-defined");N.send(null);if(!(200<=N.status&&300>N.status||304===N.status))throw Error("Couldn't load "+c+". Status: "+N.status);y=void 0!==N.response?new Uint8Array(N.response||[]):Ob(N.responseText||"",!0);ab[A]=y}if("undefined"===typeof x.cb[A])throw Error("doXHR failed!");return x.cb[A]});if(q||!r)p=r=1,p=r=this.nc(0).length,qa("LazyFiles on gzip forces download of the whole file when length is accessed");this.Lc=r;this.Kc=p;this.Xb=
!0};if("undefined"!==typeof XMLHttpRequest){if(!u)throw"Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc";var h=new g;Object.defineProperties(h,{length:{get:function(){this.Xb||this.cc();return this.Lc}},chunkSize:{get:function(){this.Xb||this.cc();return this.Kc}}});var l=void 0}else l=c,h=void 0;var m=zc(a,b,d,f);h?m.Ya=h:l&&(m.Ya=null,m.url=l);Object.defineProperties(m,{ab:{get:function(){return this.Ya.length}}});var n={};Object.keys(m.$a).forEach(function(q){var r=
m.$a[q];n[q]=function(){Bc(m);return r.apply(null,arguments)}});n.read=function(q,r,v,k,p){Bc(m);q=q.node.Ya;if(p>=q.length)return 0;k=Math.min(q.length-p,k);if(q.slice)for(var x=0;x<k;x++)r[v+x]=q[p+x];else for(x=0;x<k;x++)r[v+x]=q.get(p+x);return k};m.$a=n;return m}
function Dc(a,b,c,d,f,g,h,l,m,n){function q(k){function p(A){n&&n();l||Ac(a,b,A,d,f,m);g&&g();fb(v)}var x=!1;e.preloadPlugins.forEach(function(A){!x&&A.canHandle(r)&&(A.handle(k,r,p,function(){h&&h();fb(v)}),x=!0)});x||p(k)}Ec();var r=b?Jb(Fb(a+"/"+b)):a,v="cp "+r;eb(v);"string"==typeof c?Fc(c,function(k){q(k)},h):q(c)}var Gc={},nc,tc,Hc=void 0;function Ic(){Hc+=4;return E[Hc-4>>2]}function Jc(a){a=Xb[a];if(!a)throw new Q(8);return a}
function Kc(a,b,c){if(z)return T(2,1,a,b,c);Hc=c;try{var d=Jc(a);switch(b){case 21509:case 21505:return d.tty?0:-59;case 21510:case 21511:case 21512:case 21506:case 21507:case 21508:return d.tty?0:-59;case 21519:if(!d.tty)return-59;var f=Ic();return E[f>>2]=0;case 21520:return d.tty?-28:-59;case 21531:a=f=Ic();if(!d.$a.bd)throw new Q(59);return d.$a.bd(d,b,a);case 21523:return d.tty?0:-59;case 21524:return d.tty?0:-59;default:C("bad ioctl syscall "+b)}}catch(g){return"undefined"!==typeof Gc&&g instanceof
Q||C(g),-g.lb}}function Lc(a,b,c){if(z)return T(3,1,a,b,c);Hc=c;try{var d=J(a),f=c?Ic():0;return Ya(d,b,f).fd}catch(g){return"undefined"!==typeof Gc&&g instanceof Q||C(g),-g.lb}}function Mc(a){switch(a){case 1:return 0;case 2:return 1;case 4:return 2;case 8:return 3;default:throw new TypeError("Unknown type size: "+a);}}var Nc=void 0;function U(a){for(var b="";I[a];)b+=Nc[I[a++]];return b}var Oc={},Pc={},Qc={};
function Rc(a){if(void 0===a)return"_unknown";a=a.replace(/[^a-zA-Z0-9_]/g,"$");var b=a.charCodeAt(0);return 48<=b&&57>=b?"_"+a:a}function Sc(a,b){a=Rc(a);return(new Function("body","return function "+a+'() {\n    "use strict";    return body.apply(this, arguments);\n};\n'))(b)}
function Tc(a){var b=Error,c=Sc(a,function(d){this.name=a;this.message=d;d=Error(d).stack;void 0!==d&&(this.stack=this.toString()+"\n"+d.replace(/^Error(:[^\n]*)?\n/,""))});c.prototype=Object.create(b.prototype);c.prototype.constructor=c;c.prototype.toString=function(){return void 0===this.message?this.name:this.name+": "+this.message};return c}var Uc=void 0;function V(a){throw new Uc(a);}var Vc=void 0;
function Wc(a,b){function c(l){l=b(l);if(l.length!==d.length)throw new Vc("Mismatched type converter count");for(var m=0;m<d.length;++m)Xc(d[m],l[m])}var d=[];d.forEach(function(l){Qc[l]=a});var f=Array(a.length),g=[],h=0;a.forEach(function(l,m){Pc.hasOwnProperty(l)?f[m]=Pc[l]:(g.push(l),Oc.hasOwnProperty(l)||(Oc[l]=[]),Oc[l].push(function(){f[m]=Pc[l];++h;h===g.length&&c(f)}))});0===g.length&&c(f)}
function Xc(a,b,c){c=c||{};if(!("argPackAdvance"in b))throw new TypeError("registerType registeredInstance requires argPackAdvance");var d=b.name;a||V('type "'+d+'" must have a positive integer typeid pointer');if(Pc.hasOwnProperty(a)){if(c.Wc)return;V("Cannot register type '"+d+"' twice")}Pc[a]=b;delete Qc[a];Oc.hasOwnProperty(a)&&(b=Oc[a],delete Oc[a],b.forEach(function(f){f()}))}var Yc=[],W=[{},{value:void 0},{value:null},{value:!0},{value:!1}];
function Zc(a){switch(a){case void 0:return 1;case null:return 2;case !0:return 3;case !1:return 4;default:var b=Yc.length?Yc.pop():W.length;W[b]={jd:1,value:a};return b}}function $c(a){return this.fromWireType(K[a>>2])}function ad(a){if(null===a)return"null";var b=typeof a;return"object"===b||"array"===b||"function"===b?a.toString():""+a}
function bd(a,b){switch(b){case 2:return function(c){return this.fromWireType(xa[c>>2])};case 3:return function(c){return this.fromWireType(ya[c>>3])};default:throw new TypeError("Unknown float type: "+a);}}function cd(a){var b=Function;if(!(b instanceof Function))throw new TypeError("new_ called with constructor type "+typeof b+" which is not a function");var c=Sc(b.name||"unknownFunctionName",function(){});c.prototype=b.prototype;c=new c;a=b.apply(c,a);return a instanceof Object?a:c}
function dd(a){for(;a.length;){var b=a.pop();a.pop()(b)}}function ed(a,b){var c=e;if(void 0===c[a].hb){var d=c[a];c[a]=function(){c[a].hb.hasOwnProperty(arguments.length)||V("Function '"+b+"' called with an invalid number of arguments ("+arguments.length+") - expects one of ("+c[a].hb+")!");return c[a].hb[arguments.length].apply(this,arguments)};c[a].hb=[];c[a].hb[d.Nc]=d}}
function fd(a,b,c){e.hasOwnProperty(a)?((void 0===c||void 0!==e[a].hb&&void 0!==e[a].hb[c])&&V("Cannot register public name '"+a+"' twice"),ed(a,a),e.hasOwnProperty(c)&&V("Cannot register multiple overloads of a function with the same number of arguments ("+c+")!"),e[a].hb[c]=b):(e[a]=b,void 0!==c&&(e[a].ce=c))}function gd(a,b){for(var c=[],d=0;d<a;d++)c.push(E[(b>>2)+d]);return c}
function hd(a,b){var c=[];return function(){c.length=arguments.length;for(var d=0;d<arguments.length;d++)c[d]=arguments[d];-1!=a.indexOf("j")?(d=e["dynCall_"+a],d=c&&c.length?d.apply(null,[b].concat(c)):d.call(null,b)):d=L.get(b).apply(null,c);return d}}function id(a,b){a=U(a);var c=-1!=a.indexOf("j")?hd(a,b):L.get(b);"function"!==typeof c&&V("unknown function pointer with signature "+a+": "+b);return c}var jd=void 0;function kd(a){a=ld(a);var b=U(a);P(a);return b}
function md(a,b){function c(g){f[g]||Pc[g]||(Qc[g]?Qc[g].forEach(c):(d.push(g),f[g]=!0))}var d=[],f={};b.forEach(c);throw new jd(a+": "+d.map(kd).join([", "]));}function nd(a,b,c){switch(b){case 0:return c?function(d){return D[d]}:function(d){return I[d]};case 1:return c?function(d){return va[d>>1]}:function(d){return Na[d>>1]};case 2:return c?function(d){return E[d>>2]}:function(d){return K[d>>2]};default:throw new TypeError("Unknown integer type: "+a);}}
function od(a,b){if(0>=a)return a;var c=32>=b?Math.abs(1<<b-1):Math.pow(2,b-1);a>=c&&(32>=b||a>c)&&(a=-2*c+a);return a}function pd(a,b){return 0<=a?a:32>=b?2*Math.abs(1<<b-1)+a:Math.pow(2,b)+a}
function qd(a,b){function c(H){var ab=d;("double"===H||"i64"===H)&&ab&7&&(ab+=4);d=ab;"double"===H?(H=ya[d>>3],d+=8):"i64"==H?(H=[E[d>>2],E[d+4>>2]],d+=8):(H=E[d>>2],d+=4);return H}for(var d=b,f=[],g,h;;){var l=a;g=D[a>>0];if(0===g)break;h=D[a+1>>0];if(37==g){var m=!1,n=b=!1,q=!1,r=!1;a:for(;;){switch(h){case 43:m=!0;break;case 45:b=!0;break;case 35:n=!0;break;case 48:if(q)break a;else{q=!0;break}case 32:r=!0;break;default:break a}a++;h=D[a+1>>0]}var v=0;if(42==h)v=c("i32"),a++,h=D[a+1>>0];else for(;48<=
h&&57>=h;)v=10*v+(h-48),a++,h=D[a+1>>0];var k=!1,p=-1;if(46==h){p=0;k=!0;a++;h=D[a+1>>0];if(42==h)p=c("i32"),a++;else for(;;){h=D[a+1>>0];if(48>h||57<h)break;p=10*p+(h-48);a++}h=D[a+1>>0]}0>p&&(p=6,k=!1);switch(String.fromCharCode(h)){case "h":h=D[a+2>>0];if(104==h){a++;var x=1}else x=2;break;case "l":h=D[a+2>>0];108==h?(a++,x=8):x=4;break;case "L":case "q":case "j":x=8;break;case "z":case "t":case "I":x=4;break;default:x=null}x&&a++;h=D[a+1>>0];switch(String.fromCharCode(h)){case "d":case "i":case "u":case "o":case "x":case "X":case "p":l=
100==h||105==h;x=x||4;g=c("i"+8*x);8==x&&(g=117==h?(g[0]>>>0)+4294967296*(g[1]>>>0):(g[0]>>>0)+4294967296*g[1]);4>=x&&(g=(l?od:pd)(g&Math.pow(256,x)-1,8*x));var A=Math.abs(g);l="";if(100==h||105==h)var y=od(g,8*x,1).toString(10);else if(117==h)y=pd(g,8*x,1).toString(10),g=Math.abs(g);else if(111==h)y=(n?"0":"")+A.toString(8);else if(120==h||88==h){l=n&&0!=g?"0x":"";if(0>g){g=-g;y=(A-1).toString(16);A=[];for(n=0;n<y.length;n++)A.push((15-parseInt(y[n],16)).toString(16));for(y=A.join("");y.length<2*
x;)y="f"+y}else y=A.toString(16);88==h&&(l=l.toUpperCase(),y=y.toUpperCase())}else 112==h&&(0===A?y="(nil)":(l="0x",y=A.toString(16)));if(k)for(;y.length<p;)y="0"+y;0<=g&&(m?l="+"+l:r&&(l=" "+l));"-"==y.charAt(0)&&(l="-"+l,y=y.substr(1));for(;l.length+y.length<v;)b?y+=" ":q?y="0"+y:l=" "+l;y=l+y;y.split("").forEach(function(H){f.push(H.charCodeAt(0))});break;case "f":case "F":case "e":case "E":case "g":case "G":g=c("double");if(isNaN(g))y="nan",q=!1;else if(isFinite(g)){k=!1;x=Math.min(p,20);if(103==
h||71==h)k=!0,p=p||1,x=parseInt(g.toExponential(x).split("e")[1],10),p>x&&-4<=x?(h=(103==h?"f":"F").charCodeAt(0),p-=x+1):(h=(103==h?"e":"E").charCodeAt(0),p--),x=Math.min(p,20);if(101==h||69==h)y=g.toExponential(x),/[eE][-+]\d$/.test(y)&&(y=y.slice(0,-1)+"0"+y.slice(-1));else if(102==h||70==h)y=g.toFixed(x),0===g&&(0>g||0===g&&-Infinity===1/g)&&(y="-"+y);l=y.split("e");if(k&&!n)for(;1<l[0].length&&-1!=l[0].indexOf(".")&&("0"==l[0].slice(-1)||"."==l[0].slice(-1));)l[0]=l[0].slice(0,-1);else for(n&&
-1==y.indexOf(".")&&(l[0]+=".");p>x++;)l[0]+="0";y=l[0]+(1<l.length?"e"+l[1]:"");69==h&&(y=y.toUpperCase());0<=g&&(m?y="+"+y:r&&(y=" "+y))}else y=(0>g?"-":"")+"inf",q=!1;for(;y.length<v;)y=b?y+" ":!q||"-"!=y[0]&&"+"!=y[0]?(q?"0":" ")+y:y[0]+"0"+y.slice(1);97>h&&(y=y.toUpperCase());y.split("").forEach(function(H){f.push(H.charCodeAt(0))});break;case "s":q=(m=c("i8*"))?rd(m):6;k&&(q=Math.min(q,p));if(!b)for(;q<v--;)f.push(32);if(m)for(n=0;n<q;n++)f.push(I[m++>>0]);else f=f.concat(Ob("(null)".substr(0,
q),!0));if(b)for(;q<v--;)f.push(32);break;case "c":for(b&&f.push(c("i8"));0<--v;)f.push(32);b||f.push(c("i8"));break;case "n":b=c("i32*");E[b>>2]=f.length;break;case "%":f.push(g);break;default:for(n=l;n<a+2;n++)f.push(D[n>>0])}a+=2}else f.push(g),a+=1}return f}
function sd(a){if(!a||!a.callee||!a.callee.name)return[null,"",""];var b=a.callee.name,c="(",d=!0,f;for(f in a){var g=a[f];d||(c+=", ");d=!1;c="number"===typeof g||"string"===typeof g?c+g:c+("("+typeof g+")")}c+=")";a=(a=a.callee.caller)?a.arguments:[];d&&(c="");return[a,b,c]}
function td(a){a:{var b=Error();if(!b.stack){try{throw Error();}catch(p){b=p}if(!b.stack){b="(no stack trace available)";break a}}b=b.stack.toString()}b=b.slice(b.indexOf("\n",Math.max(b.lastIndexOf("_emscripten_log"),b.lastIndexOf("_emscripten_get_callstack")))+1);a&32&&ra("EM_LOG_DEMANGLE is deprecated; ignoring");a&8&&"undefined"===typeof emscripten_source_map&&(ra('Source map information is not available, emscripten_log with EM_LOG_C_STACK will be ignored. Build with "--pre-js $EMSCRIPTEN/src/emscripten-source-map.min.js" linker flag to add source map loading to code.'),
a=a^8|16);var c=null;if(a&128)for(c=sd(arguments);0<=c[1].indexOf("_emscripten_");)c=sd(c[0]);var d=b.split("\n");b="";var f=/\s*(.*?)@(.*?):([0-9]+):([0-9]+)/,g=/\s*(.*?)@(.*):(.*)(:(.*))?/,h=/\s*at (.*?) \((.*):(.*):(.*)\)/,l;for(l in d){var m=d[l],n;if((n=h.exec(m))&&5==n.length){m=n[1];var q=n[2];var r=n[3];n=n[4]}else if((n=f.exec(m))||(n=g.exec(m)),n&&4<=n.length)m=n[1],q=n[2],r=n[3],n=n[4]|0;else{b+=m+"\n";continue}var v=!1;if(a&8){var k=emscripten_source_map.ee({line:r,Qc:n});if(v=k&&k.source)a&
64&&(k.source=k.source.substring(k.source.replace(/\\/g,"/").lastIndexOf("/")+1)),b+="    at "+m+" ("+k.source+":"+k.line+":"+k.Qc+")\n"}if(a&16||!v)a&64&&(q=q.substring(q.replace(/\\/g,"/").lastIndexOf("/")+1)),b+=(v?"     = "+m:"    at "+m)+" ("+q+":"+r+":"+n+")\n";a&128&&c[0]&&(c[1]==m&&0<c[2].length&&(b=b.replace(/\s+$/,""),b+=" with values: "+c[1]+c[2]+"\n"),c=sd(c[0]))}return b=b.replace(/\s+$/,"")}
function T(a,b){for(var c=arguments.length-2,d=ud(),f=vd(8*c),g=f>>3,h=0;h<c;h++)ya[g+h]=arguments[2+h];c=wd(a,c,f,b);yb(d);return c}var xd=[],yd=[],zd=[0,"undefined"!==typeof document?document:0,"undefined"!==typeof window?window:0];function Ad(a){a=2<a?J(a):a;return zd[a]||("undefined"!==typeof document?document.querySelector(a):void 0)}
function Bd(a,b,c){var d=Ad(a);if(!d)return-4;d.Fb&&(E[d.Fb>>2]=b,E[d.Fb+4>>2]=c);if(d.yc||!d.Kd)d.yc&&(d=d.yc),a=!1,d.Eb&&d.Eb.sb&&(a=d.Eb.sb.getParameter(2978),a=0===a[0]&&0===a[1]&&a[2]===d.width&&a[3]===d.height),d.width=b,d.height=c,a&&d.Eb.sb.viewport(0,0,b,c);else{if(d.Fb){a=a?J(a):"";d=E[d.Fb+8>>2];var f=ud(),g=vd(12),h=0;if(a){h=Ga(a)+1;var l=G(h);Fa(a,I,l,h);h=l}E[g>>2]=h;E[g+4>>2]=b;E[g+8>>2]=c;Cd(0,d,657457152,0,h,g);yb(f);return 1}return-4}return 0}
function Dd(a,b,c){return z?T(4,1,a,b,c):Bd(a,b,c)}function Ed(){if(!Ab())try{if(z){var a=Ca;z?O.Gc(a):wb(a);w&&process.exit(a);throw"unwind";}wb(Ca)}catch(b){if(!(b instanceof oa))throw b;}}function Fd(a){try{a()}catch(b){if(b instanceof oa)return;if("unwind"!==b)throw b&&"object"===typeof b&&b.stack&&t("exception thrown: "+[b,b.stack]),b;}z&&Ed()}var Gd=!1,Hd=null,Id=0,Jd=null,Kd=0,Ld=0,Md=0,Nd=0,Od=[],Pd={},Qd,Rd,Sd,Td=!1,Ud=!1,Vd=[];
function Ec(){function a(){Ud=document.pointerLockElement===e.canvas||document.mozPointerLockElement===e.canvas||document.webkitPointerLockElement===e.canvas||document.msPointerLockElement===e.canvas}e.preloadPlugins||(e.preloadPlugins=[]);if(!Wd){Wd=!0;try{Xd=!0}catch(c){Xd=!1,console.log("warning: no blob constructor, cannot create blobs with mimetypes")}Yd="undefined"!=typeof MozBlobBuilder?MozBlobBuilder:"undefined"!=typeof WebKitBlobBuilder?WebKitBlobBuilder:Xd?null:console.log("warning: no BlobBuilder");
Zd="undefined"!=typeof window?window.URL?window.URL:window.webkitURL:void 0;e.xc||"undefined"!==typeof Zd||(console.log("warning: Browser does not support creating object URLs. Built-in browser image decoding will not be available."),e.xc=!0);e.preloadPlugins.push({canHandle:function(c){return!e.xc&&/\.(jpg|jpeg|png|bmp)$/i.test(c)},handle:function(c,d,f,g){var h=null;if(Xd)try{h=new Blob([c],{type:$d(d)}),h.size!==c.length&&(h=new Blob([(new Uint8Array(c)).buffer],{type:$d(d)}))}catch(n){ra("Blob constructor present but fails: "+
n+"; falling back to blob builder")}h||(h=new Yd,h.append((new Uint8Array(c)).buffer),h=h.getBlob());var l=Zd.createObjectURL(h),m=new Image;m.onload=function(){assert(m.complete,"Image "+d+" could not be decoded");var n=document.createElement("canvas");n.width=m.width;n.height=m.height;n.getContext("2d").drawImage(m,0,0);e.preloadedImages[d]=n;Zd.revokeObjectURL(l);f&&f(c)};m.onerror=function(){console.log("Image "+l+" could not be decoded");g&&g()};m.src=l}});e.preloadPlugins.push({canHandle:function(c){return!e.be&&
c.substr(-4)in{".ogg":1,".wav":1,".mp3":1}},handle:function(c,d,f,g){function h(r){m||(m=!0,e.preloadedAudios[d]=r,f&&f(c))}function l(){m||(m=!0,e.preloadedAudios[d]=new Audio,g&&g())}var m=!1;if(Xd){try{var n=new Blob([c],{type:$d(d)})}catch(r){return l()}n=Zd.createObjectURL(n);var q=new Audio;q.addEventListener("canplaythrough",function(){h(q)},!1);q.onerror=function(){if(!m){console.log("warning: browser could not fully decode audio "+d+", trying slower base64 approach");for(var r="",v=0,k=0,
p=0;p<c.length;p++)for(v=v<<8|c[p],k+=8;6<=k;){var x=v>>k-6&63;k-=6;r+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[x]}2==k?(r+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(v&3)<<4],r+="=="):4==k&&(r+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(v&15)<<2],r+="=");q.src="data:audio/x-"+d.substr(-3)+";base64,"+r;h(q)}};q.src=n;ae(function(){h(q)})}else return l()}});var b=e.canvas;b&&(b.requestPointerLock=b.requestPointerLock||b.mozRequestPointerLock||
b.webkitRequestPointerLock||b.msRequestPointerLock||function(){},b.exitPointerLock=document.exitPointerLock||document.mozExitPointerLock||document.webkitExitPointerLock||document.msExitPointerLock||function(){},b.exitPointerLock=b.exitPointerLock.bind(document),document.addEventListener("pointerlockchange",a,!1),document.addEventListener("mozpointerlockchange",a,!1),document.addEventListener("webkitpointerlockchange",a,!1),document.addEventListener("mspointerlockchange",a,!1),e.elementPointerLock&&
b.addEventListener("click",function(c){!Ud&&e.canvas.requestPointerLock&&(e.canvas.requestPointerLock(),c.preventDefault())},!1))}}
function be(a,b,c,d){if(b&&e.Ab&&a==e.canvas)return e.Ab;var f;if(b){var g={antialias:!1,alpha:!1,rc:2};if(d)for(var h in d)g[h]=d[h];if("undefined"!==typeof ce&&(f=de(a,g)))var l=ee[f].sb}else l=a.getContext("2d");if(!l)return null;c&&(b||assert("undefined"===typeof X,"cannot set in module if GLctx is used, but we are a non-GL context that would replace it"),e.Ab=l,b&&(fe=ee[f],e.Ab=X=fe&&fe.sb),e.ke=b,Vd.forEach(function(m){m()}),Ec());return l}var ge=!1,he=void 0,ie=void 0;
function je(a,b){function c(){Td=!1;var g=d.parentNode;(document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===g?(d.exitFullscreen=ke,he&&d.requestPointerLock(),Td=!0,ie?("undefined"!=typeof SDL&&(E[SDL.screen>>2]=K[SDL.screen>>2]|8388608),le(e.canvas),me()):le(d)):(g.parentNode.insertBefore(d,g),g.parentNode.removeChild(g),ie?("undefined"!=typeof SDL&&(E[SDL.screen>>2]=K[SDL.screen>>2]&
-8388609),le(e.canvas),me()):le(d));if(e.onFullScreen)e.onFullScreen(Td);if(e.onFullscreen)e.onFullscreen(Td)}he=a;ie=b;"undefined"===typeof he&&(he=!0);"undefined"===typeof ie&&(ie=!1);var d=e.canvas;ge||(ge=!0,document.addEventListener("fullscreenchange",c,!1),document.addEventListener("mozfullscreenchange",c,!1),document.addEventListener("webkitfullscreenchange",c,!1),document.addEventListener("MSFullscreenChange",c,!1));var f=document.createElement("div");d.parentNode.insertBefore(f,d);f.appendChild(d);
f.requestFullscreen=f.requestFullscreen||f.mozRequestFullScreen||f.msRequestFullscreen||(f.webkitRequestFullscreen?function(){f.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT)}:null)||(f.webkitRequestFullScreen?function(){f.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT)}:null);f.requestFullscreen()}
function ke(){if(!Td)return!1;(document.exitFullscreen||document.cancelFullScreen||document.mozCancelFullScreen||document.msExitFullscreen||document.webkitCancelFullScreen||function(){}).apply(document,[]);return!0}var ne=0;function oe(a){if("function"===typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===ne)ne=b+1E3/60;else for(;b+2>=ne;)ne+=1E3/60;setTimeout(a,Math.max(ne-b,0))}}function ae(a){zb+=1;setTimeout(function(){--zb;Fd(a)},1E4)}
function $d(a){return{jpg:"image/jpeg",jpeg:"image/jpeg",png:"image/png",bmp:"image/bmp",ogg:"audio/ogg",wav:"audio/wav",mp3:"audio/mpeg"}[a.substr(a.lastIndexOf(".")+1)]}var pe=0,qe=0,re=0,se=0;
function te(a){if(Ud)"mousemove"!=a.type&&"mozMovementX"in a?re=se=0:(re=a.movementX||a.mozMovementX||a.webkitMovementX||0,se=a.movementY||a.mozMovementY||a.webkitMovementY||0),"undefined"!=typeof SDL?(pe=SDL.Zd+re,qe=SDL.$d+se):(pe+=re,qe+=se);else{var b=e.canvas.getBoundingClientRect(),c=e.canvas.width,d=e.canvas.height,f="undefined"!==typeof window.scrollX?window.scrollX:window.pageXOffset,g="undefined"!==typeof window.scrollY?window.scrollY:window.pageYOffset;"touchstart"!==a.type&&"touchend"!==
a.type&&"touchmove"!==a.type&&(f=a.pageX-(f+b.left),a=a.pageY-(g+b.top),f*=c/b.width,a*=d/b.height,re=f-pe,se=a-qe,pe=f,qe=a)}}function Fc(a,b,c){var d="al "+a;ka(a,function(f){assert(f,'Loading data file "'+a+'" failed (no arrayBuffer).');b(new Uint8Array(f));d&&fb(d)},function(){if(c)c();else throw'Loading data file "'+a+'" failed.';});d&&eb(d)}var ue=[];function me(){var a=e.canvas;ue.forEach(function(b){b(a.width,a.height)})}function ve(a,b,c){le(e.canvas,a,b);c||me()}
function le(a,b,c){b&&c?(a.Ed=b,a.Vc=c):(b=a.Ed,c=a.Vc);var d=b,f=c;e.forcedAspectRatio&&0<e.forcedAspectRatio&&(d/f<e.forcedAspectRatio?d=Math.round(f*e.forcedAspectRatio):f=Math.round(d/e.forcedAspectRatio));if((document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===a.parentNode&&"undefined"!=typeof screen){var g=Math.min(screen.width/d,screen.height/f);d=Math.round(d*g);f=Math.round(f*
g)}ie?(a.width!=d&&(a.width=d),a.height!=f&&(a.height=f),"undefined"!=typeof a.style&&(a.style.removeProperty("width"),a.style.removeProperty("height"))):(a.width!=b&&(a.width=b),a.height!=c&&(a.height=c),"undefined"!=typeof a.style&&(d!=b||f!=c?(a.style.setProperty("width",d+"px","important"),a.style.setProperty("height",f+"px","important")):(a.style.removeProperty("width"),a.style.removeProperty("height"))))}var Wd,Xd,Yd,Zd;
function we(a,b){Ld=a;Md=b;if(Jd)if(Gd||(zb+=1,Gd=!0),0==a)Hd=function(){var d=Math.max(0,Rd+b-Bb())|0;setTimeout(Sd,d)};else if(1==a)Hd=function(){oe(Sd)};else if(2==a){if("undefined"===typeof setImmediate){var c=[];addEventListener("message",function(d){if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);setImmediate=function(d){c.push(d);u?(void 0===e.setImmediates&&(e.setImmediates=[]),e.setImmediates.push(d),postMessage({target:"setimmediate"})):postMessage("setimmediate",
"*")}}Hd=function(){setImmediate(Sd)}}}
function xe(a,b,c,d,f){function g(){return h<Id?(--zb,Ed(),!1):!0}assert(!Jd,"emscripten_set_main_loop: there can only be one main loop function at once: call emscripten_cancel_main_loop to cancel the previous one before setting a new one with different parameters.");Jd=a;Kd=d;var h=Id;Gd=!1;Sd=function(){if(!Ba)if(0<Od.length){var l=Date.now(),m=Od.shift();m.Tc(m.tb);if(Qd){var n=Qd,q=0==n%1?n-1:Math.floor(n);Qd=m.Ld?q:(8*n+(q+.5))/9}console.log('main loop blocker "'+m.name+'" took '+(Date.now()-
l)+" ms");e.setStatus&&(l=e.statusMessage||"Please wait...",m=Qd,n=Pd.Qd,m?m<n?e.setStatus(l+" ("+(n-m)+"/"+n+")"):e.setStatus(l):e.setStatus(""));g()&&setTimeout(Sd,0)}else g()&&(Nd=Nd+1|0,1==Ld&&1<Md&&0!=Nd%Md?Hd():(0==Ld&&(Rd=Bb()),Ba||e.preMainLoop&&!1===e.preMainLoop()||(Fd(a),e.postMainLoop&&e.postMainLoop()),g()&&("object"===typeof SDL&&SDL.audio&&SDL.audio.gd&&SDL.audio.gd(),Hd())))};f||(b&&0<b?we(0,1E3/b):we(1,1),Hd());if(c)throw"unwind";}var ye=1,ze=[],Ae=[],Be=[],Ce=[],De=[],ee={},Ee={};
function Fe(a){for(var b=ye++,c=a.length;c<b;c++)a[c]=null;return b}function de(a,b){a.lc||(a.lc=a.getContext,a.getContext=function(d,f){f=a.lc(d,f);return"webgl"==d==f instanceof WebGLRenderingContext?f:null});var c=a.getContext("webgl2",b);return c?Ge(c,b):0}function Ge(a,b){var c=G(8);E[c+4>>2]=rb();var d={Td:c,attributes:b,version:b.rc,sb:a};a.canvas&&(a.canvas.Eb=d);ee[c]=d;("undefined"===typeof b.hc||b.hc)&&He(d);return c}
function He(a){a||(a=fe);if(!a.Yc){a.Yc=!0;var b=a.sb;b.Od=b.getExtension("WEBGL_draw_instanced_base_vertex_base_instance");b.Xd=b.getExtension("WEBGL_multi_draw_instanced_base_vertex_base_instance");b.Pd=b.getExtension("EXT_disjoint_timer_query");b.ae=b.getExtension("WEBGL_multi_draw");(b.getSupportedExtensions()||[]).forEach(function(c){0>c.indexOf("lose_context")&&0>c.indexOf("debug")&&b.getExtension(c)})}}var ce={},Ie,fe,Je=["default","low-power","high-performance"],Ke={};
function Le(){if(!Me){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"===typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:ca||"./this.program"},b;for(b in Ke)a[b]=Ke[b];var c=[];for(b in a)c.push(b+"="+a[b]);Me=c}return Me}var Me;
function Ne(a,b){if(z)return T(5,1,a,b);try{var c=0;Le().forEach(function(d,f){var g=b+c;f=E[a+4*f>>2]=g;for(g=0;g<d.length;++g)D[f++>>0]=d.charCodeAt(g);D[f>>0]=0;c+=d.length+1});return 0}catch(d){return"undefined"!==typeof Gc&&d instanceof Q||C(d),d.lb}}function Oe(a,b){if(z)return T(6,1,a,b);try{var c=Le();E[a>>2]=c.length;var d=0;c.forEach(function(f){d+=f.length+1});E[b>>2]=d;return 0}catch(f){return"undefined"!==typeof Gc&&f instanceof Q||C(f),f.lb}}
function Pe(a){if(z)return T(7,1,a);try{var b=Jc(a);uc(b);return 0}catch(c){return"undefined"!==typeof Gc&&c instanceof Q||C(c),c.lb}}
function Qe(a,b,c,d){if(z)return T(8,1,a,b,c,d);try{a:{for(var f=Jc(a),g=a=0;g<c;g++){var h=E[b+(8*g+4)>>2],l=f,m=E[b+8*g>>2],n=h,q=void 0,r=D;if(0>n||0>q)throw new Q(28);if(null===l.fd)throw new Q(8);if(1===(l.flags&2097155))throw new Q(8);if(16384===(l.node.mode&61440))throw new Q(31);if(!l.$a.read)throw new Q(28);var v="undefined"!==typeof q;if(!v)q=l.position;else if(!l.seekable)throw new Q(70);var k=l.$a.read(l,r,m,n,q);v||(l.position+=k);var p=k;if(0>p){var x=-1;break a}a+=p;if(p<h)break}x=
a}E[d>>2]=x;return 0}catch(A){return"undefined"!==typeof Gc&&A instanceof Q||C(A),A.lb}}
function Re(a,b,c,d,f){if(z)return T(9,1,a,b,c,d,f);try{var g=Jc(a);a=4294967296*c+(b>>>0);if(-9007199254740992>=a||9007199254740992<=a)return-61;vc(g,a,d);wa=[g.position>>>0,(F=g.position,1<=+Math.abs(F)?0<F?(Math.min(+Math.floor(F/4294967296),4294967295)|0)>>>0:~~+Math.ceil((F-+(~~F>>>0))/4294967296)>>>0:0)];E[f>>2]=wa[0];E[f+4>>2]=wa[1];g.Wb&&0===a&&0===d&&(g.Wb=null);return 0}catch(h){return"undefined"!==typeof Gc&&h instanceof Q||C(h),h.lb}}
function Se(a,b,c,d){if(z)return T(10,1,a,b,c,d);try{a:{for(var f=Jc(a),g=a=0;g<c;g++){var h=wc(f,D,E[b+8*g>>2],E[b+(8*g+4)>>2],void 0);if(0>h){var l=-1;break a}a+=h}l=a}E[d>>2]=l;return 0}catch(m){return"undefined"!==typeof Gc&&m instanceof Q||C(m),m.lb}}function Te(a,b,c,d){for(var f=0;f<a;f++){var g=X[c](),h=g&&Fe(d);g?(g.name=h,d[h]=g):Ie||(Ie=1282);E[b+4*f>>2]=h}}
function Ue(a,b,c,d){this.id=a;this.y=this.x=0;this.Vb=!1;this.Fc=this.Ec=0;this.width=b;this.height=c;this.Dc=b;this.Cc=c;this.title=d;this.attributes=Ve;this.buttons=0;this.keys=[];this.Qb=[];this.dc=this.oc=this.Rb=this.Bc=this.Gb=this.fc=this.vc=this.kc=this.Nb=this.title=null}
var Y=null,Z=null,Ve=null,We={131073:0,131074:0,131075:1,131076:1,131077:1,135169:8,135170:8,135171:8,135172:8,135173:24,135174:8,135175:0,135176:0,135177:0,135178:0,135179:0,135180:0,135181:0,135182:0,135183:0,139265:196609,139266:1,139267:0,139268:0,139269:0,139270:0,139271:0,139272:0};
function Xe(a){switch(a){case 32:return 32;case 222:return 39;case 188:return 44;case 173:return 45;case 189:return 45;case 190:return 46;case 191:return 47;case 48:return 48;case 49:return 49;case 50:return 50;case 51:return 51;case 52:return 52;case 53:return 53;case 54:return 54;case 55:return 55;case 56:return 56;case 57:return 57;case 59:return 59;case 61:return 61;case 187:return 61;case 65:return 65;case 66:return 66;case 67:return 67;case 68:return 68;case 69:return 69;case 70:return 70;case 71:return 71;
case 72:return 72;case 73:return 73;case 74:return 74;case 75:return 75;case 76:return 76;case 77:return 77;case 78:return 78;case 79:return 79;case 80:return 80;case 81:return 81;case 82:return 82;case 83:return 83;case 84:return 84;case 85:return 85;case 86:return 86;case 87:return 87;case 88:return 88;case 89:return 89;case 90:return 90;case 219:return 91;case 220:return 92;case 221:return 93;case 192:return 94;case 27:return 256;case 13:return 257;case 9:return 258;case 8:return 259;case 45:return 260;
case 46:return 261;case 39:return 262;case 37:return 263;case 40:return 264;case 38:return 265;case 33:return 266;case 34:return 267;case 36:return 268;case 35:return 269;case 20:return 280;case 145:return 281;case 144:return 282;case 44:return 283;case 19:return 284;case 112:return 290;case 113:return 291;case 114:return 292;case 115:return 293;case 116:return 294;case 117:return 295;case 118:return 296;case 119:return 297;case 120:return 298;case 121:return 299;case 122:return 300;case 123:return 301;
case 124:return 302;case 125:return 303;case 126:return 304;case 127:return 305;case 128:return 306;case 129:return 307;case 130:return 308;case 131:return 309;case 132:return 310;case 133:return 311;case 134:return 312;case 135:return 313;case 136:return 314;case 96:return 320;case 97:return 321;case 98:return 322;case 99:return 323;case 100:return 324;case 101:return 325;case 102:return 326;case 103:return 327;case 104:return 328;case 105:return 329;case 110:return 330;case 111:return 331;case 106:return 332;
case 109:return 333;case 107:return 334;case 16:return 340;case 17:return 341;case 18:return 342;case 91:return 343;case 93:return 348;default:return-1}}function Ye(){var a=Y,b=0;a.keys[340]&&(b|=1);a.keys[341]&&(b|=2);a.keys[342]&&(b|=4);a.keys[343]&&(b|=8);return b}function Ze(a){Y&&Y.dc&&!a.ctrlKey&&!a.metaKey&&(a=a.charCode,0==a||0<=a&&31>=a||L.get(Y.dc)(Y.id,a))}
function $e(a,b){if(Y){var c=Xe(a);if(-1!=c){var d=b&&Y.keys[c];Y.keys[c]=b;Y.Qb[a]=b;Y.oc&&(d&&(b=2),L.get(Y.oc)(Y.id,c,a,b,Ye()))}}}function af(){bf()}function cf(){bf()}function df(a){$e(a.keyCode,1);8!==a.keyCode&&9!==a.keyCode||a.preventDefault()}function ef(a){$e(a.keyCode,0)}function ff(){if(Y)for(var a=0;a<Y.Qb.length;++a)Y.Qb[a]&&$e(a,0)}function gf(a){Y&&(te(a),a.target==e.canvas&&Y.fc&&L.get(Y.fc)(Y.id,pe,qe))}function hf(a){Y&&a.target==e.canvas&&Y.Gb&&L.get(Y.Gb)(Y.id,1)}
function jf(a){Y&&a.target==e.canvas&&Y.Gb&&L.get(Y.Gb)(Y.id,0)}function kf(a,b){if(Y&&(te(a),a.target==e.canvas)){var c=a.button;0<c&&(c=1==c?2:1);if(1==b){Y.buttons|=1<<c;try{a.target.setCapture()}catch(d){}}else Y.buttons&=~(1<<c);Y.vc&&L.get(Y.vc)(Y.id,c,b,Ye())}}function lf(a){Y&&kf(a,1)}function mf(a){Y&&kf(a,0)}
function nf(a){switch(a.type){case "DOMMouseScroll":break;case "mousewheel":break;case "wheel":switch(a.deltaMode){case 0:break;case 1:break;case 2:break;default:throw"unrecognized mouse wheel delta mode: "+a.deltaMode;}break;default:throw"unrecognized mouse wheel event: "+a.type;}if(Y&&Y.Bc&&a.target==e.canvas){if("mousewheel"==a.type){var b=a.wheelDeltaX;var c=a.wheelDeltaY}else b=a.deltaX,c=a.deltaY;L.get(Y.Bc)(Y.id,b,c);a.preventDefault()}}var of={},pf=null,qf=null;
function bf(){if(Nd!==qf||!Nd){pf=navigator.getGamepads?navigator.getGamepads():navigator.webkitGetGamepads?navigator.webkitGetGamepads:null;qf=Nd;for(var a=0;a<pf.length;++a){var b=pf[a];if(b){of[a]||(console.log("glfw joystick connected:",a),of[a]={id:Da(Ob(b.id)),Id:b.buttons.length,Gd:b.axes.length,buttons:Da(Array(b.buttons.length)),axes:Da(Array(4*b.axes.length))});for(var c=of[a],d=0;d<b.buttons.length;++d)ua(c.buttons+d,b.buttons[d].pressed,"i8");for(d=0;d<b.axes.length;++d)ua(c.axes+4*d,
b.axes[d],"float")}else of[a]&&(console.log("glfw joystick disconnected",a),P(of[a].id),P(of[a].buttons),P(of[a].axes),delete of[a])}}}
function rf(a){function b(l){var m="/.glfw_dropped_files/"+l.name.replace(/\//g,"_"),n=new FileReader;n.onloadend=function(r){if(2!=n.readyState)++g,console.log("failed to read dropped file: "+l.name+": "+n.error);else{var v=new Uint8Array(r.target.result);var k=k||{};k.flags=k.flags||577;r=Ya(m,k.flags,k.mode);if("string"===typeof v){var p=new Uint8Array(Ga(v)+1);v=Fa(v,p,0,p.length);wc(r,p,0,v,void 0,k.Pc)}else if(ArrayBuffer.isView(v))wc(r,v,0,v.byteLength,void 0,k.Pc);else throw Error("Unsupported data type");
uc(r);if(++g===f){L.get(Y.Rb)(Y.id,f,c);for(k=0;k<d.length;++k)P(d[k]);P(c)}}};n.readAsArrayBuffer(l);var q=Da(Ob(m));d.push(q);ua(c+4*h,q,"i8*")}if(Y&&Y.Rb&&a.dataTransfer&&a.dataTransfer.files&&0!=a.dataTransfer.files.length){a.preventDefault();var c=Da(Array(4*a.dataTransfer.files.length)),d=[],f=a.dataTransfer.files.length,g=0;yc("/",".glfw_dropped_files");for(var h=0;h<f;++h)b(a.dataTransfer.files[h]);return!1}}function sf(a){if(Y&&Y.Rb)return a.preventDefault(),!1}
function vb(a){if(z)throw"Internal Error! spawnThread() can only ever be called from main application thread!";var b=O.Uc();if(!b)return 6;if(void 0!==b.fb)throw"Internal error!";if(!a.Ib)throw"Internal error, no pthread ptr!";O.pb.push(b);for(var c=G(512),d=0;128>d;++d)E[c+4*d>>2]=0;var f=a.rb+a.yb;d=O.ib[a.Ib]={worker:b,rb:a.rb,yb:a.yb,Pb:a.Pb,jb:a.Ib};var g=d.jb>>2;Atomics.store(K,g+16,a.detached);Atomics.store(K,g+25,c);Atomics.store(K,g+10,d.jb);Atomics.store(K,g+20,a.yb);Atomics.store(K,g+19,
f);Atomics.store(K,g+26,a.yb);Atomics.store(K,g+28,f);Atomics.store(K,g+29,a.detached);c=tf()+40;Atomics.store(K,g+43,c);b.fb=d;var h={cmd:"run",start_routine:a.ud,arg:a.tb,threadInfoStruct:a.Ib,stackBase:a.rb,stackSize:a.yb};b.Cb=function(){h.time=performance.now();b.postMessage(h,a.Cd)};b.loaded&&(b.Cb(),delete b.Cb);return 0}function uf(a){return 0===a%4&&(0!==a%100||0===a%400)}function vf(a,b){for(var c=0,d=0;d<=b;c+=a[d++]);return c}
var wf=[31,29,31,30,31,30,31,31,30,31,30,31],xf=[31,28,31,30,31,30,31,31,30,31,30,31];function yf(a,b){for(a=new Date(a.getTime());0<b;){var c=a.getMonth(),d=(uf(a.getFullYear())?wf:xf)[c];if(b>d-a.getDate())b-=d-a.getDate()+1,a.setDate(1),11>c?a.setMonth(c+1):(a.setMonth(0),a.setFullYear(a.getFullYear()+1));else{a.setDate(a.getDate()+b);break}}return a}
function zf(a,b,c,d){function f(k,p,x){for(k="number"===typeof k?k.toString():k||"";k.length<p;)k=x[0]+k;return k}function g(k,p){return f(k,p,"0")}function h(k,p){function x(y){return 0>y?-1:0<y?1:0}var A;0===(A=x(k.getFullYear()-p.getFullYear()))&&0===(A=x(k.getMonth()-p.getMonth()))&&(A=x(k.getDate()-p.getDate()));return A}function l(k){switch(k.getDay()){case 0:return new Date(k.getFullYear()-1,11,29);case 1:return k;case 2:return new Date(k.getFullYear(),0,3);case 3:return new Date(k.getFullYear(),
0,2);case 4:return new Date(k.getFullYear(),0,1);case 5:return new Date(k.getFullYear()-1,11,31);case 6:return new Date(k.getFullYear()-1,11,30)}}function m(k){k=yf(new Date(k.bb+1900,0,1),k.Mb);var p=new Date(k.getFullYear()+1,0,4),x=l(new Date(k.getFullYear(),0,4));p=l(p);return 0>=h(x,k)?0>=h(p,k)?k.getFullYear()+1:k.getFullYear():k.getFullYear()-1}var n=E[d+40>>2];d={Ad:E[d>>2],zd:E[d+4>>2],Kb:E[d+8>>2],Db:E[d+12>>2],zb:E[d+16>>2],bb:E[d+20>>2],Lb:E[d+24>>2],Mb:E[d+28>>2],je:E[d+32>>2],yd:E[d+
36>>2],Bd:n?J(n):""};c=J(c);n={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S","%Ec":"%c","%EC":"%C","%Ex":"%m/%d/%y","%EX":"%H:%M:%S","%Ey":"%y","%EY":"%Y","%Od":"%d","%Oe":"%e","%OH":"%H","%OI":"%I","%Om":"%m","%OM":"%M","%OS":"%S","%Ou":"%u","%OU":"%U","%OV":"%V","%Ow":"%w","%OW":"%W","%Oy":"%y"};for(var q in n)c=c.replace(new RegExp(q,"g"),n[q]);var r="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),
v="January February March April May June July August September October November December".split(" ");n={"%a":function(k){return r[k.Lb].substring(0,3)},"%A":function(k){return r[k.Lb]},"%b":function(k){return v[k.zb].substring(0,3)},"%B":function(k){return v[k.zb]},"%C":function(k){return g((k.bb+1900)/100|0,2)},"%d":function(k){return g(k.Db,2)},"%e":function(k){return f(k.Db,2," ")},"%g":function(k){return m(k).toString().substring(2)},"%G":function(k){return m(k)},"%H":function(k){return g(k.Kb,
2)},"%I":function(k){k=k.Kb;0==k?k=12:12<k&&(k-=12);return g(k,2)},"%j":function(k){return g(k.Db+vf(uf(k.bb+1900)?wf:xf,k.zb-1),3)},"%m":function(k){return g(k.zb+1,2)},"%M":function(k){return g(k.zd,2)},"%n":function(){return"\n"},"%p":function(k){return 0<=k.Kb&&12>k.Kb?"AM":"PM"},"%S":function(k){return g(k.Ad,2)},"%t":function(){return"\t"},"%u":function(k){return k.Lb||7},"%U":function(k){var p=new Date(k.bb+1900,0,1),x=0===p.getDay()?p:yf(p,7-p.getDay());k=new Date(k.bb+1900,k.zb,k.Db);return 0>
h(x,k)?g(Math.ceil((31-x.getDate()+(vf(uf(k.getFullYear())?wf:xf,k.getMonth()-1)-31)+k.getDate())/7),2):0===h(x,p)?"01":"00"},"%V":function(k){var p=new Date(k.bb+1901,0,4),x=l(new Date(k.bb+1900,0,4));p=l(p);var A=yf(new Date(k.bb+1900,0,1),k.Mb);return 0>h(A,x)?"53":0>=h(p,A)?"01":g(Math.ceil((x.getFullYear()<k.bb+1900?k.Mb+32-x.getDate():k.Mb+1-x.getDate())/7),2)},"%w":function(k){return k.Lb},"%W":function(k){var p=new Date(k.bb,0,1),x=1===p.getDay()?p:yf(p,0===p.getDay()?1:7-p.getDay()+1);k=
new Date(k.bb+1900,k.zb,k.Db);return 0>h(x,k)?g(Math.ceil((31-x.getDate()+(vf(uf(k.getFullYear())?wf:xf,k.getMonth()-1)-31)+k.getDate())/7),2):0===h(x,p)?"01":"00"},"%y":function(k){return(k.bb+1900).toString().substring(2)},"%Y":function(k){return k.bb+1900},"%z":function(k){k=k.yd;var p=0<=k;k=Math.abs(k)/60;return(p?"+":"-")+String("0000"+(k/60*100+k%60)).slice(-4)},"%Z":function(k){return k.Bd},"%%":function(){return"%"}};for(q in n)0<=c.indexOf(q)&&(c=c.replace(new RegExp(q,"g"),n[q](d)));q=
Ob(c,!1);if(q.length>b)return 0;D.set(q,a);return q.length-1}z||O.Zc();function hc(a,b,c,d){a||(a=this);this.parent=a;this.mb=a.mb;this.Bb=null;this.id=Yb++;this.name=b;this.mode=c;this.Za={};this.$a={};this.rdev=d}
Object.defineProperties(hc.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}},dd:{get:function(){return 16384===(this.mode&61440)}},cd:{get:function(){return 8192===(this.mode&61440)}}});Wa();Zb=Array(4096);oc(R,"/");S("/tmp");S("/home");S("/home/web_user");
(function(){S("/dev");Mb(259,{read:function(){return 0},write:function(b,c,d,f){return f}});qc("/dev/null",259);Lb(1280,Pb);Lb(1536,Qb);qc("/dev/tty",1280);qc("/dev/tty1",1536);var a=Ib();M("/dev","random",a);M("/dev","urandom",a);S("/dev/shm");S("/dev/shm/tmp")})();
(function(){S("/proc");var a=S("/proc/self");S("/proc/self/fd");oc({mb:function(){var b=Sb(a,"fd",16895,73);b.Za={lookup:function(c,d){var f=Xb[+d];if(!f)throw new Q(8);c={parent:null,mb:{uc:"fake"},Za:{readlink:function(){return f.path}}};return c.parent=c}};return b}},"/proc/self/fd")})();e.FS_createPath=yc;e.FS_createDataFile=Ac;e.FS_createPreloadedFile=Dc;e.FS_createLazyFile=Cc;e.FS_createDevice=M;e.FS_unlink=rc;for(var Af=Array(256),Bf=0;256>Bf;++Bf)Af[Bf]=String.fromCharCode(Bf);Nc=Af;
Uc=e.BindingError=Tc("BindingError");Vc=e.InternalError=Tc("InternalError");e.count_emval_handles=function(){for(var a=0,b=5;b<W.length;++b)void 0!==W[b]&&++a;return a};e.get_first_emval=function(){for(var a=5;a<W.length;++a)if(void 0!==W[a])return W[a];return null};jd=e.UnboundTypeError=Tc("UnboundTypeError");e.requestFullscreen=function(a,b){je(a,b)};e.requestAnimationFrame=function(a){oe(a)};e.setCanvasSize=function(a,b,c){ve(a,b,c)};e.pauseMainLoop=function(){Hd=null;Id++};
e.resumeMainLoop=function(){Id++;var a=Ld,b=Md,c=Jd;Jd=null;xe(c,0,!1,Kd,!0);we(a,b);Hd()};e.getUserMedia=function(){window.getUserMedia||(window.getUserMedia=navigator.getUserMedia||navigator.mozGetUserMedia);window.getUserMedia(void 0)};e.createContext=function(a,b,c,d){return be(a,b,c,d)};var X,Cf=[null,function(a,b){if(z)return T(1,1,a,b)},Kc,Lc,Dd,Ne,Oe,Pe,Qe,Re,Se];function Ob(a,b){var c=Array(Ga(a)+1);a=Fa(a,c,0,c.length);b&&(c.length=a);return c}
var Ff={b:function(a,b,c,d){C("Assertion failed: "+J(a)+", at: "+[b?J(b):"unknown filename",c,d?J(d):"unknown function"])},c:function(a){return G(a+16)+16},d:function(a,b,c){(new Cb(a)).Xc(b,c);Db++;throw a;},Y:Kc,Z:Lc,$:function(a,b,c,d,f){var g=Mc(c);b=U(b);Xc(a,{name:b,fromWireType:function(h){return!!h},toWireType:function(h,l){return l?d:f},argPackAdvance:8,readValueFromPointer:function(h){if(1===c)var l=D;else if(2===c)l=va;else if(4===c)l=E;else throw new TypeError("Unknown boolean type size: "+
b);return this.fromWireType(l[h>>g])},nb:null})},_:function(a,b){b=U(b);Xc(a,{name:b,fromWireType:function(c){var d=W[c].value;4<c&&0===--W[c].jd&&(W[c]=void 0,Yc.push(c));return d},toWireType:function(c,d){return Zc(d)},argPackAdvance:8,readValueFromPointer:$c,nb:null})},A:function(a,b,c){c=Mc(c);b=U(b);Xc(a,{name:b,fromWireType:function(d){return d},toWireType:function(d,f){if("number"!==typeof f&&"boolean"!==typeof f)throw new TypeError('Cannot convert "'+ad(f)+'" to '+this.name);return f},argPackAdvance:8,
readValueFromPointer:bd(b,c),nb:null})},p:function(a,b,c,d,f,g){var h=gd(b,c);a=U(a);f=id(d,f);fd(a,function(){md("Cannot call "+a+" due to unbound types",h)},b-1);Wc(h,function(l){var m=[l[0],null].concat(l.slice(1)),n=l=a,q=f,r=m.length;2>r&&V("argTypes array size mismatch! Must at least get return value and 'this' types!");for(var v=null!==m[1]&&!1,k=!1,p=1;p<m.length;++p)if(null!==m[p]&&void 0===m[p].nb){k=!0;break}var x="void"!==m[0].name,A="",y="";for(p=0;p<r-2;++p)A+=(0!==p?", ":"")+"arg"+
p,y+=(0!==p?", ":"")+"arg"+p+"Wired";n="return function "+Rc(n)+"("+A+") {\nif (arguments.length !== "+(r-2)+") {\nthrowBindingError('function "+n+" called with ' + arguments.length + ' arguments, expected "+(r-2)+" args!');\n}\n";k&&(n+="var destructors = [];\n");var H=k?"destructors":"null";A="throwBindingError invoker fn runDestructors retType classParam".split(" ");q=[V,q,g,dd,m[0],m[1]];v&&(n+="var thisWired = classParam.toWireType("+H+", this);\n");for(p=0;p<r-2;++p)n+="var arg"+p+"Wired = argType"+
p+".toWireType("+H+", arg"+p+"); // "+m[p+2].name+"\n",A.push("argType"+p),q.push(m[p+2]);v&&(y="thisWired"+(0<y.length?", ":"")+y);n+=(x?"var rv = ":"")+"invoker(fn"+(0<y.length?", ":"")+y+");\n";if(k)n+="runDestructors(destructors);\n";else for(p=v?1:2;p<m.length;++p)r=1===p?"thisWired":"arg"+(p-2)+"Wired",null!==m[p].nb&&(n+=r+"_dtor("+r+"); // "+m[p].name+"\n",A.push(r+"_dtor"),q.push(m[p].nb));x&&(n+="var ret = retType.fromWireType(rv);\nreturn ret;\n");A.push(n+"}\n");m=cd(A).apply(null,q);
p=b-1;if(!e.hasOwnProperty(l))throw new Vc("Replacing nonexistant public symbol");void 0!==e[l].hb&&void 0!==p?e[l].hb[p]=m:(e[l]=m,e[l].Nc=p);return[]})},g:function(a,b,c,d,f){function g(n){return n}b=U(b);-1===f&&(f=4294967295);var h=Mc(c);if(0===d){var l=32-8*c;g=function(n){return n<<l>>>l}}var m=-1!=b.indexOf("unsigned");Xc(a,{name:b,fromWireType:g,toWireType:function(n,q){if("number"!==typeof q&&"boolean"!==typeof q)throw new TypeError('Cannot convert "'+ad(q)+'" to '+this.name);if(q<d||q>f)throw new TypeError('Passing a number "'+
ad(q)+'" from JS side to C/C++ side to an argument of type "'+b+'", which is outside the valid range ['+d+", "+f+"]!");return m?q>>>0:q|0},argPackAdvance:8,readValueFromPointer:nd(b,h,0!==d),nb:null})},f:function(a,b,c){function d(g){g>>=2;return new f(ha,K[g+1],K[g])}var f=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array][b];c=U(c);Xc(a,{name:c,fromWireType:d,argPackAdvance:8,readValueFromPointer:d},{Wc:!0})},B:function(a,b){b=U(b);var c="std::string"===
b;Xc(a,{name:b,fromWireType:function(d){var f=K[d>>2];if(c)for(var g=d+4,h=0;h<=f;++h){var l=d+4+h;if(h==f||0==I[l]){g=J(g,l-g);if(void 0===m)var m=g;else m+=String.fromCharCode(0),m+=g;g=l+1}}else{m=Array(f);for(h=0;h<f;++h)m[h]=String.fromCharCode(I[d+4+h]);m=m.join("")}P(d);return m},toWireType:function(d,f){f instanceof ArrayBuffer&&(f=new Uint8Array(f));var g="string"===typeof f;g||f instanceof Uint8Array||f instanceof Uint8ClampedArray||f instanceof Int8Array||V("Cannot pass non-string to std::string");
var h=(c&&g?function(){return Ga(f)}:function(){return f.length})(),l=G(4+h+1);K[l>>2]=h;if(c&&g)Fa(f,I,l+4,h+1);else if(g)for(g=0;g<h;++g){var m=f.charCodeAt(g);255<m&&(P(l),V("String has UTF-16 code units that do not fit in 8 bits"));I[l+4+g]=m}else for(g=0;g<h;++g)I[l+4+g]=f[g];null!==d&&d.push(P,l);return l},argPackAdvance:8,readValueFromPointer:$c,nb:function(d){P(d)}})},r:function(a,b,c){c=U(c);if(2===b){var d=Ha;var f=Ia;var g=Ja;var h=function(){return Na};var l=1}else 4===b&&(d=Ka,f=La,g=
Ma,h=function(){return K},l=2);Xc(a,{name:c,fromWireType:function(m){for(var n=K[m>>2],q=h(),r,v=m+4,k=0;k<=n;++k){var p=m+4+k*b;if(k==n||0==q[p>>l])v=d(v,p-v),void 0===r?r=v:(r+=String.fromCharCode(0),r+=v),v=p+b}P(m);return r},toWireType:function(m,n){"string"!==typeof n&&V("Cannot pass non-string to C++ string type "+c);var q=g(n),r=G(4+q+b);K[r>>2]=q>>l;f(n,r+4,q+b);null!==m&&m.push(P,r);return r},argPackAdvance:8,readValueFromPointer:$c,nb:function(m){P(m)}})},aa:function(a,b){b=U(b);Xc(a,{Ud:!0,
name:b,argPackAdvance:0,fromWireType:function(){},toWireType:function(){}})},V:function(a,b){if(a==b)postMessage({cmd:"processQueuedMainThreadWork"});else if(z)postMessage({targetThread:a,cmd:"processThreadQueue"});else{a=(a=O.ib[a])&&a.worker;if(!a)return;a.postMessage({cmd:"processThreadQueue"})}return 1},v:function(){C()},i:function(a,b,c){yd.length=0;var d;for(c>>=2;d=I[b++];)(d=105>d)&&c&1&&c++,yd.push(d?ya[c++>>1]:E[c]),++c;return mb[a].apply(null,yd)},R:function(){w||u||ra("Blocking on the main thread is very dangerous, see https://emscripten.org/docs/porting/pthreads.html#blocking-on-the-main-browser-thread")},
y:function(){},l:function(a,b,c){if(0>=a||a>D.length||a&1)return-28;if(ea){if(Atomics.load(E,a>>2)!=b)return-6;var d=performance.now();c=d+c;for(Atomics.exchange(E,ob>>2,a);;){d=performance.now();if(d>c)return Atomics.exchange(E,ob>>2,0),-73;d=Atomics.exchange(E,ob>>2,0);if(0==d)break;ub();if(Atomics.load(E,a>>2)!=b)return-6;Atomics.exchange(E,ob>>2,a)}return 0}a=Atomics.wait(E,a>>2,b,c);if("timed-out"===a)return-73;if("not-equal"===a)return-6;if("ok"===a)return 0;throw"Atomics.wait returned an unexpected value "+
a;},k:nb,m:Bb,sa:function(a,b,c){b=qd(b,c);b=Ea(b,0);a&24&&(b=b.replace(/\s+$/,""),b+=(0<b.length?"\n":"")+td(a));a&1?a&4?console.error(b):a&2?console.warn(b):a&512?console.info(b):a&256?console.debug(b):console.log(b):a&6?t(b):qa(b)},N:function(a,b,c){I.copyWithin(a,b,b+c)},S:function(a,b,c){xd.length=b;c>>=3;for(var d=0;d<b;d++)xd[d]=ya[c+d];return(0>a?mb[-a-1]:Cf[a]).apply(null,xd)},j:function(){C("OOM")},T:function(a,b,c){return Ad(a)?Bd(a,b,c):Dd(a,b,c)},x:function(){},ia:function(a,b,c,d){xe(function(){L.get(a)(b)},
c,d,b)},U:function(a,b){b>>=2;b={alpha:!!E[b],depth:!!E[b+1],stencil:!!E[b+2],antialias:!!E[b+3],premultipliedAlpha:!!E[b+4],preserveDrawingBuffer:!!E[b+5],powerPreference:Je[E[b+6]],failIfMajorPerformanceCaveat:!!E[b+7],rc:E[b+8],Yd:E[b+9],hc:E[b+10],Sc:E[b+11],fe:E[b+12],ge:E[b+13]};a=Ad(a);return!a||b.Sc?0:de(a,b)},P:Ne,Q:Oe,z:Pe,X:Qe,K:Re,W:Se,D:function(a,b){X.attachShader(Ae[a],Ce[b])},e:function(a,b){35051==a?X.Md=b:35052==a&&(X.Nd=b);X.bindBuffer(a,ze[b])},s:function(a){X.bindVertexArray(De[a])},
ka:function(a,b){X.blendFunc(a,b)},ja:function(a,b,c,d){X.blendFuncSeparate(a,b,c,d)},h:function(a,b,c,d){c?X.bufferData(a,I,d,c,b):X.bufferData(a,b,d)},u:function(a,b,c,d){X.bufferSubData(a,b,I,d,c)},oa:function(a){X.clear(a)},pa:function(a,b,c,d){X.clearColor(a,b,c,d)},E:function(a){X.compileShader(Ce[a])},ga:function(){var a=Fe(Ae),b=X.createProgram();b.name=a;Ae[a]=b;return a},G:function(a){var b=Fe(Ce);Ce[b]=X.createShader(a);return b},ra:function(a,b,c,d){X.drawArraysInstanced(a,b,c,d)},la:function(a){X.enable(a)},
o:function(a){X.enableVertexAttribArray(a)},q:function(a,b){Te(a,b,"createBuffer",ze)},ba:function(a,b){Te(a,b,"createVertexArray",De)},I:function(a,b){b=J(b);var c=0;if("]"==b[b.length-1]){var d=b.lastIndexOf("[");c="]"!=b[d+1]?parseInt(b.slice(d+1)):0;b=b.slice(0,d)}return(a=Ee[a]&&Ee[a].Ic[b])&&0<=c&&c<a[0]?a[1]+c:-1},fa:function(a){X.linkProgram(Ae[a]);var b=Ae[a];a=Ee[a]={Ic:{},sc:0,Vd:-1,Wd:-1};for(var c=a.Ic,d=X.getProgramParameter(b,35718),f=0;f<d;++f){var g=X.getActiveUniform(b,f),h=g.name;
a.sc=Math.max(a.sc,h.length+1);"]"==h.slice(-1)&&(h=h.slice(0,h.lastIndexOf("[")));var l=X.getUniformLocation(b,h);if(l){var m=Fe(Be);c[h]=[g.size,m];Be[m]=l;for(var n=1;n<g.size;++n)l=X.getUniformLocation(b,h+"["+n+"]"),m=Fe(Be),Be[m]=l}}},F:function(a,b,c,d){for(var f="",g=0;g<b;++g){var h=d?E[d+4*g>>2]:-1;f+=J(E[c+4*g>>2],0>h?void 0:h)}X.shaderSource(Ce[a],f)},H:function(a,b){X.uniform1f(Be[a],b)},ma:function(a){X.useProgram(Ae[a])},t:function(a,b){X.vertexAttribDivisor(a,b)},n:function(a,b,c,
d,f,g){X.vertexAttribPointer(a,b,c,!!d,f,g)},J:function(a,b,c,d){X.viewport(a,b,c,d)},da:function(a,b,c,d){var f;for(f=0;f<Z.length&&null!==Z[f];f++);if(0<f)throw"glfwCreateWindow only supports one window at time currently";var g=f+1;if(0>=a||0>=b)g=0;else{d?je():ve(a,b);for(f=0;f<Z.length&&null==Z[f];f++);d=0<Ve[139265];f==Z.length&&(d?e.Ab=be(e.canvas,!0,!0,{antialias:1<Ve[135181],depth:0<Ve[135173],stencil:0<Ve[135174],alpha:0<Ve[135172]}):Ec());!e.Ab&&d?g=0:(a=new Ue(g,a,b,c),g-1==Z.length?Z.push(a):
Z[g-1]=a,Y=a,g=a.id)}return g},ea:function(){if(Z)return 1;Bb();Ve=We;Z=[];Y=null;window.addEventListener("gamepadconnected",af,!0);window.addEventListener("gamepaddisconnected",cf,!0);window.addEventListener("keydown",df,!0);window.addEventListener("keypress",Ze,!0);window.addEventListener("keyup",ef,!0);window.addEventListener("blur",ff,!0);e.canvas.addEventListener("touchmove",gf,!0);e.canvas.addEventListener("touchstart",lf,!0);e.canvas.addEventListener("touchcancel",mf,!0);e.canvas.addEventListener("touchend",
mf,!0);e.canvas.addEventListener("mousemove",gf,!0);e.canvas.addEventListener("mousedown",lf,!0);e.canvas.addEventListener("mouseup",mf,!0);e.canvas.addEventListener("wheel",nf,!0);e.canvas.addEventListener("mousewheel",nf,!0);e.canvas.addEventListener("mouseenter",hf,!0);e.canvas.addEventListener("mouseleave",jf,!0);e.canvas.addEventListener("drop",rf,!0);e.canvas.addEventListener("dragover",sf,!0);ue.push(function(a,b){if(Y){var c=!0;document.fullscreen||document.fullScreen||document.mozFullScreen||
document.webkitIsFullScreen?(Y.Ec=Y.x,Y.Fc=Y.y,Y.Dc=Y.width,Y.Cc=Y.height,Y.x=Y.y=0,Y.width=screen.width,Y.height=screen.height,Y.Vb=!0):1==Y.Vb?(Y.x=Y.Ec,Y.y=Y.Fc,Y.width=Y.Dc,Y.height=Y.Cc,Y.Vb=!1):Y.width!=a||Y.height!=b?(Y.width=a,Y.height=b):c=!1;c&&(ve(Y.width,Y.height,!0),Y&&Y.Nb&&L.get(Y.Nb)(Y.id,Y.width,Y.height),Y&&Y.kc&&L.get(Y.kc)(Y.id,Y.width,Y.height))}});return 1},ca:function(){},qa:function(a,b,c){if(a=0>=a||!Z?null:Z[a-1])Y.id==a.id&&(b==screen.width&&c==screen.height?je():(ke(),
ve(b,c),a.width=b,a.height=c)),a.Nb&&L.get(a.Nb)(a.id,b,c)},na:function(){},ha:function(){window.removeEventListener("gamepadconnected",af,!0);window.removeEventListener("gamepaddisconnected",cf,!0);window.removeEventListener("keydown",df,!0);window.removeEventListener("keypress",Ze,!0);window.removeEventListener("keyup",ef,!0);window.removeEventListener("blur",ff,!0);e.canvas.removeEventListener("touchmove",gf,!0);e.canvas.removeEventListener("touchstart",lf,!0);e.canvas.removeEventListener("touchcancel",
mf,!0);e.canvas.removeEventListener("touchend",mf,!0);e.canvas.removeEventListener("mousemove",gf,!0);e.canvas.removeEventListener("mousedown",lf,!0);e.canvas.removeEventListener("mouseup",mf,!0);e.canvas.removeEventListener("wheel",nf,!0);e.canvas.removeEventListener("mousewheel",nf,!0);e.canvas.removeEventListener("mouseenter",hf,!0);e.canvas.removeEventListener("mouseleave",jf,!0);e.canvas.removeEventListener("drop",rf,!0);e.canvas.removeEventListener("dragover",sf,!0);e.canvas.width=e.canvas.height=
1;Y=Z=null},C:function(a,b){Ve[a]=b},M:function(){O.$c()},a:za,w:function(a,b,c,d){if("undefined"===typeof SharedArrayBuffer)return t("Current environment does not support SharedArrayBuffer, pthreads are not available!"),6;if(!a)return t("pthread_create called with a null thread pointer!"),28;var f=[];if(z&&0===f.length)return Df(687865856,a,b,c,d);var g=0,h=0;if(b&&-1!=b){var l=E[b>>2];l+=81920;g=E[b+8>>2];h=0!==E[b+12>>2]}else l=2097152;(b=0==g)?g=Ef(16,l):(g-=l,assert(0<g));for(var m=G(228),n=
0;57>n;++n)K[(m>>2)+n]=0;E[a>>2]=m;E[m+12>>2]=m;a=m+152;E[a>>2]=a;c={rb:g,yb:l,Pb:b,detached:h,ud:c,Ib:m,tb:d,Cd:f};return z?(c.Jd="spawnThread",postMessage(c,f),0):vb(c)},L:function(){},O:function(a,b,c,d){return zf(a,b,c,d)}};
(function(){function a(f,g){e.asm=f.exports;L=e.asm.za;Ra.unshift(e.asm.ta);O.$b.push(e.asm.ya);Aa=g;if(!z){var h=O.kb.length;O.kb.forEach(function(l){O.pc(l,function(){--h||fb("wasm-instantiate")})})}}function b(f){a(f.instance,f.module)}function c(f){return kb().then(function(g){return WebAssembly.instantiate(g,d)}).then(f,function(g){t("failed to asynchronously prepare wasm: "+g);C(g)})}var d={a:Ff};z||eb("wasm-instantiate");if(e.instantiateWasm)try{return e.instantiateWasm(d,a)}catch(f){return t("Module.instantiateWasm callback failed with error: "+
f),!1}(function(){return ta||"function"!==typeof WebAssembly.instantiateStreaming||ib()||gb("file://")||"function"!==typeof fetch?c(b):fetch(hb,{credentials:"same-origin"}).then(function(f){return WebAssembly.instantiateStreaming(f,d).then(b,function(g){t("wasm streaming compile failed: "+g);t("falling back to ArrayBuffer instantiation");return c(b)})})})();return{}})();e.___wasm_call_ctors=function(){return(e.___wasm_call_ctors=e.asm.ta).apply(null,arguments)};
e._setValues=function(){return(e._setValues=e.asm.ua).apply(null,arguments)};var rd=e._strlen=function(){return(rd=e._strlen=e.asm.va).apply(null,arguments)},G=e._malloc=function(){return(G=e._malloc=e.asm.wa).apply(null,arguments)};e._main=function(){return(e._main=e.asm.xa).apply(null,arguments)};e._emscripten_tls_init=function(){return(e._emscripten_tls_init=e.asm.ya).apply(null,arguments)};var ld=e.___getTypeName=function(){return(ld=e.___getTypeName=e.asm.Aa).apply(null,arguments)};
e.___embind_register_native_and_builtin_types=function(){return(e.___embind_register_native_and_builtin_types=e.asm.Ba).apply(null,arguments)};
var P=e._free=function(){return(P=e._free=e.asm.Ca).apply(null,arguments)},tf=e._emscripten_get_global_libc=function(){return(tf=e._emscripten_get_global_libc=e.asm.Da).apply(null,arguments)},rb=e._pthread_self=function(){return(rb=e._pthread_self=e.asm.Ea).apply(null,arguments)},sb=e.___pthread_tsd_run_dtors=function(){return(sb=e.___pthread_tsd_run_dtors=e.asm.Fa).apply(null,arguments)};
e._emscripten_current_thread_process_queued_calls=function(){return(e._emscripten_current_thread_process_queued_calls=e.asm.Ga).apply(null,arguments)};
var qb=e._emscripten_register_main_browser_thread_id=function(){return(qb=e._emscripten_register_main_browser_thread_id=e.asm.Ha).apply(null,arguments)},lb=e.__emscripten_do_dispatch_to_thread=function(){return(lb=e.__emscripten_do_dispatch_to_thread=e.asm.Ia).apply(null,arguments)},Df=e._emscripten_sync_run_in_main_thread_4=function(){return(Df=e._emscripten_sync_run_in_main_thread_4=e.asm.Ja).apply(null,arguments)},ub=e._emscripten_main_thread_process_queued_calls=function(){return(ub=e._emscripten_main_thread_process_queued_calls=
e.asm.Ka).apply(null,arguments)},wd=e._emscripten_run_in_main_runtime_thread_js=function(){return(wd=e._emscripten_run_in_main_runtime_thread_js=e.asm.La).apply(null,arguments)},Cd=e.__emscripten_call_on_thread=function(){return(Cd=e.__emscripten_call_on_thread=e.asm.Ma).apply(null,arguments)},pb=e.__emscripten_thread_init=function(){return(pb=e.__emscripten_thread_init=e.asm.Na).apply(null,arguments)},ud=e.stackSave=function(){return(ud=e.stackSave=e.asm.Oa).apply(null,arguments)},yb=e.stackRestore=
function(){return(yb=e.stackRestore=e.asm.Pa).apply(null,arguments)},vd=e.stackAlloc=function(){return(vd=e.stackAlloc=e.asm.Qa).apply(null,arguments)},xb=e._emscripten_stack_set_limits=function(){return(xb=e._emscripten_stack_set_limits=e.asm.Ra).apply(null,arguments)},Ef=e._memalign=function(){return(Ef=e._memalign=e.asm.Sa).apply(null,arguments)};e.dynCall_jiji=function(){return(e.dynCall_jiji=e.asm.Ta).apply(null,arguments)};
e.dynCall_viijii=function(){return(e.dynCall_viijii=e.asm.Ua).apply(null,arguments)};e.dynCall_iiiiiijj=function(){return(e.dynCall_iiiiiijj=e.asm.Va).apply(null,arguments)};e.dynCall_iiiiij=function(){return(e.dynCall_iiiiij=e.asm.Wa).apply(null,arguments)};e.dynCall_iiiiijj=function(){return(e.dynCall_iiiiijj=e.asm.Xa).apply(null,arguments)};var tb=e.__emscripten_allow_main_runtime_queued_calls=16030584,ob=e.__emscripten_main_thread_futex=20034388;e.addRunDependency=eb;e.removeRunDependency=fb;
e.FS_createPath=yc;e.FS_createDataFile=Ac;e.FS_createPreloadedFile=Dc;e.FS_createLazyFile=Cc;e.FS_createDevice=M;e.FS_unlink=rc;e.PThread=O;e.PThread=O;e.wasmMemory=za;e.ExitStatus=oa;var Gf;function oa(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}db=function Hf(){Gf||If();Gf||(db=Hf)};
function If(){function a(){if(!Gf&&(Gf=!0,e.calledRun=!0,!Ba)){Ua();z||($b=!1,Za(Sa));if(e.onRuntimeInitialized)e.onRuntimeInitialized();if(Jf){var b=e._main;try{var c=b(0,0);wb(c,!0)}catch(d){d instanceof oa||"unwind"==d||((b=d)&&"object"===typeof d&&d.stack&&(b=[d,d.stack]),t("exception thrown: "+b),da(1,d))}finally{}}if(!z){if(e.postRun)for("function"==typeof e.postRun&&(e.postRun=[e.postRun]);e.postRun.length;)b=e.postRun.shift(),Ta.unshift(b);Za(Ta)}}}if(!(0<bb))if(z)Ua(),postMessage({cmd:"loaded"});
else{if(!z){if(e.preRun)for("function"==typeof e.preRun&&(e.preRun=[e.preRun]);e.preRun.length;)$a();Za(Qa)}0<bb||(e.setStatus?(e.setStatus("Running..."),setTimeout(function(){setTimeout(function(){e.setStatus("")},1);a()},1)):a())}}e.run=If;function wb(a,b){Ca=a;if(!b||!Ab()||0!==a){if(!b&&z)throw postMessage({cmd:"exitProcess",returnCode:a}),new oa(a);if(!Ab()){O.vd();if(e.onExit)e.onExit(a);Ba=!0}da(a,new oa(a))}}if(e.preInit)for("function"==typeof e.preInit&&(e.preInit=[e.preInit]);0<e.preInit.length;)e.preInit.pop()();
var Jf=!0;e.noInitialRun&&(Jf=!1);z&&(noExitRuntime=!1,O.ad());If();
